// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details

import { describe, expect, it } from "vitest"

import {
  selectOfferFeeStructures,
  sumRegistrationFee,
} from "@/components/school-marketing/application/offer/fee-structures"

type Row = {
  id: string
  isAutoGenerated: boolean
  sourceSignals: Record<string, unknown> | null
  totalAmount: number
  registrationFee: number | null
  admissionFee: number | null
}

const GRADE = "grade-1"

function row(overrides: Partial<Row> & { id: string }): Row {
  return {
    isAutoGenerated: false,
    sourceSignals: null,
    totalAmount: 1000,
    registrationFee: null,
    admissionFee: null,
    ...overrides,
  }
}

const amountOf = (r: Row) => r.totalAmount

describe("selectOfferFeeStructures", () => {
  it("keeps admin-created and class-linked rows additive", () => {
    const rows = [
      row({ id: "school-wide", registrationFee: 100 }),
      row({ id: "class-linked", registrationFee: 50 }),
    ]
    expect(selectOfferFeeStructures(rows, GRADE, amountOf)).toEqual(rows)
  })

  it("passes a single auto-generated grade row through unchanged", () => {
    const rows = [
      row({
        id: "auto-base",
        isAutoGenerated: true,
        sourceSignals: { gradeId: GRADE },
        registrationFee: 200,
      }),
    ]
    expect(selectOfferFeeStructures(rows, GRADE, amountOf)).toEqual(rows)
  })

  it("quotes ONE variant of a grade's pricing group — the base one — never the sum", () => {
    const base = row({
      id: "auto-base",
      isAutoGenerated: true,
      sourceSignals: { gradeId: GRADE },
      totalAmount: 5000,
      registrationFee: 200,
    })
    const science = row({
      id: "auto-science",
      isAutoGenerated: true,
      sourceSignals: { gradeId: GRADE, streamId: "science" },
      totalAmount: 5500,
      registrationFee: 200,
    })
    const boarding = row({
      id: "auto-boarding",
      isAutoGenerated: true,
      sourceSignals: { gradeId: GRADE, studentType: "BOARDING" },
      totalAmount: 9000,
      registrationFee: 200,
    })
    const extra = row({ id: "bus", registrationFee: 30 })

    const selected = selectOfferFeeStructures(
      [science, boarding, base, extra],
      GRADE,
      amountOf
    )

    expect(selected.map((r) => r.id)).toEqual(["bus", "auto-base"])
    expect(sumRegistrationFee(selected, null)).toBe(230)
  })

  it("falls back to the cheapest pinned variant when there is no base row", () => {
    const science = row({
      id: "auto-science",
      isAutoGenerated: true,
      sourceSignals: { gradeId: GRADE, streamId: "science" },
      totalAmount: 5500,
    })
    const arts = row({
      id: "auto-arts",
      isAutoGenerated: true,
      sourceSignals: { gradeId: GRADE, streamId: "arts" },
      totalAmount: 5200,
    })
    const selected = selectOfferFeeStructures([science, arts], GRADE, amountOf)
    expect(selected.map((r) => r.id)).toEqual(["auto-arts"])
  })

  it("treats auto-generated rows of another grade as additive (they only arrive via a class link)", () => {
    const other = row({
      id: "auto-other-grade",
      isAutoGenerated: true,
      sourceSignals: { gradeId: "grade-2" },
    })
    const mine = row({
      id: "auto-mine",
      isAutoGenerated: true,
      sourceSignals: { gradeId: GRADE },
    })
    expect(
      selectOfferFeeStructures([other, mine], GRADE, amountOf).map((r) => r.id)
    ).toEqual(["auto-other-grade", "auto-mine"])
  })

  it("with no resolvable grade, auto-generated rows are never grouped", () => {
    const a = row({
      id: "a",
      isAutoGenerated: true,
      sourceSignals: { gradeId: GRADE },
    })
    expect(selectOfferFeeStructures([a], null, amountOf)).toEqual([a])
  })
})

describe("sumRegistrationFee", () => {
  it("adds the registration and one-time admission components", () => {
    expect(
      sumRegistrationFee(
        [
          { registrationFee: 200, admissionFee: 100 },
          { registrationFee: 50, admissionFee: null },
        ],
        null
      )
    ).toBe(350)
  })

  it("falls back to the campaign fee only when no structure defines one", () => {
    expect(sumRegistrationFee([], 75)).toBe(75)
    expect(
      sumRegistrationFee([{ registrationFee: 20, admissionFee: null }], 75)
    ).toBe(20)
    expect(sumRegistrationFee([], null)).toBe(0)
  })
})
