// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details

/**
 * Action error codes for i18n-safe error responses.
 *
 * Server actions return these codes instead of hardcoded English strings.
 * Clients resolve them to translated strings via the dictionary.
 *
 * @see src/lib/resolve-action-error.ts for client-side resolution
 * @see src/components/internationalization/en.json common.errors for translations
 */

export const ACTION_ERRORS = {
  // Generic
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  MISSING_SCHOOL: "MISSING_SCHOOL",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  RATE_LIMITED: "RATE_LIMITED",
  UNKNOWN: "UNKNOWN",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",

  // CRUD operations (generic)
  CREATE_FAILED: "CREATE_FAILED",
  UPDATE_FAILED: "UPDATE_FAILED",
  DELETE_FAILED: "DELETE_FAILED",
  SAVE_FAILED: "SAVE_FAILED",
  LOAD_FAILED: "LOAD_FAILED",
  HAS_DEPENDENCIES: "HAS_DEPENDENCIES",

  // Student
  STUDENT_NOT_FOUND: "STUDENT_NOT_FOUND",
  STUDENT_CREATE_FAILED: "STUDENT_CREATE_FAILED",
  STUDENT_UPDATE_FAILED: "STUDENT_UPDATE_FAILED",
  STUDENT_DELETE_FAILED: "STUDENT_DELETE_FAILED",
  STUDENT_ARCHIVE_FAILED: "STUDENT_ARCHIVE_FAILED",
  STUDENT_RESTORE_FAILED: "STUDENT_RESTORE_FAILED",
  STUDENT_PURGE_FAILED: "STUDENT_PURGE_FAILED",
  STUDENT_RESTORE_CONFLICT: "STUDENT_RESTORE_CONFLICT",
  PURGE_TOKEN_INVALID: "PURGE_TOKEN_INVALID",
  PURGE_TOKEN_EXPIRED: "PURGE_TOKEN_EXPIRED",

  // Teacher
  TEACHER_NOT_FOUND: "TEACHER_NOT_FOUND",
  TEACHER_CREATE_FAILED: "TEACHER_CREATE_FAILED",
  TEACHER_UPDATE_FAILED: "TEACHER_UPDATE_FAILED",
  TEACHER_DELETE_FAILED: "TEACHER_DELETE_FAILED",

  // Class
  CLASS_NOT_FOUND: "CLASS_NOT_FOUND",
  CLASS_CREATE_FAILED: "CLASS_CREATE_FAILED",
  CLASS_UPDATE_FAILED: "CLASS_UPDATE_FAILED",
  CLASS_DELETE_FAILED: "CLASS_DELETE_FAILED",

  // Subject
  SUBJECT_NOT_FOUND: "SUBJECT_NOT_FOUND",
  SUBJECT_CREATE_FAILED: "SUBJECT_CREATE_FAILED",
  SUBJECT_UPDATE_FAILED: "SUBJECT_UPDATE_FAILED",
  SUBJECT_DELETE_FAILED: "SUBJECT_DELETE_FAILED",

  // Classroom
  CLASSROOM_NOT_FOUND: "CLASSROOM_NOT_FOUND",
  CLASSROOM_CREATE_FAILED: "CLASSROOM_CREATE_FAILED",
  CLASSROOM_UPDATE_FAILED: "CLASSROOM_UPDATE_FAILED",
  CLASSROOM_DELETE_FAILED: "CLASSROOM_DELETE_FAILED",
  CLASSROOM_LIMIT_REACHED: "CLASSROOM_LIMIT_REACHED",
  CAPACITY_EXCEEDS_ROOM: "CAPACITY_EXCEEDS_ROOM",
  NO_TEACHERS_FOUND: "NO_TEACHERS_FOUND",
  NO_PERIODS_FOUND: "NO_PERIODS_FOUND",
  NO_GRADES_FOUND: "NO_GRADES_FOUND",

  // Parent
  PARENT_NOT_FOUND: "PARENT_NOT_FOUND",
  PARENT_CREATE_FAILED: "PARENT_CREATE_FAILED",
  PARENT_UPDATE_FAILED: "PARENT_UPDATE_FAILED",
  PARENT_DELETE_FAILED: "PARENT_DELETE_FAILED",

  // Staff
  STAFF_NOT_FOUND: "STAFF_NOT_FOUND",
  STAFF_CREATE_FAILED: "STAFF_CREATE_FAILED",
  STAFF_UPDATE_FAILED: "STAFF_UPDATE_FAILED",
  STAFF_DELETE_FAILED: "STAFF_DELETE_FAILED",

  // Announcement
  ANNOUNCEMENT_NOT_FOUND: "ANNOUNCEMENT_NOT_FOUND",
  ANNOUNCEMENT_CREATE_FAILED: "ANNOUNCEMENT_CREATE_FAILED",
  ANNOUNCEMENT_UPDATE_FAILED: "ANNOUNCEMENT_UPDATE_FAILED",
  ANNOUNCEMENT_DELETE_FAILED: "ANNOUNCEMENT_DELETE_FAILED",

  // Assignment
  ASSIGNMENT_NOT_FOUND: "ASSIGNMENT_NOT_FOUND",
  ASSIGNMENT_CREATE_FAILED: "ASSIGNMENT_CREATE_FAILED",
  ASSIGNMENT_UPDATE_FAILED: "ASSIGNMENT_UPDATE_FAILED",
  ASSIGNMENT_DELETE_FAILED: "ASSIGNMENT_DELETE_FAILED",

  // Event
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
  EVENT_CREATE_FAILED: "EVENT_CREATE_FAILED",
  EVENT_UPDATE_FAILED: "EVENT_UPDATE_FAILED",
  EVENT_DELETE_FAILED: "EVENT_DELETE_FAILED",

  // Grade
  GRADE_NOT_FOUND: "GRADE_NOT_FOUND",
  GRADE_CREATE_FAILED: "GRADE_CREATE_FAILED",
  GRADE_UPDATE_FAILED: "GRADE_UPDATE_FAILED",
  GRADE_DELETE_FAILED: "GRADE_DELETE_FAILED",
  GRADE_SUBMIT_FAILED: "GRADE_SUBMIT_FAILED",

  // Exam
  EXAM_NOT_FOUND: "EXAM_NOT_FOUND",
  EXAM_CREATE_FAILED: "EXAM_CREATE_FAILED",
  EXAM_UPDATE_FAILED: "EXAM_UPDATE_FAILED",
  EXAM_DELETE_FAILED: "EXAM_DELETE_FAILED",
  EXAM_SUBMIT_FAILED: "EXAM_SUBMIT_FAILED",
  EXAM_GENERATE_FAILED: "EXAM_GENERATE_FAILED",

  // Question Bank
  QUESTION_NOT_FOUND: "QUESTION_NOT_FOUND",
  QUESTION_CREATE_FAILED: "QUESTION_CREATE_FAILED",
  QUESTION_UPDATE_FAILED: "QUESTION_UPDATE_FAILED",
  QUESTION_DELETE_FAILED: "QUESTION_DELETE_FAILED",
  QUESTION_ANALYZE_FAILED: "QUESTION_ANALYZE_FAILED",

  // Exam Template / Session
  TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",
  TEMPLATE_CREATE_FAILED: "TEMPLATE_CREATE_FAILED",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",

  // Certificate
  CERTIFICATE_NOT_FOUND: "CERTIFICATE_NOT_FOUND",
  CERTIFICATE_CREATE_FAILED: "CERTIFICATE_CREATE_FAILED",
  CERTIFICATE_ISSUE_FAILED: "CERTIFICATE_ISSUE_FAILED",

  // Attendance
  ATTENDANCE_MARK_FAILED: "ATTENDANCE_MARK_FAILED",
  ATTENDANCE_UPDATE_FAILED: "ATTENDANCE_UPDATE_FAILED",
  ATTENDANCE_NOT_FOUND: "ATTENDANCE_NOT_FOUND",
  EXCUSE_CREATE_FAILED: "EXCUSE_CREATE_FAILED",
  EXCUSE_UPDATE_FAILED: "EXCUSE_UPDATE_FAILED",
  HALL_PASS_CREATE_FAILED: "HALL_PASS_CREATE_FAILED",
  HALL_PASS_NOT_FOUND: "HALL_PASS_NOT_FOUND",
  HALL_PASS_RETURN_FAILED: "HALL_PASS_RETURN_FAILED",
  HALL_PASS_CANCEL_FAILED: "HALL_PASS_CANCEL_FAILED",
  GEOFENCE_CREATE_FAILED: "GEOFENCE_CREATE_FAILED",
  GEOFENCE_UPDATE_FAILED: "GEOFENCE_UPDATE_FAILED",
  GEOFENCE_DELETE_FAILED: "GEOFENCE_DELETE_FAILED",
  GEOFENCE_NOT_FOUND: "GEOFENCE_NOT_FOUND",
  INTERVENTION_CREATE_FAILED: "INTERVENTION_CREATE_FAILED",
  INTERVENTION_UPDATE_FAILED: "INTERVENTION_UPDATE_FAILED",
  INTERVENTION_NOT_FOUND: "INTERVENTION_NOT_FOUND",
  INTENTION_NOT_FOUND: "INTENTION_NOT_FOUND",
  INTENTION_CREATE_FAILED: "INTENTION_CREATE_FAILED",
  LETTER_GENERATE_FAILED: "LETTER_GENERATE_FAILED",
  PREDICTION_FAILED: "PREDICTION_FAILED",
  TRANSLATION_FAILED: "TRANSLATION_FAILED",
  GAMIFICATION_FAILED: "GAMIFICATION_FAILED",
  COMPETITION_NOT_FOUND: "COMPETITION_NOT_FOUND",
  KIOSK_REGISTER_FAILED: "KIOSK_REGISTER_FAILED",

  // Finance
  FEE_NOT_FOUND: "FEE_NOT_FOUND",
  FEE_CREATE_FAILED: "FEE_CREATE_FAILED",
  FEE_UPDATE_FAILED: "FEE_UPDATE_FAILED",
  FEE_DELETE_FAILED: "FEE_DELETE_FAILED",
  FEE_FULLY_PAID: "FEE_FULLY_PAID",
  FEE_ALREADY_ASSIGNED: "FEE_ALREADY_ASSIGNED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_CANNOT_DELETE: "PAYMENT_CANNOT_DELETE",
  PAYMENT_HAS_REFUND: "PAYMENT_HAS_REFUND",
  FINE_CANNOT_DELETE: "FINE_CANNOT_DELETE",
  FINE_WAIVED_CANNOT_DELETE: "FINE_WAIVED_CANNOT_DELETE",
  INVOICE_NOT_FOUND: "INVOICE_NOT_FOUND",
  INVOICE_CREATE_FAILED: "INVOICE_CREATE_FAILED",
  INVOICE_UPDATE_FAILED: "INVOICE_UPDATE_FAILED",
  INVOICE_DELETE_FAILED: "INVOICE_DELETE_FAILED",
  SALARY_CREATE_FAILED: "SALARY_CREATE_FAILED",
  SALARY_UPDATE_FAILED: "SALARY_UPDATE_FAILED",
  PAYROLL_CREATE_FAILED: "PAYROLL_CREATE_FAILED",
  PAYROLL_UPDATE_FAILED: "PAYROLL_UPDATE_FAILED",
  RECEIPT_CREATE_FAILED: "RECEIPT_CREATE_FAILED",
  RECEIPT_NOT_FOUND: "RECEIPT_NOT_FOUND",
  BUDGET_CREATE_FAILED: "BUDGET_CREATE_FAILED",
  EXPENSE_CREATE_FAILED: "EXPENSE_CREATE_FAILED",
  WALLET_CREATE_FAILED: "WALLET_CREATE_FAILED",
  TRANSFER_FAILED: "TRANSFER_FAILED",
  FEE_STRUCTURE_HAS_ASSIGNMENTS: "FEE_STRUCTURE_HAS_ASSIGNMENTS",
  FEE_ASSIGNMENT_HAS_PAYMENTS: "FEE_ASSIGNMENT_HAS_PAYMENTS",
  SCHOLARSHIP_HAS_ASSIGNMENTS: "SCHOLARSHIP_HAS_ASSIGNMENTS",
  INVOICE_DUPLICATE_NUMBER: "INVOICE_DUPLICATE_NUMBER",
  INVOICE_FETCH_FAILED: "INVOICE_FETCH_FAILED",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  CHECKOUT_SESSION_FAILED: "CHECKOUT_SESSION_FAILED",
  PERMISSION_GRANT_FAILED: "PERMISSION_GRANT_FAILED",
  PERMISSION_REVOKE_FAILED: "PERMISSION_REVOKE_FAILED",
  PERMISSION_COPY_FAILED: "PERMISSION_COPY_FAILED",

  // Timetable
  TIMETABLE_NOT_FOUND: "TIMETABLE_NOT_FOUND",
  TIMETABLE_CREATE_FAILED: "TIMETABLE_CREATE_FAILED",
  TIMETABLE_UPDATE_FAILED: "TIMETABLE_UPDATE_FAILED",
  TIMETABLE_CONFLICT: "TIMETABLE_CONFLICT",
  TIMETABLE_GENERATE_FAILED: "TIMETABLE_GENERATE_FAILED",

  // Admission
  ADMISSION_NOT_FOUND: "ADMISSION_NOT_FOUND",
  ADMISSION_UPDATE_FAILED: "ADMISSION_UPDATE_FAILED",
  APPLICATION_NOT_FOUND: "APPLICATION_NOT_FOUND",
  APPLICATION_CREATE_FAILED: "APPLICATION_CREATE_FAILED",
  APPLICATION_UPDATE_FAILED: "APPLICATION_UPDATE_FAILED",
  ENROLLMENT_FAILED: "ENROLLMENT_FAILED",
  CAMPAIGN_NOT_FOUND: "CAMPAIGN_NOT_FOUND",
  CAMPAIGN_CREATE_FAILED: "CAMPAIGN_CREATE_FAILED",
  CAMPAIGN_UPDATE_FAILED: "CAMPAIGN_UPDATE_FAILED",
  CAMPAIGN_DELETE_FAILED: "CAMPAIGN_DELETE_FAILED",
  CAMPAIGN_HAS_APPLICATIONS: "CAMPAIGN_HAS_APPLICATIONS",
  APPLICATION_STATUS_INVALID: "APPLICATION_STATUS_INVALID",
  OFFER_EXPIRED: "OFFER_EXPIRED",
  PLACEMENT_INVALID_STATUS: "PLACEMENT_INVALID_STATUS",
  PLACEMENT_NO_USER: "PLACEMENT_NO_USER",
  SECTION_AT_CAPACITY: "SECTION_AT_CAPACITY",
  STUDENT_ALREADY_IN_SECTION: "STUDENT_ALREADY_IN_SECTION",
  NO_CLASSES_FOR_GRADE: "NO_CLASSES_FOR_GRADE",
  STUDENT_ALREADY_ENROLLED: "STUDENT_ALREADY_ENROLLED",
  MERIT_GENERATE_FAILED: "MERIT_GENERATE_FAILED",
  APPLICATION_FEE_REQUIRED: "APPLICATION_FEE_REQUIRED",

  // Messaging
  MESSAGE_SEND_FAILED: "MESSAGE_SEND_FAILED",
  MESSAGE_EDIT_FAILED: "MESSAGE_EDIT_FAILED",
  MESSAGE_DELETE_FAILED: "MESSAGE_DELETE_FAILED",
  MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND",
  MESSAGE_REACTION_FAILED: "MESSAGE_REACTION_FAILED",
  CONVERSATION_CREATE_FAILED: "CONVERSATION_CREATE_FAILED",
  CONVERSATION_NOT_FOUND: "CONVERSATION_NOT_FOUND",
  CONVERSATION_ARCHIVE_FAILED: "CONVERSATION_ARCHIVE_FAILED",
  CONVERSATION_LEAVE_FAILED: "CONVERSATION_LEAVE_FAILED",
  PARTICIPANT_ADD_FAILED: "PARTICIPANT_ADD_FAILED",
  PARTICIPANT_REMOVE_FAILED: "PARTICIPANT_REMOVE_FAILED",
  SEARCH_QUERY_TOO_SHORT: "SEARCH_QUERY_TOO_SHORT",
  WHATSAPP_NOT_CONNECTED: "WHATSAPP_NOT_CONNECTED",

  // Notification
  NOTIFICATION_SEND_FAILED: "NOTIFICATION_SEND_FAILED",
  NOTIFICATION_UPDATE_FAILED: "NOTIFICATION_UPDATE_FAILED",

  // School / Config
  SCHOOL_UPDATE_FAILED: "SCHOOL_UPDATE_FAILED",
  SCHOOL_NOT_FOUND: "SCHOOL_NOT_FOUND",
  MEMBERSHIP_UPDATE_FAILED: "MEMBERSHIP_UPDATE_FAILED",
  INVITATION_FAILED: "INVITATION_FAILED",

  // Settings
  SETTINGS_UPDATE_FAILED: "SETTINGS_UPDATE_FAILED",
  PASSWORD_CHANGE_FAILED: "PASSWORD_CHANGE_FAILED",
  PROFILE_UPDATE_FAILED: "PROFILE_UPDATE_FAILED",

  // Reports
  REPORT_GENERATE_FAILED: "REPORT_GENERATE_FAILED",
  EXPORT_FAILED: "EXPORT_FAILED",
  IMPORT_FAILED: "IMPORT_FAILED",

  // Year Level / Academic
  YEAR_LEVEL_NOT_FOUND: "YEAR_LEVEL_NOT_FOUND",
  YEAR_LEVEL_CREATE_FAILED: "YEAR_LEVEL_CREATE_FAILED",
  YEAR_LEVEL_UPDATE_FAILED: "YEAR_LEVEL_UPDATE_FAILED",
  YEAR_LEVEL_DELETE_FAILED: "YEAR_LEVEL_DELETE_FAILED",
  ACADEMIC_PERIOD_NOT_FOUND: "ACADEMIC_PERIOD_NOT_FOUND",
  ACADEMIC_PERIOD_CREATE_FAILED: "ACADEMIC_PERIOD_CREATE_FAILED",
  ACADEMIC_TERM_NOT_FOUND: "ACADEMIC_TERM_NOT_FOUND",
  ACADEMIC_TERM_CREATE_FAILED: "ACADEMIC_TERM_CREATE_FAILED",

  // Department
  DEPARTMENT_NOT_FOUND: "DEPARTMENT_NOT_FOUND",
  DEPARTMENT_CREATE_FAILED: "DEPARTMENT_CREATE_FAILED",
  DEPARTMENT_UPDATE_FAILED: "DEPARTMENT_UPDATE_FAILED",
  DEPARTMENT_DELETE_FAILED: "DEPARTMENT_DELETE_FAILED",

  // Library
  BOOK_NOT_FOUND: "BOOK_NOT_FOUND",
  BOOK_CREATE_FAILED: "BOOK_CREATE_FAILED",
  BOOK_UPDATE_FAILED: "BOOK_UPDATE_FAILED",
  BORROW_FAILED: "BORROW_FAILED",
  RETURN_FAILED: "RETURN_FAILED",

  // Stream / LMS
  COURSE_NOT_FOUND: "COURSE_NOT_FOUND",
  COURSE_CREATE_FAILED: "COURSE_CREATE_FAILED",
  COURSE_UPDATE_FAILED: "COURSE_UPDATE_FAILED",
  LESSON_NOT_FOUND: "LESSON_NOT_FOUND",
  CHAPTER_NOT_FOUND: "CHAPTER_NOT_FOUND",
  ENROLLMENT_CREATE_FAILED: "ENROLLMENT_CREATE_FAILED",

  // Upload / File
  UPLOAD_FAILED: "UPLOAD_FAILED",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",

  // Transportation
  VEHICLE_NOT_FOUND: "VEHICLE_NOT_FOUND",
  VEHICLE_CREATE_FAILED: "VEHICLE_CREATE_FAILED",
  VEHICLE_UPDATE_FAILED: "VEHICLE_UPDATE_FAILED",
  VEHICLE_DELETE_FAILED: "VEHICLE_DELETE_FAILED",
  VEHICLE_PLATE_TAKEN: "VEHICLE_PLATE_TAKEN",
  DRIVER_NOT_FOUND: "DRIVER_NOT_FOUND",
  DRIVER_CREATE_FAILED: "DRIVER_CREATE_FAILED",
  DRIVER_UPDATE_FAILED: "DRIVER_UPDATE_FAILED",
  DRIVER_DELETE_FAILED: "DRIVER_DELETE_FAILED",
  DRIVER_LICENSE_TAKEN: "DRIVER_LICENSE_TAKEN",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  ROUTE_CREATE_FAILED: "ROUTE_CREATE_FAILED",
  ROUTE_UPDATE_FAILED: "ROUTE_UPDATE_FAILED",
  ROUTE_DELETE_FAILED: "ROUTE_DELETE_FAILED",
  ROUTE_NAME_TAKEN: "ROUTE_NAME_TAKEN",
  STOP_NOT_FOUND: "STOP_NOT_FOUND",
  STOP_CREATE_FAILED: "STOP_CREATE_FAILED",
  STOP_UPDATE_FAILED: "STOP_UPDATE_FAILED",
  STOP_DELETE_FAILED: "STOP_DELETE_FAILED",
  STOP_ORDER_CONFLICT: "STOP_ORDER_CONFLICT",
  ROUTE_ASSIGNMENT_NOT_FOUND: "ROUTE_ASSIGNMENT_NOT_FOUND",
  ROUTE_ASSIGNMENT_CREATE_FAILED: "ROUTE_ASSIGNMENT_CREATE_FAILED",
  ROUTE_ASSIGNMENT_UPDATE_FAILED: "ROUTE_ASSIGNMENT_UPDATE_FAILED",
  ROUTE_ASSIGNMENT_OVERLAP: "ROUTE_ASSIGNMENT_OVERLAP",
  ROUTE_ASSIGNMENT_END_FAILED: "ROUTE_ASSIGNMENT_END_FAILED",

  // Transportation — Trips (M2)
  TRIP_NOT_FOUND: "TRIP_NOT_FOUND",
  TRIP_CREATE_FAILED: "TRIP_CREATE_FAILED",
  TRIP_UPDATE_FAILED: "TRIP_UPDATE_FAILED",
  TRIP_INVALID_STATE: "TRIP_INVALID_STATE",
  TRIP_DUPLICATE: "TRIP_DUPLICATE",
  BOARDING_NOT_FOUND: "BOARDING_NOT_FOUND",
  BOARDING_UPDATE_FAILED: "BOARDING_UPDATE_FAILED",

  // Transportation — Settings (Phase 4)
  TRANSPORTATION_SETTINGS_UPDATE_FAILED:
    "TRANSPORTATION_SETTINGS_UPDATE_FAILED",

  // Transportation — Geofence webhook (Phase 4.4)
  MISSING_API_TOKEN: "MISSING_API_TOKEN",
  INVALID_API_TOKEN: "INVALID_API_TOKEN",
  INSUFFICIENT_SCOPE: "INSUFFICIENT_SCOPE",
  API_TOKEN_CREATE_FAILED: "API_TOKEN_CREATE_FAILED",
  API_TOKEN_REVOKE_FAILED: "API_TOKEN_REVOKE_FAILED",
} as const

export type ActionErrorCode = (typeof ACTION_ERRORS)[keyof typeof ACTION_ERRORS]

/**
 * Helper to create error responses with codes.
 * Returns a shape compatible with ActionResponse.
 *
 * @param code - One of the ACTION_ERRORS constants
 * @param details - Optional additional context (not shown to users, useful for debugging)
 */
export function actionError(code: ActionErrorCode, details?: string) {
  return {
    success: false as const,
    error: code,
    details,
  }
}
