// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details

import { db } from "@/lib/db"

/**
 * Step 7 safety net: if a school has academic structure (grades) + pricing
 * (tuitionFee set) but zero auto-generated FeeStructures, re-run provisioning.
 *
 * Why: onboarding runs `provisionSchoolFees` in next/server `after()`. On
 * serverless cold drops the function can be terminated before `after()`
 * completes, leaving the school with empty FeeStructures despite having
 * grades + tuition. Admins then open /finance/fees and see nothing.
 *
 * This function runs fast (two counts + an optional provisioning call),
 * is fully idempotent, and swallows errors — it's a background best-effort
 * heal, never a critical path.
 */
export async function selfHealFeeProvisioning(schoolId: string): Promise<void> {
  try {
    const [autoCount, gradeCount, school] = await Promise.all([
      db.feeStructure.count({
        where: { schoolId, isAutoGenerated: true, isActive: true },
      }),
      db.academicGrade.count({ where: { schoolId } }),
      db.school.findUnique({
        where: { id: schoolId },
        select: { tuitionFee: true },
      }),
    ])

    const needsHeal =
      autoCount === 0 &&
      gradeCount > 0 &&
      school?.tuitionFee != null &&
      Number(school.tuitionFee) > 0

    if (!needsHeal) return

    const { provisionSchoolFees } = await import("@/lib/fee-provisioning")
    const result = await provisionSchoolFees(schoolId, { mode: "recompute" })
    console.log(
      `[selfHealFeeProvisioning] schoolId=${schoolId} created=${result.created} updated=${result.updated} errors=${result.errors.length}`
    )
  } catch (err) {
    console.error(`[selfHealFeeProvisioning] Failed for ${schoolId}:`, err)
  }
}
