import { db } from "@/lib/db"

/**
 * Auto-assign matching FeeStructure records to a student.
 *
 * Mirrors the logic in admission/actions.ts confirmEnrollment() but works
 * for manually enrolled students (wizard or /students/enroll).
 *
 * Matches fee structures by:
 * 1. Admin-created school-wide structures (classId = null, not auto-generated)
 * 2. Class-linked structures where classId belongs to the student's grade
 * 3. Auto-generated per-grade structures via sourceSignals.gradeId
 *
 * Skips duplicates via upsert. Non-blocking — callers should .catch() this.
 */
export async function autoAssignFeesForStudent(
  schoolId: string,
  studentId: string,
  academicGradeId: string
): Promise<{ assignedCount: number }> {
  // Get current academic year
  const currentYear = await db.schoolYear.findFirst({
    where: { schoolId },
    orderBy: { startDate: "desc" },
    select: { yearName: true },
  })
  const academicYear =
    currentYear?.yearName ||
    `${new Date().getFullYear()}-${new Date().getFullYear() + 1}`

  // Find classes for this grade (to match grade-specific fee structures)
  const gradeClasses = await db.class.findMany({
    where: { schoolId, gradeId: academicGradeId },
    select: { id: true },
  })
  const gradeClassIds = gradeClasses.map((c) => c.id)

  // Find matching active fee structures
  const feeStructures = await db.feeStructure.findMany({
    where: {
      schoolId,
      academicYear,
      isActive: true,
      OR: [
        // Admin school-wide (classId null, not auto-generated)
        { classId: null, isAutoGenerated: false },
        // Class-linked structures whose classId belongs to this grade
        ...(gradeClassIds.length > 0
          ? [{ classId: { in: gradeClassIds } }]
          : []),
        // Auto-generated per-grade structures — match on JSON signal
        {
          isAutoGenerated: true,
          sourceSignals: {
            path: ["gradeId"],
            equals: academicGradeId,
          },
        },
      ],
    },
    select: { id: true, totalAmount: true },
  })

  if (feeStructures.length === 0) return { assignedCount: 0 }

  let assignedCount = 0
  const assignmentIds: string[] = []

  for (const structure of feeStructures) {
    // Upsert to avoid duplicates (idempotent)
    try {
      const upserted = await db.feeAssignment.upsert({
        where: {
          studentId_feeStructureId_academicYear: {
            studentId,
            feeStructureId: structure.id,
            academicYear,
          },
        },
        create: {
          schoolId,
          studentId,
          feeStructureId: structure.id,
          academicYear,
          finalAmount: Number(structure.totalAmount),
          totalDiscount: 0,
          status: "PENDING",
        },
        update: {}, // No-op if already exists
        select: { id: true },
      })
      assignedCount++
      assignmentIds.push(upserted.id)
    } catch (err) {
      // Skip on unique constraint violation (race condition safety)
      console.warn(
        `[autoAssignFeesForStudent] Skipped duplicate for student=${studentId} structure=${structure.id}:`,
        err
      )
    }
  }

  // Step 23: also ensure UserInvoice rows per installment. Idempotent and
  // non-blocking — invoice-sync failure should never roll back the
  // assignment itself. Without this call, students see empty /my-fees
  // because downstream views read from UserInvoice, not FeeAssignment.
  if (assignmentIds.length > 0) {
    try {
      const { ensureInvoicesForAssignment } =
        await import("@/lib/fee-invoice-sync")
      await Promise.all(
        assignmentIds.map((id) =>
          ensureInvoicesForAssignment(schoolId, id).catch((err) =>
            console.warn(
              `[autoAssignFeesForStudent] Invoice sync failed for assignment=${id}:`,
              err
            )
          )
        )
      )
    } catch (err) {
      console.warn("[autoAssignFeesForStudent] Invoice sync batch failed:", err)
    }
  }

  // Steps 25-27: notify the student + their guardians that fees have been
  // assigned. in_app + email + whatsapp all dispatch from the same call —
  // per-user preferences are honored inside dispatchNotification.
  if (assignmentIds.length > 0) {
    try {
      await notifyStudentFeesAssigned(schoolId, studentId, assignmentIds.length)
    } catch (err) {
      console.warn("[autoAssignFeesForStudent] Notification failed:", err)
    }
  }

  if (assignedCount > 0) {
    console.log(
      `[autoAssignFeesForStudent] Assigned ${assignedCount} fee structure(s) to student ${studentId}`
    )
  }

  return { assignedCount }
}

async function notifyStudentFeesAssigned(
  schoolId: string,
  studentId: string,
  assignmentCount: number
): Promise<void> {
  const student = await db.student.findFirst({
    where: { id: studentId, schoolId },
    select: {
      firstName: true,
      userId: true,
      studentGuardians: {
        select: {
          guardian: {
            select: { userId: true },
          },
        },
      },
    },
  })
  if (!student) return

  const [school, { dispatchNotification }] = await Promise.all([
    db.school.findUnique({
      where: { id: schoolId },
      select: { preferredLanguage: true, name: true },
    }),
    import("@/lib/dispatch-notification"),
  ])

  const lang = school?.preferredLanguage ?? "ar"
  const schoolName = school?.name ?? ""

  // Titles + bodies — kept inline (small surface) but stored against the
  // school's preferredLanguage. Runtime translation handles the rest.
  const title =
    lang === "ar" ? `تم تحديد الرسوم الدراسية` : `Tuition fees assigned`
  const body =
    lang === "ar"
      ? `تمت إضافة ${assignmentCount} رسم${assignmentCount === 1 ? "" : "وم"} لطالبك. يمكنك المراجعة والسداد عبر صفحة الرسوم.`
      : `${assignmentCount} fee${assignmentCount === 1 ? "" : "s"} assigned to your student at ${schoolName}. Review and pay from the My Fees page.`

  const recipients = new Set<string>()
  if (student.userId) recipients.add(student.userId)
  for (const sg of student.studentGuardians) {
    if (sg.guardian?.userId) recipients.add(sg.guardian.userId)
  }

  await Promise.all(
    Array.from(recipients).map((userId) =>
      dispatchNotification({
        schoolId,
        userId,
        type: "fee_due",
        title,
        body,
        lang,
        priority: "normal",
        channels: ["in_app", "email", "whatsapp"],
        metadata: { studentId, assignmentCount },
      }).catch((err) =>
        console.warn(
          `[notifyStudentFeesAssigned] Failed for user=${userId}:`,
          err
        )
      )
    )
  )
}
