// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details

import type { Prisma } from "@prisma/client"

import { db } from "@/lib/db"
import { resolveDefaultCurrency } from "@/lib/payment/gateway-config"

// Bump when the default-shape algorithm changes. Stored in sourceSignals so
// drift detection can compare old rows against the latest version.
const PROVISIONING_VERSION = 1

export type FeeProvisioningSignals = {
  country: string | null
  schoolType: string | null
  schoolLevel: string | null
  tuitionFee: number
  currency: string
  gradeId: string | null
  version: number
}

export type FeeProvisioningMode =
  | "new-scope" // only create missing; never touch existing rows (locked or unlocked)
  | "recompute" // create missing + update unlocked; skip locked
  | "reset" // create missing + update ALL (overwrites locked)

export type FeeProvisioningResult = {
  created: number
  updated: number
  lockedSkipped: number
  deactivated: number // orphaned auto-gen rows whose grade no longer exists
  errors: Array<{ gradeId: string | null; error: string }>
  scope: "per-grade" | "school-wide-fallback"
  mode: FeeProvisioningMode
  academicYear: string
  currency: string
  assignedStudents: number
}

async function resolveCurrentAcademicYear(schoolId: string): Promise<string> {
  const current = await db.schoolYear.findFirst({
    where: { schoolId },
    orderBy: { startDate: "desc" },
    select: { yearName: true },
  })
  if (current?.yearName) return current.yearName
  const year = new Date().getFullYear()
  return `${year}-${year + 1}`
}

/**
 * Auto-provision fee structures for a school from current signals.
 *
 * Reads:
 *  - School.tuitionFee   → baseline per-grade tuition (admin-editable at onboarding + school config)
 *  - School.currency     → ISO currency
 *  - School.country/type → stored on the row for traceability
 *
 * Produces:
 *  - One FeeStructure per AcademicGrade that has ≥1 Class (linked via classId)
 *  - Falls back to one school-wide structure when no grade-with-class exists
 *
 * Rules:
 *  - `isAutoGenerated: true` + `isLocked: false`  → updated in place on re-sync
 *  - `isAutoGenerated: true` + `isLocked: true`   → skipped, counted as lockedSkipped
 *  - Admin-created rows (`isAutoGenerated: false`) → never touched
 *
 * Idempotent by (schoolId, academicYear, sourceSignals.gradeId).
 */
export async function provisionSchoolFees(
  schoolId: string,
  options: { mode?: FeeProvisioningMode } = {}
): Promise<FeeProvisioningResult> {
  const mode: FeeProvisioningMode = options.mode ?? "recompute"
  const school = await db.school.findUnique({
    where: { id: schoolId },
    select: {
      id: true,
      country: true,
      currency: true,
      timezone: true,
      schoolType: true,
      schoolLevel: true,
      tuitionFee: true,
    },
  })
  if (!school) throw new Error(`School ${schoolId} not found`)

  const tuitionFee = school.tuitionFee ? Number(school.tuitionFee) : 0
  const currency =
    school.currency ||
    resolveDefaultCurrency(school.country, school.timezone) ||
    "USD"
  const academicYear = await resolveCurrentAcademicYear(schoolId)

  const baseSignals = {
    country: school.country,
    schoolType: school.schoolType,
    schoolLevel: school.schoolLevel,
    tuitionFee,
    currency,
    version: PROVISIONING_VERSION,
  }

  const grades = await db.academicGrade.findMany({
    where: { schoolId },
    select: {
      id: true,
      name: true,
      gradeNumber: true,
      classes: { select: { id: true }, take: 1 },
    },
    orderBy: { gradeNumber: "asc" },
  })

  // Pull every auto-generated row once so upsert doesn't loop on N+1 reads
  const existingAuto = await db.feeStructure.findMany({
    where: { schoolId, academicYear, isAutoGenerated: true },
  })
  const byGradeId = new Map<string, (typeof existingAuto)[number]>()
  let schoolWideExisting: (typeof existingAuto)[number] | undefined
  for (const row of existingAuto) {
    const sig = row.sourceSignals as { gradeId?: string | null } | null
    if (sig?.gradeId) byGradeId.set(sig.gradeId, row)
    else if (row.classId === null) schoolWideExisting = row
  }

  const result: FeeProvisioningResult = {
    created: 0,
    updated: 0,
    lockedSkipped: 0,
    deactivated: 0,
    errors: [],
    scope: "per-grade",
    mode,
    academicYear,
    currency,
    assignedStudents: 0,
  }

  // One FeeStructure per AcademicGrade — independent of whether the grade
  // has Class rows yet. Per-grade rows use sourceSignals.gradeId for student
  // matching (autoAssignFeesForStudent reads this path). classId is linked
  // when the grade already has a class, otherwise left null; admins can edit
  // the linkage later without breaking the per-grade match.
  for (const grade of grades) {
    try {
      const signals: FeeProvisioningSignals = {
        ...baseSignals,
        gradeId: grade.id,
      }
      const name = grade.name
      const payload = buildPayload({
        name,
        academicYear,
        classId: grade.classes[0]?.id ?? null,
        tuitionFee,
        signals,
      })
      const existing = byGradeId.get(grade.id)
      if (existing) {
        if (mode === "new-scope") {
          continue
        }
        if (existing.isLocked && mode !== "reset") {
          result.lockedSkipped++
          continue
        }
        await db.feeStructure.update({
          where: { id: existing.id },
          data: payload,
        })
        result.updated++
      } else {
        await db.feeStructure.create({ data: { schoolId, ...payload } })
        result.created++
      }
    } catch (err) {
      result.errors.push({
        gradeId: grade.id,
        error: err instanceof Error ? err.message : String(err),
      })
    }
  }

  // Legacy school-wide auto-generated row (from the old fallback path):
  // deactivate it so it doesn't double-match every student alongside the
  // new per-grade rows. Admin-created school-wide rows are untouched
  // (isAutoGenerated: false). Only runs on recompute/reset.
  if (mode !== "new-scope" && schoolWideExisting) {
    if (!schoolWideExisting.isLocked || mode === "reset") {
      if (schoolWideExisting.isActive) {
        await db.feeStructure.update({
          where: { id: schoolWideExisting.id },
          data: { isActive: false },
        })
        result.deactivated++
      }
    } else {
      result.lockedSkipped++
    }
  }

  // Orphan sweep: deactivate auto-generated rows whose sourceSignals.gradeId
  // no longer matches any current AcademicGrade (grade was deleted/renamed).
  // Only runs in "recompute" or "reset" mode — "new-scope" is additive only.
  if (mode !== "new-scope") {
    const currentGradeIds = new Set(grades.map((g) => g.id))
    for (const row of existingAuto) {
      const sig = row.sourceSignals as { gradeId?: string | null } | null
      if (!sig?.gradeId) continue // school-wide rows handled above
      if (currentGradeIds.has(sig.gradeId)) continue
      if (row.isLocked && mode !== "reset") continue
      if (!row.isActive) continue
      await db.feeStructure.update({
        where: { id: row.id },
        data: { isActive: false },
      })
      result.deactivated++
    }
  }

  // Fan out: attach new/updated structures to existing enrolled students so
  // `/finance/fees/my` is not empty after a sync. autoAssignFeesForStudent
  // is idempotent (upsert on @@unique[studentId, feeStructureId, academicYear]).
  const students = await db.student.findMany({
    where: { schoolId, academicGradeId: { not: null } },
    select: { id: true, academicGradeId: true },
  })
  const { autoAssignFeesForStudent } = await import("@/lib/fee-auto-assign")
  for (const s of students) {
    if (!s.academicGradeId) continue
    try {
      const r = await autoAssignFeesForStudent(
        schoolId,
        s.id,
        s.academicGradeId
      )
      result.assignedStudents += r.assignedCount
    } catch (err) {
      result.errors.push({
        gradeId: s.academicGradeId,
        error: err instanceof Error ? err.message : String(err),
      })
    }
  }

  return result
}

function buildPayload(input: {
  name: string
  academicYear: string
  classId: string | null
  tuitionFee: number
  signals: FeeProvisioningSignals
}) {
  return {
    name: input.name,
    academicYear: input.academicYear,
    classId: input.classId,
    tuitionFee: input.tuitionFee,
    totalAmount: input.tuitionFee,
    installments: 4,
    isActive: true,
    isAutoGenerated: true,
    sourceSignals: input.signals as unknown as Prisma.InputJsonValue,
    lastSyncedAt: new Date(),
  }
}

export type FeeDriftChange = {
  field: "tuitionFee" | "currency" | "country" | "schoolType" | "schoolLevel"
  stored: string | number | null
  current: string | number | null
}

export type FeeDriftReport = {
  hasDrift: boolean
  staleRowCount: number
  changes: FeeDriftChange[] // deduped across rows
  signalHash: string // stable id for "current" signals — used for dismiss-key
}

/**
 * Compare current School signals against what's stored in sourceSignals of
 * existing auto-generated (unlocked, active) FeeStructure rows.
 *
 * Returns the set of fields that have drifted. Dismiss state is keyed by
 * the current-signals hash so changing the signals again re-shows the banner.
 */
export async function detectFeeProvisioningDrift(
  schoolId: string
): Promise<FeeDriftReport> {
  const school = await db.school.findUnique({
    where: { id: schoolId },
    select: {
      country: true,
      currency: true,
      timezone: true,
      schoolType: true,
      schoolLevel: true,
      tuitionFee: true,
    },
  })
  if (!school) {
    return {
      hasDrift: false,
      staleRowCount: 0,
      changes: [],
      signalHash: "",
    }
  }

  const current = {
    country: school.country,
    schoolType: school.schoolType,
    schoolLevel: school.schoolLevel,
    tuitionFee: school.tuitionFee ? Number(school.tuitionFee) : 0,
    currency:
      school.currency ||
      resolveDefaultCurrency(school.country, school.timezone) ||
      "USD",
  }

  const rows = await db.feeStructure.findMany({
    where: {
      schoolId,
      isAutoGenerated: true,
      isActive: true,
      isLocked: false,
    },
    select: { id: true, sourceSignals: true },
  })

  const changesByField = new Map<FeeDriftChange["field"], FeeDriftChange>()
  let staleRowCount = 0

  for (const row of rows) {
    const sig = row.sourceSignals as FeeProvisioningSignals | null
    if (!sig) continue
    let isStale = false
    const fieldChecks: Array<{
      field: FeeDriftChange["field"]
      stored: string | number | null
      current: string | number | null
    }> = [
      {
        field: "tuitionFee",
        stored: sig.tuitionFee,
        current: current.tuitionFee,
      },
      { field: "currency", stored: sig.currency, current: current.currency },
      { field: "country", stored: sig.country, current: current.country },
      {
        field: "schoolType",
        stored: sig.schoolType,
        current: current.schoolType,
      },
      {
        field: "schoolLevel",
        stored: sig.schoolLevel,
        current: current.schoolLevel,
      },
    ]
    for (const check of fieldChecks) {
      if (check.stored !== check.current) {
        isStale = true
        if (!changesByField.has(check.field)) {
          changesByField.set(check.field, check)
        }
      }
    }
    if (isStale) staleRowCount++
  }

  const signalHash = [
    current.tuitionFee,
    current.currency,
    current.country ?? "",
    current.schoolType ?? "",
    current.schoolLevel ?? "",
  ].join("|")

  return {
    hasDrift: changesByField.size > 0,
    staleRowCount,
    changes: Array.from(changesByField.values()),
    signalHash,
  }
}
