import type { Prisma } from "@prisma/client"

import { db } from "@/lib/db"

type DbClient = typeof db | Prisma.TransactionClient

/**
 * Founder contract — every student-create / grade-update path that knows the
 * student's grade MUST end with `ensureStudentFeeAssignments`. The guarantee:
 *
 * 1. Synchronous + awaited (callers `await` the result; no fire-and-forget).
 * 2. Idempotent — re-running for the same `(student, structure, year)` tuple
 *    is a no-op via `@@unique([studentId, feeStructureId, academicYear])`.
 * 3. Never overwrites admin-set fields. Existing `discounts` / `scholarshipId`
 *    / `totalDiscount` / `customAmount` / `finalAmount` are left alone — only
 *    NEW assignments are inserted.
 * 4. Best-effort invoice sync + `fee_due` notification fire after the
 *    transaction commits; failures here log but never roll back the
 *    assignments themselves.
 *
 * Optional `tx` — when a caller is already inside a `db.$transaction` (e.g.
 * admission `confirmEnrollment`), it passes its transaction client so the
 * fee-assignment + invoice fan-out join that atomic unit. In tx-mode the
 * `fee_due` notification is SUPPRESSED (the caller owns post-commit
 * notifications) and invoice sync runs inside the same tx. This is the single
 * source of truth for student→structure matching — no caller should duplicate
 * the matching rules inline.
 */
export interface EnsureFeeAssignmentsInput {
  schoolId: string
  studentId: string
  /** When null, the helper short-circuits to `skipped: 1` — caller is
   *  expected to re-invoke once a grade is set. */
  academicGradeId: string | null
  /** Defaults to the school's current `SchoolYear.yearName`, or the calendar
   *  year-pair fallback. */
  academicYear?: string
  /** When false, suppress the `fee_due` notification — useful for bulk
   *  imports where notifications are dispatched separately. */
  notify?: boolean
}

export interface EnsureFeeAssignmentsResult {
  created: number
  existing: number
  /** 1 when the call short-circuited because no grade was supplied. */
  skipped: number
  /** Combined IDs of newly-created + pre-existing assignments. Useful for
   *  invoice fan-out by the caller. */
  assignmentIds: string[]
}

export async function ensureStudentFeeAssignments(
  input: EnsureFeeAssignmentsInput,
  tx?: Prisma.TransactionClient
): Promise<EnsureFeeAssignmentsResult> {
  const { schoolId, studentId, academicGradeId, notify = true } = input
  // In tx-mode all reads/writes use the caller's transaction client so the
  // fee-assignment + invoice fan-out are atomic with the caller's work.
  const client: DbClient = tx ?? db

  // No grade yet → nothing to assign. Caller (wizard, future grade-edit) is
  // expected to re-invoke once `Student.academicGradeId` is set.
  if (!academicGradeId) {
    return { created: 0, existing: 0, skipped: 1, assignmentIds: [] }
  }

  const academicYear =
    input.academicYear ?? (await resolveCurrentAcademicYear(schoolId, client))

  // Grade-specific structures attach via Class, so we resolve those classes
  // first.
  const gradeClasses = await client.class.findMany({
    where: { schoolId, gradeId: academicGradeId },
    select: { id: true },
  })
  const gradeClassIds = gradeClasses.map((c) => c.id)

  // Three sources of structures match a student-grade pair:
  // 1. Admin-created school-wide (no class link, not auto-generated)
  // 2. Class-linked structures whose classId belongs to this grade
  // 3. Auto-generated per-grade structures (sourceSignals.gradeId match) —
  //    these may include pricing-matrix VARIANTS (per stream / student-type).
  const matchedStructures = await client.feeStructure.findMany({
    where: {
      schoolId,
      academicYear,
      isActive: true,
      OR: [
        { classId: null, isAutoGenerated: false },
        ...(gradeClassIds.length > 0
          ? [{ classId: { in: gradeClassIds } }]
          : []),
        {
          isAutoGenerated: true,
          sourceSignals: {
            path: ["gradeId"],
            equals: academicGradeId,
          },
        },
      ],
    },
    select: {
      id: true,
      totalAmount: true,
      isAutoGenerated: true,
      sourceSignals: true,
    },
  })

  if (matchedStructures.length === 0) {
    return { created: 0, existing: 0, skipped: 0, assignmentIds: [] }
  }

  // Auto-generated structures carrying this grade's sourceSignals.gradeId form
  // a MUTUALLY-EXCLUSIVE variant group (base + per-stream / per-type prices of
  // the same grade fee): the student gets the single most-specific variant
  // COMPATIBLE with their stream + studentType. Everything else (admin
  // school-wide, class-linked, legacy rows with no sourceSignals) is additive.
  // With ≤1 variant this is a no-op, preserving legacy "assign all" behaviour.
  const feeStructures = await selectAssignableStructures(
    client,
    { schoolId, studentId, academicGradeId },
    matchedStructures
  )

  if (feeStructures.length === 0) {
    return { created: 0, existing: 0, skipped: 0, assignmentIds: [] }
  }

  // Diff existing vs needed so we know exactly how many were *newly* created.
  // Counting via upsert would conflate new+existing and break the founder
  // contract's notification rule (only notify on new).
  const structureIds = feeStructures.map((s) => s.id)
  const existing = await client.feeAssignment.findMany({
    where: { studentId, academicYear, feeStructureId: { in: structureIds } },
    select: { id: true, feeStructureId: true },
  })
  const existingStructureIds = new Set(existing.map((a) => a.feeStructureId))
  const missing = feeStructures.filter((s) => !existingStructureIds.has(s.id))

  if (missing.length === 0) {
    return {
      created: 0,
      existing: existing.length,
      skipped: 0,
      assignmentIds: existing.map((a) => a.id),
    }
  }

  // Create the missing assignments. A partial failure must not leave
  // half-created rows: when we own the transaction we wrap in
  // `db.$transaction`; when the caller passed a `tx`, the create loop joins
  // their atomic unit directly (no nested transaction — Prisma forbids it).
  const created = tx
    ? await createMissingAssignments(
        tx,
        { schoolId, studentId, academicYear },
        missing
      )
    : await db.$transaction((innerTx) =>
        createMissingAssignments(
          innerTx,
          { schoolId, studentId, academicYear },
          missing
        )
      )

  const allAssignmentIds = [
    ...existing.map((a) => a.id),
    ...created.map((c) => c.id),
  ]

  // Invoice fan-out. In tx-mode it runs inside the caller's transaction
  // (atomic); standalone it is best-effort after commit so a transient
  // failure never rolls back the assignments themselves. Either way invoice
  // errors are caught and logged, never propagated.
  if (created.length > 0) {
    try {
      const { ensureInvoicesForAssignment } =
        await import("@/lib/fee-invoice-sync")
      for (const c of created) {
        try {
          await ensureInvoicesForAssignment(schoolId, c.id, tx)
        } catch (err) {
          console.warn(
            `[ensureStudentFeeAssignments] Invoice sync failed for assignment=${c.id}:`,
            err
          )
        }
      }
    } catch (err) {
      console.warn(
        "[ensureStudentFeeAssignments] Invoice sync batch failed:",
        err
      )
    }
  }

  // In tx-mode the caller owns post-commit notifications (dispatching mid-tx
  // would write notification rows that vanish on rollback), so suppress here.
  if (!tx && notify && created.length > 0) {
    try {
      await notifyStudentFeesAssigned(schoolId, studentId, created.length)
    } catch (err) {
      console.warn("[ensureStudentFeeAssignments] Notification failed:", err)
    }
  }

  if (created.length > 0) {
    console.log(
      `[ensureStudentFeeAssignments] Created ${created.length} new fee assignment(s) for student ${studentId} (${existing.length} pre-existing)`
    )
  }

  return {
    created: created.length,
    existing: existing.length,
    skipped: 0,
    assignmentIds: allAssignmentIds,
  }
}

type MatchedStructure = {
  id: string
  totalAmount: Prisma.Decimal | number
  isAutoGenerated: boolean
  sourceSignals: unknown
}

/**
 * Collapse the pricing-matrix variant group to the single most-specific variant
 * compatible with the student, while keeping all additive (non-variant)
 * structures. Backward-compatible: 0–1 variants → returns everything unchanged.
 */
async function selectAssignableStructures(
  client: DbClient,
  ctx: { schoolId: string; studentId: string; academicGradeId: string },
  matched: MatchedStructure[]
): Promise<Array<{ id: string; totalAmount: Prisma.Decimal | number }>> {
  const variantGroup: MatchedStructure[] = []
  const additive: MatchedStructure[] = []
  for (const s of matched) {
    const sig = s.sourceSignals as { gradeId?: string | null } | null
    if (s.isAutoGenerated && sig?.gradeId === ctx.academicGradeId) {
      variantGroup.push(s)
    } else {
      additive.push(s)
    }
  }

  // 0 or 1 variant → no dimension resolution needed (legacy fast path).
  if (variantGroup.length <= 1) {
    return [...additive, ...variantGroup]
  }

  // Resolve the student's dimensions to choose the most-specific compatible
  // variant. A pinned dimension on the structure must equal the student's value.
  const student = await client.student.findFirst({
    where: { id: ctx.studentId, schoolId: ctx.schoolId },
    select: { academicStreamId: true, studentType: true },
  })
  const studentStream = student?.academicStreamId ?? null
  const studentType = (student?.studentType as string | null) ?? null

  let chosen: MatchedStructure | null = null
  let chosenScore = -1
  for (const s of variantGroup) {
    const sig = s.sourceSignals as {
      streamId?: string | null
      studentType?: string | null
    } | null
    const sStream = sig?.streamId ?? null
    const sType = sig?.studentType ?? null
    if (sStream !== null && sStream !== studentStream) continue
    if (sType !== null && sType !== studentType) continue
    const score = (sStream ? 1 : 0) + (sType ? 1 : 0)
    if (score > chosenScore) {
      chosen = s
      chosenScore = score
    }
  }

  return chosen ? [...additive, chosen] : additive
}

/**
 * Insert the missing FeeAssignment rows on the given client (a transaction
 * client). P2002 (unique-constraint race) is treated as pre-existing and
 * skipped; any other error propagates to roll the transaction back.
 */
async function createMissingAssignments(
  client: Prisma.TransactionClient,
  ctx: { schoolId: string; studentId: string; academicYear: string },
  missing: Array<{ id: string; totalAmount: Prisma.Decimal | number }>
): Promise<{ id: string }[]> {
  const createdRows: { id: string }[] = []
  for (const structure of missing) {
    try {
      const row = await client.feeAssignment.create({
        data: {
          schoolId: ctx.schoolId,
          studentId: ctx.studentId,
          feeStructureId: structure.id,
          academicYear: ctx.academicYear,
          finalAmount: Number(structure.totalAmount),
          totalDiscount: 0,
          status: "PENDING",
        },
        select: { id: true },
      })
      createdRows.push(row)
    } catch (err: unknown) {
      if (
        err &&
        typeof err === "object" &&
        "code" in err &&
        (err as { code?: string }).code === "P2002"
      ) {
        continue
      }
      throw err
    }
  }
  return createdRows
}

/**
 * @deprecated Prefer `ensureStudentFeeAssignments`. Thin wrapper kept so the
 * rewiring sweep can be done one caller at a time without breakage.
 */
export async function autoAssignFeesForStudent(
  schoolId: string,
  studentId: string,
  academicGradeId: string
): Promise<{ assignedCount: number }> {
  const result = await ensureStudentFeeAssignments({
    schoolId,
    studentId,
    academicGradeId,
  })
  // Old contract counted EVERY matching structure; preserve that for callers
  // still on the deprecated entrypoint.
  return { assignedCount: result.created + result.existing }
}

async function resolveCurrentAcademicYear(
  schoolId: string,
  client: DbClient = db
): Promise<string> {
  const currentYear = await client.schoolYear.findFirst({
    where: { schoolId },
    orderBy: { startDate: "desc" },
    select: { yearName: true },
  })
  return (
    currentYear?.yearName ??
    `${new Date().getFullYear()}-${new Date().getFullYear() + 1}`
  )
}

async function notifyStudentFeesAssigned(
  schoolId: string,
  studentId: string,
  assignmentCount: number
): Promise<void> {
  const student = await db.student.findFirst({
    where: { id: studentId, schoolId },
    select: {
      firstName: true,
      userId: true,
      studentGuardians: {
        select: {
          guardian: {
            select: { userId: true },
          },
        },
      },
    },
  })
  if (!student) return

  const [school, { dispatchNotification }] = await Promise.all([
    db.school.findUnique({
      where: { id: schoolId },
      select: { preferredLanguage: true, name: true },
    }),
    import("@/lib/dispatch-notification"),
  ])

  const lang = school?.preferredLanguage ?? "ar"
  const schoolName = school?.name ?? ""

  // Titles + bodies — kept inline (small surface) but stored against the
  // school's preferredLanguage. Runtime translation handles the rest.
  const title =
    lang === "ar" ? `تم تحديد الرسوم الدراسية` : `Tuition fees assigned`
  const body =
    lang === "ar"
      ? `تمت إضافة ${assignmentCount} رسم${assignmentCount === 1 ? "" : "وم"} لطالبك. يمكنك المراجعة والسداد عبر صفحة الرسوم.`
      : `${assignmentCount} fee${assignmentCount === 1 ? "" : "s"} assigned to your student at ${schoolName}. Review and pay from the My Fees page.`

  const recipients = new Set<string>()
  if (student.userId) recipients.add(student.userId)
  for (const sg of student.studentGuardians) {
    if (sg.guardian?.userId) recipients.add(sg.guardian.userId)
  }

  await Promise.all(
    Array.from(recipients).map((userId) =>
      dispatchNotification({
        schoolId,
        userId,
        type: "fee_due",
        title,
        body,
        lang,
        priority: "normal",
        channels: ["in_app", "email", "whatsapp"],
        metadata: { studentId, assignmentCount },
      }).catch((err) =>
        console.warn(
          `[notifyStudentFeesAssigned] Failed for user=${userId}:`,
          err
        )
      )
    )
  )
}
