// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details

import type { Prisma } from "@prisma/client"

import { db } from "@/lib/db"
import { resolveDefaultCurrency } from "@/lib/payment/gateway-config"

// Bump when the default-shape algorithm changes. Stored in sourceSignals so
// drift detection can compare old rows against the latest version.
const PROVISIONING_VERSION = 1

export type FeeProvisioningSignals = {
  country: string | null
  schoolType: string | null
  schoolLevel: string | null
  tuitionFee: number
  currency: string
  gradeId: string | null
  // Pricing-matrix dimensions. null = the grade-wide base variant (legacy
  // behaviour). Non-null = a specific stream / student-type variant materialised
  // from a PricingRule. Read by `ensureStudentFeeAssignments` for most-specific
  // matching against a student's stream + type.
  streamId?: string | null
  studentType?: string | null
  version: number
}

// Fee components shared by FeeStructure + PricingRule.
type FeeComponents = {
  tuitionFee: number
  admissionFee?: number | null
  registrationFee?: number | null
  examFee?: number | null
  libraryFee?: number | null
  laboratoryFee?: number | null
  sportsFee?: number | null
  transportFee?: number | null
  hostelFee?: number | null
  otherFees?: unknown
  installments: number
}

const COMPONENT_FIELDS = [
  "tuitionFee",
  "admissionFee",
  "registrationFee",
  "examFee",
  "libraryFee",
  "laboratoryFee",
  "sportsFee",
  "transportFee",
  "hostelFee",
] as const

/** Sum all numeric fee components into the headline total. */
function sumComponents(c: FeeComponents): number {
  let total = 0
  for (const f of COMPONENT_FIELDS) {
    const v = c[f]
    if (typeof v === "number" && Number.isFinite(v)) total += v
  }
  // otherFees: array of {name, amount}
  if (Array.isArray(c.otherFees)) {
    for (const o of c.otherFees as Array<{ amount?: unknown }>) {
      const a = Number(o?.amount)
      if (Number.isFinite(a)) total += a
    }
  }
  return Math.round(total * 100) / 100
}

export type FeeProvisioningMode =
  | "new-scope" // only create missing; never touch existing rows (locked or unlocked)
  | "recompute" // create missing + update unlocked; skip locked
  | "reset" // create missing + update ALL (overwrites locked)

export type FeeProvisioningResult = {
  created: number
  updated: number
  lockedSkipped: number
  deactivated: number // orphaned auto-gen rows whose grade no longer exists
  errors: Array<{ gradeId: string | null; error: string }>
  scope: "per-grade" | "school-wide-fallback"
  mode: FeeProvisioningMode
  academicYear: string
  currency: string
  assignedStudents: number
}

async function resolveCurrentAcademicYear(schoolId: string): Promise<string> {
  const current = await db.schoolYear.findFirst({
    where: { schoolId },
    orderBy: { startDate: "desc" },
    select: { yearName: true },
  })
  if (current?.yearName) return current.yearName
  const year = new Date().getFullYear()
  return `${year}-${year + 1}`
}

/**
 * Auto-provision fee structures for a school from current signals.
 *
 * Reads:
 *  - School.tuitionFee   → baseline per-grade tuition (admin-editable at onboarding + school config)
 *  - School.currency     → ISO currency
 *  - School.country/type → stored on the row for traceability
 *
 * Produces:
 *  - One FeeStructure per AcademicGrade that has ≥1 Class (linked via classId)
 *  - Falls back to one school-wide structure when no grade-with-class exists
 *
 * Rules:
 *  - `isAutoGenerated: true` + `isLocked: false`  → updated in place on re-sync
 *  - `isAutoGenerated: true` + `isLocked: true`   → skipped, counted as lockedSkipped
 *  - Admin-created rows (`isAutoGenerated: false`) → never touched
 *
 * Idempotent by (schoolId, academicYear, sourceSignals.gradeId).
 */
export async function provisionSchoolFees(
  schoolId: string,
  options: { mode?: FeeProvisioningMode } = {}
): Promise<FeeProvisioningResult> {
  const mode: FeeProvisioningMode = options.mode ?? "recompute"
  const school = await db.school.findUnique({
    where: { id: schoolId },
    select: {
      id: true,
      country: true,
      currency: true,
      timezone: true,
      schoolType: true,
      schoolLevel: true,
      tuitionFee: true,
    },
  })
  if (!school) throw new Error(`School ${schoolId} not found`)

  const tuitionFee = school.tuitionFee ? Number(school.tuitionFee) : 0
  const currency =
    school.currency ||
    resolveDefaultCurrency(school.country, school.timezone) ||
    "USD"
  const academicYear = await resolveCurrentAcademicYear(schoolId)

  const baseSignals = {
    country: school.country,
    schoolType: school.schoolType,
    schoolLevel: school.schoolLevel,
    tuitionFee,
    currency,
    version: PROVISIONING_VERSION,
  }

  const grades = await db.academicGrade.findMany({
    where: { schoolId },
    select: {
      id: true,
      name: true,
      gradeNumber: true,
      classes: { select: { id: true }, take: 1 },
    },
    orderBy: { gradeNumber: "asc" },
  })

  // Admin pricing matrix (sparse). Empty → legacy per-grade tuition baseline,
  // i.e. exactly one base variant per grade priced at School.tuitionFee.
  const pricingRules = (await db.pricingRule.findMany({
    where: { schoolId, academicYear, isActive: true },
    select: {
      gradeId: true,
      academicStreamId: true,
      studentType: true,
      tuitionFee: true,
      admissionFee: true,
      registrationFee: true,
      examFee: true,
      libraryFee: true,
      laboratoryFee: true,
      sportsFee: true,
      transportFee: true,
      hostelFee: true,
      otherFees: true,
      installments: true,
    },
  })) as unknown as LoadedPricingRule[]

  // Stream id→name map for readable variant labels (one query, not per-grade).
  const streamRows = await db.academicStream.findMany({
    where: { schoolId },
    select: { id: true, name: true },
  })
  const streamNameById = new Map(streamRows.map((s) => [s.id, s.name]))

  // Pull every auto-generated row once so upsert doesn't loop on N+1 reads.
  // Index by the composite (grade, stream, studentType) variant key.
  const existingAuto = await db.feeStructure.findMany({
    where: { schoolId, academicYear, isAutoGenerated: true },
  })
  const byVariant = new Map<string, (typeof existingAuto)[number]>()
  let schoolWideExisting: (typeof existingAuto)[number] | undefined
  for (const row of existingAuto) {
    const sig = row.sourceSignals as {
      gradeId?: string | null
      streamId?: string | null
      studentType?: string | null
    } | null
    if (sig?.gradeId) {
      byVariant.set(
        variantKey(sig.gradeId, sig.streamId ?? null, sig.studentType ?? null),
        row
      )
    } else if (row.classId === null) schoolWideExisting = row
  }

  const result: FeeProvisioningResult = {
    created: 0,
    updated: 0,
    lockedSkipped: 0,
    deactivated: 0,
    errors: [],
    scope: "per-grade",
    mode,
    academicYear,
    currency,
    assignedStudents: 0,
  }

  // One FeeStructure per AcademicGrade × pricing-matrix variant. With no
  // PricingRule rows each grade yields exactly one base variant (stream=null,
  // type=null) priced at School.tuitionFee — identical to the legacy behaviour.
  // Per-grade rows use sourceSignals.{gradeId,streamId,studentType} for student
  // matching. classId is linked when the grade already has a class, otherwise
  // left null; admins can edit the linkage later without breaking the match.
  const materializedKeys = new Set<string>()
  for (const grade of grades) {
    const combos = variantsForGrade(pricingRules, grade.id)
    for (const combo of combos) {
      const key = variantKey(grade.id, combo.streamId, combo.studentType)
      materializedKeys.add(key)
      try {
        const rule = resolvePricingRule(
          pricingRules,
          grade.id,
          combo.streamId,
          combo.studentType
        )
        const components = ruleToComponents(rule, tuitionFee)
        const signals: FeeProvisioningSignals = {
          ...baseSignals,
          gradeId: grade.id,
          streamId: combo.streamId,
          studentType: combo.studentType,
        }
        const labelParts = [grade.name]
        if (combo.streamId)
          labelParts.push(streamNameById.get(combo.streamId) ?? combo.streamId)
        if (combo.studentType) labelParts.push(combo.studentType)
        const payload = buildPayload({
          name: labelParts.join(" — "),
          academicYear,
          classId: grade.classes[0]?.id ?? null,
          components,
          signals,
        })
        const existing = byVariant.get(key)
        if (existing) {
          if (mode === "new-scope") {
            continue
          }
          if (existing.isLocked && mode !== "reset") {
            result.lockedSkipped++
            continue
          }
          await db.feeStructure.update({
            where: { id: existing.id },
            data: payload,
          })
          result.updated++
        } else {
          await db.feeStructure.create({ data: { schoolId, ...payload } })
          result.created++
        }
      } catch (err) {
        result.errors.push({
          gradeId: grade.id,
          error: err instanceof Error ? err.message : String(err),
        })
      }
    }
  }

  // Legacy school-wide auto-generated row (from the old fallback path):
  // deactivate it so it doesn't double-match every student alongside the
  // new per-grade rows. Admin-created school-wide rows are untouched
  // (isAutoGenerated: false). Only runs on recompute/reset.
  if (mode !== "new-scope" && schoolWideExisting) {
    if (!schoolWideExisting.isLocked || mode === "reset") {
      if (schoolWideExisting.isActive) {
        await db.feeStructure.update({
          where: { id: schoolWideExisting.id },
          data: { isActive: false },
        })
        result.deactivated++
      }
    } else {
      result.lockedSkipped++
    }
  }

  // Orphan sweep: deactivate auto-generated rows whose variant was NOT
  // re-materialised this run — covers deleted/renamed grades AND removed
  // pricing-matrix variants (e.g. admin deleted a stream/type PricingRule).
  // Only runs in "recompute" or "reset" mode — "new-scope" is additive only.
  if (mode !== "new-scope") {
    for (const row of existingAuto) {
      const sig = row.sourceSignals as {
        gradeId?: string | null
        streamId?: string | null
        studentType?: string | null
      } | null
      if (!sig?.gradeId) continue // school-wide rows handled above
      const key = variantKey(
        sig.gradeId,
        sig.streamId ?? null,
        sig.studentType ?? null
      )
      if (materializedKeys.has(key)) continue
      if (row.isLocked && mode !== "reset") continue
      if (!row.isActive) continue
      await db.feeStructure.update({
        where: { id: row.id },
        data: { isActive: false },
      })
      result.deactivated++
    }
  }

  // Fan out: attach new/updated structures to existing enrolled students so
  // `/finance/fees/my` is not empty after a sync. ensureStudentFeeAssignments
  // is idempotent (unique constraint on [studentId, feeStructureId, academicYear]).
  // notify=false on bulk sync — admin already pressed the Sync button and
  // doesn't need a notification storm in response.
  const students = await db.student.findMany({
    where: { schoolId, academicGradeId: { not: null } },
    select: { id: true, academicGradeId: true },
  })
  const { ensureStudentFeeAssignments } = await import("@/lib/fee-auto-assign")
  for (const s of students) {
    if (!s.academicGradeId) continue
    try {
      const r = await ensureStudentFeeAssignments({
        schoolId,
        studentId: s.id,
        academicGradeId: s.academicGradeId,
        notify: false,
      })
      // Preserve old result shape: count both newly-created and pre-existing
      // matches so the admin sees the full fan-out span.
      result.assignedStudents += r.created + r.existing
    } catch (err) {
      result.errors.push({
        gradeId: s.academicGradeId,
        error: err instanceof Error ? err.message : String(err),
      })
    }
  }

  return result
}

// Build 4 quarterly installment due dates from an academic year string
// ("2025/2026" or "2025-2026"). The cron at /api/cron/fee-overdue reads this
// paymentSchedule JSON to flip PENDING → OVERDUE. Without it, auto-generated
// fees never become overdue and never trigger reminders.
export function buildQuarterlySchedule(
  academicYear: string,
  totalAmount: number
): Array<{ dueDate: string; amount: number; description: string }> {
  // Extract start year — "2025/2026" or "2025-2026" → 2025
  const match = academicYear.match(/^(\d{4})/)
  const startYear = match ? parseInt(match[1], 10) : new Date().getFullYear()
  // Academic year conventionally starts September 1
  const start = new Date(Date.UTC(startYear, 8, 1)) // Sep = month 8
  const quarterAmount = Math.round((totalAmount / 4) * 100) / 100
  const remainder = Math.round((totalAmount - quarterAmount * 3) * 100) / 100

  return [0, 1, 2, 3].map((q) => {
    const d = new Date(start)
    // Months 0,3,6,9 after Sep 1 → Sep, Dec, Mar, Jun
    d.setUTCMonth(d.getUTCMonth() + q * 3)
    return {
      dueDate: d.toISOString(),
      amount: q === 3 ? remainder : quarterAmount, // Q4 absorbs rounding
      description: `Q${q + 1} ${academicYear}`,
    }
  })
}

function buildPayload(input: {
  name: string
  academicYear: string
  classId: string | null
  components: FeeComponents
  signals: FeeProvisioningSignals
}) {
  const { components } = input
  // totalAmount is DERIVED from the sum of all components — single source of
  // truth (fixes the legacy undercharge where totalAmount == tuitionFee only).
  const totalAmount = sumComponents(components)
  const installments = components.installments > 0 ? components.installments : 1
  return {
    name: input.name,
    academicYear: input.academicYear,
    classId: input.classId,
    tuitionFee: components.tuitionFee,
    admissionFee: components.admissionFee ?? null,
    registrationFee: components.registrationFee ?? null,
    examFee: components.examFee ?? null,
    libraryFee: components.libraryFee ?? null,
    laboratoryFee: components.laboratoryFee ?? null,
    sportsFee: components.sportsFee ?? null,
    transportFee: components.transportFee ?? null,
    hostelFee: components.hostelFee ?? null,
    otherFees: (components.otherFees ?? undefined) as Prisma.InputJsonValue,
    totalAmount,
    installments,
    paymentSchedule: buildQuarterlySchedule(
      input.academicYear,
      totalAmount
    ) as unknown as Prisma.InputJsonValue,
    isActive: true,
    isAutoGenerated: true,
    sourceSignals: input.signals as unknown as Prisma.InputJsonValue,
    lastSyncedAt: new Date(),
  }
}

// ---------------------------------------------------------------------------
// Pricing-matrix resolution
// ---------------------------------------------------------------------------

type LoadedPricingRule = {
  gradeId: string | null
  academicStreamId: string | null
  studentType: string | null
} & FeeComponents

/** Composite key uniquely identifying an auto-generated variant. */
function variantKey(
  gradeId: string,
  streamId: string | null,
  studentType: string | null
): string {
  return `${gradeId}|${streamId ?? ""}|${studentType ?? ""}`
}

/** Count of pinned (non-null) dimension selectors — higher wins ties. */
function ruleSpecificity(r: LoadedPricingRule): number {
  return (
    (r.gradeId ? 1 : 0) +
    (r.academicStreamId ? 1 : 0) +
    (r.studentType ? 1 : 0)
  )
}

/** Does a (sparse) rule apply to a concrete (grade, stream, type) target? */
function ruleApplies(
  r: LoadedPricingRule,
  gradeId: string,
  streamId: string | null,
  studentType: string | null
): boolean {
  return (
    (r.gradeId === null || r.gradeId === gradeId) &&
    (r.academicStreamId === null || r.academicStreamId === streamId) &&
    (r.studentType === null || r.studentType === studentType)
  )
}

/** Most-specific applicable rule for a target combo, or null. */
function resolvePricingRule(
  rules: LoadedPricingRule[],
  gradeId: string,
  streamId: string | null,
  studentType: string | null
): LoadedPricingRule | null {
  let best: LoadedPricingRule | null = null
  let bestScore = -1
  for (const r of rules) {
    if (!ruleApplies(r, gradeId, streamId, studentType)) continue
    const score = ruleSpecificity(r)
    if (score > bestScore) {
      best = r
      bestScore = score
    }
  }
  return best
}

/**
 * The distinct (stream, studentType) variant combos to materialise for a grade:
 * always the grade-wide base (null, null), plus every dimension-pinned combo
 * that appears in a rule applicable to this grade. Sparse — no cartesian blow-up.
 */
function variantsForGrade(
  rules: LoadedPricingRule[],
  gradeId: string
): Array<{ streamId: string | null; studentType: string | null }> {
  const combos = new Map<
    string,
    { streamId: string | null; studentType: string | null }
  >()
  combos.set("|", { streamId: null, studentType: null }) // base always exists
  for (const r of rules) {
    if (r.gradeId !== null && r.gradeId !== gradeId) continue // not applicable
    if (r.academicStreamId === null && r.studentType === null) continue // base
    combos.set(`${r.academicStreamId ?? ""}|${r.studentType ?? ""}`, {
      streamId: r.academicStreamId,
      studentType: r.studentType,
    })
  }
  return Array.from(combos.values())
}

function ruleToComponents(
  rule: LoadedPricingRule | null,
  fallbackTuition: number
): FeeComponents {
  if (!rule) {
    // No admin rule → legacy baseline: tuition only, 4 installments.
    return { tuitionFee: fallbackTuition, installments: 4 }
  }
  return {
    tuitionFee: Number(rule.tuitionFee),
    admissionFee: rule.admissionFee != null ? Number(rule.admissionFee) : null,
    registrationFee:
      rule.registrationFee != null ? Number(rule.registrationFee) : null,
    examFee: rule.examFee != null ? Number(rule.examFee) : null,
    libraryFee: rule.libraryFee != null ? Number(rule.libraryFee) : null,
    laboratoryFee:
      rule.laboratoryFee != null ? Number(rule.laboratoryFee) : null,
    sportsFee: rule.sportsFee != null ? Number(rule.sportsFee) : null,
    transportFee: rule.transportFee != null ? Number(rule.transportFee) : null,
    hostelFee: rule.hostelFee != null ? Number(rule.hostelFee) : null,
    otherFees: rule.otherFees ?? undefined,
    installments: rule.installments > 0 ? rule.installments : 4,
  }
}

export type FeeDriftChange = {
  field: "tuitionFee" | "currency" | "country" | "schoolType" | "schoolLevel"
  stored: string | number | null
  current: string | number | null
}

export type FeeDriftReport = {
  hasDrift: boolean
  staleRowCount: number
  changes: FeeDriftChange[] // deduped across rows
  signalHash: string // stable id for "current" signals — used for dismiss-key
}

/**
 * Compare current School signals against what's stored in sourceSignals of
 * existing auto-generated (unlocked, active) FeeStructure rows.
 *
 * Returns the set of fields that have drifted. Dismiss state is keyed by
 * the current-signals hash so changing the signals again re-shows the banner.
 */
export async function detectFeeProvisioningDrift(
  schoolId: string
): Promise<FeeDriftReport> {
  const school = await db.school.findUnique({
    where: { id: schoolId },
    select: {
      country: true,
      currency: true,
      timezone: true,
      schoolType: true,
      schoolLevel: true,
      tuitionFee: true,
    },
  })
  if (!school) {
    return {
      hasDrift: false,
      staleRowCount: 0,
      changes: [],
      signalHash: "",
    }
  }

  const current = {
    country: school.country,
    schoolType: school.schoolType,
    schoolLevel: school.schoolLevel,
    tuitionFee: school.tuitionFee ? Number(school.tuitionFee) : 0,
    currency:
      school.currency ||
      resolveDefaultCurrency(school.country, school.timezone) ||
      "USD",
  }

  const rows = await db.feeStructure.findMany({
    where: {
      schoolId,
      isAutoGenerated: true,
      isActive: true,
      isLocked: false,
    },
    select: { id: true, sourceSignals: true },
  })

  const changesByField = new Map<FeeDriftChange["field"], FeeDriftChange>()
  let staleRowCount = 0

  for (const row of rows) {
    const sig = row.sourceSignals as FeeProvisioningSignals | null
    if (!sig) continue
    let isStale = false
    const fieldChecks: Array<{
      field: FeeDriftChange["field"]
      stored: string | number | null
      current: string | number | null
    }> = [
      {
        field: "tuitionFee",
        stored: sig.tuitionFee,
        current: current.tuitionFee,
      },
      { field: "currency", stored: sig.currency, current: current.currency },
      { field: "country", stored: sig.country, current: current.country },
      {
        field: "schoolType",
        stored: sig.schoolType,
        current: current.schoolType,
      },
      {
        field: "schoolLevel",
        stored: sig.schoolLevel,
        current: current.schoolLevel,
      },
    ]
    for (const check of fieldChecks) {
      if (check.stored !== check.current) {
        isStale = true
        if (!changesByField.has(check.field)) {
          changesByField.set(check.field, check)
        }
      }
    }
    if (isStale) staleRowCount++
  }

  const signalHash = [
    current.tuitionFee,
    current.currency,
    current.country ?? "",
    current.schoolType ?? "",
    current.schoolLevel ?? "",
  ].join("|")

  return {
    hasDrift: changesByField.size > 0,
    staleRowCount,
    changes: Array.from(changesByField.values()),
    signalHash,
  }
}
