// Name parsing and composition utilities for configurable name input variants.
// Schools can use "split" (first + last fields) or "full" (single field) name input.
// Prisma storage always uses firstName/middleName/lastName — only the UI changes.

export type NameFormat = "split" | "full"

/**
 * Parse a full name string into first/middle/last parts.
 * First word → firstName, last word → lastName, everything in between → middleName.
 */
export function parseFullName(fullName: string): {
  firstName: string
  middleName: string | undefined
  lastName: string
} {
  const parts = fullName.trim().split(/\s+/)
  if (parts.length === 0 || (parts.length === 1 && parts[0] === ""))
    return { firstName: "", middleName: undefined, lastName: "" }
  if (parts.length === 1)
    return { firstName: parts[0], middleName: undefined, lastName: "" }
  if (parts.length === 2)
    return { firstName: parts[0], middleName: undefined, lastName: parts[1] }
  return {
    firstName: parts[0],
    middleName: parts.slice(1, -1).join(" "),
    lastName: parts[parts.length - 1],
  }
}

/**
 * Detect gender from an Arabic (or transliterated) first name.
 * Returns "MALE", "FEMALE", or null if uncertain.
 *
 * Uses a lookup table of common Arabic names (Sudanese/Saudi/Gulf focus)
 * plus morphological heuristics for Arabic script names.
 */
export function detectGenderFromName(
  firstName: string | undefined | null
): "MALE" | "FEMALE" | null {
  if (!firstName) return null
  const name = firstName.trim().toLowerCase()
  if (!name) return null

  // Normalize Arabic: strip diacritics (tashkeel)
  const arabic = firstName
    .trim()
    .replace(/[\u064B-\u065F\u0670]/g, "")
    .replace(/\s+/g, "")

  // --- Lookup tables ---
  const maleArabic = new Set([
    "محمد",
    "أحمد",
    "احمد",
    "عبدالله",
    "عبد الله",
    "عبدالرحمن",
    "عبد الرحمن",
    "عبدالعزيز",
    "عبد العزيز",
    "عبدالملك",
    "عبدالكريم",
    "عبدالرحيم",
    "عبدالحميد",
    "عبدالقادر",
    "عبدالباسط",
    "عبداللطيف",
    "عمر",
    "علي",
    "خالد",
    "إبراهيم",
    "ابراهيم",
    "يوسف",
    "حسن",
    "حسين",
    "عثمان",
    "صالح",
    "سعيد",
    "ياسر",
    "طارق",
    "فهد",
    "سلطان",
    "بدر",
    "نايف",
    "تركي",
    "فيصل",
    "سلمان",
    "ماجد",
    "سعد",
    "راشد",
    "حمد",
    "مشعل",
    "وليد",
    "ناصر",
    "بندر",
    "عادل",
    "كمال",
    "جمال",
    "مصطفى",
    "عمرو",
    "هاشم",
    "زياد",
    "أنس",
    "انس",
    "مالك",
    "حمزة",
    "سامي",
    "رامي",
    "هشام",
    "عصام",
    "بلال",
    "أيمن",
    "ايمن",
    "باسم",
    "وائل",
    "معاذ",
    "أسامة",
    "اسامة",
    "عمار",
    "معتصم",
    "معتز",
    "مأمون",
    "بكري",
    "صديق",
    "الطيب",
    "بابكر",
    "التاج",
    "مبارك",
    "آدم",
    "ادم",
    "موسى",
    "عيسى",
    "داود",
    "سليمان",
    "اسماعيل",
    "إسماعيل",
    "يحيى",
    "زكريا",
    "نوح",
    "هارون",
    "الزبير",
    "طلال",
    "منصور",
    "مشاري",
    "نواف",
    "متعب",
    "ثامر",
    "ريان",
    "غسان",
    "مروان",
    "رائد",
    "ثابت",
    "نبيل",
    "شريف",
    "حاتم",
    "قاسم",
    "رضوان",
    "عماد",
    "حاتم",
    "أمجد",
    "اشرف",
    "أشرف",
    "محمود",
    "مصعب",
    "جعفر",
  ])

  const femaleArabic = new Set([
    "فاطمة",
    "عائشة",
    "مريم",
    "نورة",
    "نوره",
    "سارة",
    "ساره",
    "هند",
    "ريم",
    "لمى",
    "دانا",
    "لينا",
    "نوال",
    "سمية",
    "سميه",
    "أمينة",
    "امينة",
    "أمينه",
    "خديجة",
    "خديجه",
    "زينب",
    "رقية",
    "رقيه",
    "آمنة",
    "امنة",
    "آمنه",
    "حليمة",
    "حليمه",
    "سلمى",
    "منى",
    "هدى",
    "ندى",
    "رنا",
    "ديما",
    "شيماء",
    "أسماء",
    "اسماء",
    "رهام",
    "نجلاء",
    "علياء",
    "سناء",
    "وفاء",
    "دعاء",
    "هناء",
    "صفاء",
    "رجاء",
    "بشرى",
    "ليلى",
    "سمر",
    "غادة",
    "غاده",
    "عبير",
    "نهى",
    "مها",
    "رشا",
    "نادية",
    "ناديه",
    "سامية",
    "ساميه",
    "عالية",
    "عاليه",
    "إيمان",
    "ايمان",
    "نجاة",
    "نجاه",
    "سعاد",
    "مرام",
    "جنى",
    "تالا",
    "لجين",
    "روان",
    "رزان",
    "حنين",
    "ياسمين",
    "نورين",
    "تسنيم",
    "سدين",
    "ملاك",
    "شهد",
    "لمياء",
    "رحاب",
    "انتصار",
    "اخلاص",
    "إخلاص",
    "محاسن",
    "آلاء",
    "الاء",
    "تهاني",
    "هاجر",
    "مروة",
    "مروه",
    "رغد",
    "لطيفة",
    "لطيفه",
    "نبيلة",
    "نبيله",
    "جميلة",
    "جميله",
  ])

  const maleEnglish = new Set([
    "mohammed",
    "muhammad",
    "mohamed",
    "ahmad",
    "ahmed",
    "omar",
    "ali",
    "khalid",
    "ibrahim",
    "youssef",
    "yousef",
    "yusuf",
    "hassan",
    "hussein",
    "osman",
    "othman",
    "saleh",
    "said",
    "saeed",
    "yasser",
    "yasir",
    "tariq",
    "tarek",
    "fahad",
    "fahd",
    "sultan",
    "badr",
    "nayef",
    "naif",
    "faisal",
    "salman",
    "majid",
    "majed",
    "saad",
    "rashid",
    "walid",
    "waleed",
    "nasser",
    "nasir",
    "adel",
    "kamal",
    "jamal",
    "mustafa",
    "amr",
    "ziad",
    "anas",
    "malik",
    "hamza",
    "sami",
    "rami",
    "hisham",
    "hesham",
    "bilal",
    "ayman",
    "basem",
    "basim",
    "wael",
    "osama",
    "ammar",
    "adam",
    "mousa",
    "musa",
    "issa",
    "dawoud",
    "dawood",
    "sulaiman",
    "ismail",
    "yahya",
    "noah",
    "talal",
    "mansour",
    "ghassan",
    "marwan",
    "imad",
    "emad",
    "mahmoud",
    "mahmud",
    "bakri",
    "mubarak",
  ])

  const femaleEnglish = new Set([
    "fatima",
    "fatimah",
    "aisha",
    "ayesha",
    "maryam",
    "mariam",
    "noura",
    "nora",
    "sarah",
    "sara",
    "hind",
    "reem",
    "lama",
    "dana",
    "lina",
    "nawal",
    "sumaya",
    "amina",
    "aminah",
    "khadija",
    "khadijah",
    "zainab",
    "ruqaya",
    "salma",
    "mona",
    "huda",
    "nada",
    "rana",
    "dima",
    "shimaa",
    "asma",
    "asmaa",
    "alia",
    "alya",
    "sanaa",
    "wafa",
    "duaa",
    "hanaa",
    "bushra",
    "layla",
    "leila",
    "samar",
    "ghada",
    "abeer",
    "nuha",
    "maha",
    "rasha",
    "nadia",
    "samia",
    "iman",
    "maram",
    "jana",
    "tala",
    "lujain",
    "rawan",
    "razan",
    "haneen",
    "yasmin",
    "jasmine",
    "noreen",
    "tasneem",
    "malak",
    "shahd",
    "hagar",
    "hajar",
    "marwa",
    "raghad",
    "latifa",
    "nabila",
    "jamila",
  ])

  // Check Arabic lookup
  if (maleArabic.has(arabic)) return "MALE"
  if (femaleArabic.has(arabic)) return "FEMALE"

  // Check English transliteration lookup
  if (maleEnglish.has(name)) return "MALE"
  if (femaleEnglish.has(name)) return "FEMALE"

  // Check compound "عبد" prefix — always male
  if (arabic.startsWith("عبد")) return "MALE"
  if (name.startsWith("abd")) return "MALE"

  // Arabic morphological heuristics (less certain, but useful)
  // Names ending in taa marbuta (ة) or its alef form (ه when preceded by a/i)
  // are predominantly female
  if (arabic.endsWith("ة") || arabic.endsWith("اء") || arabic.endsWith("ى")) {
    return "FEMALE"
  }

  return null
}

/** Compose a full name from parts, filtering out empty/null values. */
export function composeFullName(
  firstName?: string | null,
  middleName?: string | null,
  lastName?: string | null
): string {
  return [firstName, middleName, lastName].filter(Boolean).join(" ")
}
