import {
  ChartPie,
  Settings,
  Box,
  Cloud,
  CircleCheck,
  BookOpen,
  Calendar,
  ChartBar,
  MonitorSmartphone,
  FileText,
  Mail,
  Shield,
  Megaphone,
  Volume2,
  Bell,
  Receipt,
  Award,
  LibraryBig,
  Users,
  GraduationCap,
  UserCheck,
  Medal,
  FileText as InvoiceIcon,
  ClipboardList,
  Clock,
  List,
  Video,
  Wallet,
  CreditCard,
  User,
  TrendingUp,
  UserPlus,
  Pencil,
} from "lucide-react";

export const Icons = {
  edit: Pencil,
  pieChart: ChartPie,
  cog: Settings,
  box: Box,
  cloud: Cloud,
  checkCircle: CircleCheck,
  bookOpen: BookOpen,
  calendar: Calendar,
  barChart: ChartBar,
  browser: MonitorSmartphone,
  file: FileText,
  envelope: Mail,
  admin: Shield,
  megaphone: Megaphone,
  speaker: Volume2,
  bell: Bell,
  receipt: Receipt,
  award: Award,
  library: LibraryBig,
  users: Users,
  graduationCap: GraduationCap,
  userCheck: UserCheck,
  grades: Medal,
  invoice: InvoiceIcon,
  exam: ClipboardList,
  clock: Clock,
  subject: List,
  video: Video,
  wallet: Wallet,
  creditCard: CreditCard,
  user: User,
  trendingUp: TrendingUp,
  userPlus: UserPlus,
};
