// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details

import {
  Award,
  Bell,
  BookOpen,
  Box,
  Building2,
  Calendar,
  ChartBar,
  ChartPie,
  CircleCheck,
  ClipboardList,
  Clock,
  Cloud,
  CreditCard,
  DoorOpen,
  FileText,
  GraduationCap,
  FileText as InvoiceIcon,
  LibraryBig,
  List,
  Mail,
  Medal,
  Megaphone,
  MonitorSmartphone,
  Pencil,
  Receipt,
  Settings,
  Shield,
  Target,
  TrendingUp,
  User,
  UserCheck,
  UserPlus,
  Users,
  Video,
  Volume2,
  Wallet,
} from "lucide-react"

export const Icons = {
  edit: Pencil,
  pieChart: ChartPie,
  cog: Settings,
  box: Box,
  cloud: Cloud,
  checkCircle: CircleCheck,
  bookOpen: BookOpen,
  calendar: Calendar,
  barChart: ChartBar,
  browser: MonitorSmartphone,
  file: FileText,
  envelope: Mail,
  admin: Shield,
  megaphone: Megaphone,
  speaker: Volume2,
  bell: Bell,
  receipt: Receipt,
  award: Award,
  library: LibraryBig,
  users: Users,
  graduationCap: GraduationCap,
  userCheck: UserCheck,
  grades: Medal,
  invoice: InvoiceIcon,
  exam: ClipboardList,
  clock: Clock,
  subject: List,
  video: Video,
  wallet: Wallet,
  creditCard: CreditCard,
  user: User,
  trendingUp: TrendingUp,
  userPlus: UserPlus,
  sales: Target,
  doorOpen: DoorOpen,
  building: Building2,
}
