// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details

/**
 * Public Report Card Share Page
 *
 * Reached via an unguessable share token generated by shareReportCard().
 * No authentication required — the token itself is the credential.
 * Displays only the minimal payload returned by getSharedReportCard();
 * no cross-tenant data is reachable via this route.
 */

import { typography } from "@/lib/typography"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import type { Locale } from "@/components/internationalization/config"
import { getDictionary } from "@/components/internationalization/dictionaries"
import { getSharedReportCard } from "@/components/school-dashboard/grades/actions/share"

interface PublicReportCardPageProps {
  params: Promise<{
    lang: Locale
    token: string
  }>
}

export default async function PublicReportCardPage({
  params,
}: PublicReportCardPageProps) {
  const { lang, token } = await params
  const isRtl = lang === "ar"
  const dictionary = await getDictionary(lang)
  const d = dictionary?.school?.grades?.share

  const result = await getSharedReportCard(token)

  if (!result.valid || !result.data) {
    return (
      <main
        className="flex min-h-screen items-center justify-center bg-gradient-to-br from-slate-50 to-slate-100 p-4"
        dir={isRtl ? "rtl" : "ltr"}
      >
        <Card className="mx-auto max-w-md">
          <CardHeader className="text-center">
            <CardTitle className={typography.h3}>
              {d?.notFoundTitle ?? "Report Card Unavailable"}
            </CardTitle>
            <CardDescription>
              {d?.notFoundDescription ??
                "This report card is no longer available or the share link has expired."}
            </CardDescription>
          </CardHeader>
        </Card>
      </main>
    )
  }

  const { data } = result

  const termLabel = data.termNumber
    ? `${d?.termLabel ?? "Term"} ${data.termNumber}`
    : null

  return (
    <main
      className="flex min-h-screen flex-col items-center bg-gradient-to-br from-slate-50 to-slate-100 p-4"
      dir={isRtl ? "rtl" : "ltr"}
    >
      <div className="mx-auto w-full max-w-2xl space-y-4 py-8">
        <Card>
          <CardHeader>
            <CardTitle className={typography.h3}>
              {d?.pageTitle ?? "Report Card"}
            </CardTitle>
            <CardDescription>
              {data.studentName}
              {termLabel ? ` · ${termLabel}` : null}
            </CardDescription>
          </CardHeader>

          <CardContent className="space-y-6">
            {/* Overall summary row */}
            <dl className="grid grid-cols-2 gap-4 sm:grid-cols-4">
              {data.overallGrade && (
                <div className="space-y-1">
                  <dt className={typography.muted}>
                    {d?.overallGPA ?? "Overall GPA"}
                  </dt>
                  <dd className={typography.large}>{data.overallGrade}</dd>
                </div>
              )}
              {data.overallGPA !== null && (
                <div className="space-y-1">
                  <dt className={typography.muted}>{d?.overallGPA ?? "GPA"}</dt>
                  <dd className={typography.large}>
                    {data.overallGPA.toFixed(2)}
                  </dd>
                </div>
              )}
              {data.rank !== null && data.totalStudents !== null && (
                <div className="space-y-1 sm:col-span-2">
                  <dt className={typography.muted}>
                    {d?.rankLabel ?? "Class Rank"}
                  </dt>
                  <dd className={typography.large}>
                    {data.rank} {d?.rankOf ?? "of"} {data.totalStudents}
                  </dd>
                </div>
              )}
            </dl>

            {/* Subject grades table */}
            {data.grades.length > 0 && (
              <div>
                <h2 className={typography.h4}>
                  {d?.subjectGrades ?? "Subject Grades"}
                </h2>
                <div className="mt-3 overflow-x-auto rounded-lg border">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>
                          {dictionary?.school?.grades?.subject ?? "Subject"}
                        </TableHead>
                        <TableHead className="text-end">
                          {dictionary?.school?.grades?.score ?? "Score"}
                        </TableHead>
                        <TableHead className="text-end">
                          {dictionary?.school?.grades?.percentage ??
                            "Percentage"}
                        </TableHead>
                        <TableHead className="text-end">
                          {dictionary?.school?.grades?.grade ?? "Grade"}
                        </TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {data.grades.map((g) => (
                        <TableRow key={g.subjectId}>
                          <TableCell className="font-medium">
                            {g.subjectName}
                          </TableCell>
                          <TableCell className="text-end">
                            {g.score !== null && g.maxScore !== null
                              ? `${g.score}/${g.maxScore}`
                              : "—"}
                          </TableCell>
                          <TableCell className="text-end">
                            {g.percentage !== null
                              ? `${g.percentage.toFixed(1)}%`
                              : "—"}
                          </TableCell>
                          <TableCell className="text-end font-semibold">
                            {g.grade}
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </main>
  )
}
