// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details

"use client"

import {
  AlertTriangle,
  Award,
  Banknote,
  BarChart3,
  Bell,
  BookMarked,
  BookOpen,
  Building2,
  Bus,
  Calendar,
  CalendarDays,
  CalendarOff,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Contact,
  Database,
  DoorClosed,
  DoorOpen,
  FileSpreadsheet,
  FileText,
  FolderOpen,
  GitBranch,
  Globe,
  GraduationCap,
  HandHeart,
  Heart,
  HeartPulse,
  HelpCircle,
  House,
  IdCard,
  LayoutDashboard,
  Library,
  LineChart,
  ListOrdered,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MonitorPlay,
  Package,
  PieChart,
  PlayCircle,
  Receipt,
  RefreshCw,
  ScrollText,
  Settings,
  Shield,
  Ticket,
  TrendingDown,
  TrendingUp,
  UserCheck,
  UserPlus,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react"

const ICON_MAP: Record<string, LucideIcon> = {
  AlertTriangle,
  Award,
  Banknote,
  BarChart3,
  Bell,
  BookMarked,
  BookOpen,
  Building2,
  Bus,
  Calendar,
  CalendarDays,
  CalendarOff,
  Clock,
  ClipboardCheck,
  ClipboardList,
  Contact,
  Database,
  DoorClosed,
  DoorOpen,
  FileSpreadsheet,
  FileText,
  FolderOpen,
  GitBranch,
  Globe,
  GraduationCap,
  HandHeart,
  Heart,
  HeartPulse,
  HelpCircle,
  House,
  IdCard,
  LayoutDashboard,
  Library,
  LineChart,
  ListOrdered,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MonitorPlay,
  Package,
  PieChart,
  PlayCircle,
  Receipt,
  RefreshCw,
  ScrollText,
  Settings,
  Shield,
  Ticket,
  TrendingDown,
  TrendingUp,
  UserCheck,
  UserPlus,
  Users,
  Wallet,
}

/**
 * Resolve an icon name string to its Lucide component.
 * Returns a fallback if the name isn't found.
 */
export function getIconComponent(name: string): LucideIcon {
  return ICON_MAP[name] || LayoutDashboard
}
