// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details

/**
 * GENERATED by scripts/upload-marketing-assets.ts — do not edit by hand.
 *
 * CDN URLs for the marketing homepage's imagery, served from
 * cdn.databayt.org/balqalam/home/ with `public, max-age=31536000, immutable`.
 *
 * Keys carry a content hash, so re-authoring a tile changes its URL and the
 * new art is served immediately with no invalidation. Replace the source under
 * assets/marketing/home/, re-run the script with --upload, and commit this file.
 *
 * Split by kind so call sites are precisely typed: an image has both formats
 * for <picture>, a poster is the single URL <video poster> can take, and a
 * video is whichever one format it was authored in.
 */

/** Ticker tiles: AVIF with a WebP fallback, encoded at 2x display width. */
export const CDN_IMAGES = {
  "modern-02": {
    avif: "https://cdn.databayt.org/balqalam/home/modern-02.488b03b9.avif",
    webp: "https://cdn.databayt.org/balqalam/home/modern-02.e8369727.webp",
  },
  "modern-03": {
    avif: "https://cdn.databayt.org/balqalam/home/modern-03.64cf49f7.avif",
    webp: "https://cdn.databayt.org/balqalam/home/modern-03.290bfc62.webp",
  },
  "modern-04": {
    avif: "https://cdn.databayt.org/balqalam/home/modern-04.adcabdc3.avif",
    webp: "https://cdn.databayt.org/balqalam/home/modern-04.faa516a9.webp",
  },
  "modern-05": {
    avif: "https://cdn.databayt.org/balqalam/home/modern-05.deac6567.avif",
    webp: "https://cdn.databayt.org/balqalam/home/modern-05.b42b46ab.webp",
  },
  "modern-06": {
    avif: "https://cdn.databayt.org/balqalam/home/modern-06.a2946deb.avif",
    webp: "https://cdn.databayt.org/balqalam/home/modern-06.998ce9e6.webp",
  },
  "modern-07": {
    avif: "https://cdn.databayt.org/balqalam/home/modern-07.d38ed0d7.avif",
    webp: "https://cdn.databayt.org/balqalam/home/modern-07.0eff4c05.webp",
  },
  "modern-08": {
    avif: "https://cdn.databayt.org/balqalam/home/modern-08.f82bd0dd.avif",
    webp: "https://cdn.databayt.org/balqalam/home/modern-08.02a85f3d.webp",
  },
  "modern-09": {
    avif: "https://cdn.databayt.org/balqalam/home/modern-09.75d3d511.avif",
    webp: "https://cdn.databayt.org/balqalam/home/modern-09.43e043d8.webp",
  },
  "modern-10": {
    avif: "https://cdn.databayt.org/balqalam/home/modern-10.eb448453.avif",
    webp: "https://cdn.databayt.org/balqalam/home/modern-10.23107c6e.webp",
  },
  "modern-08-phone": {
    avif: "https://cdn.databayt.org/balqalam/home/modern-08-phone.1e48398a.avif",
    webp: "https://cdn.databayt.org/balqalam/home/modern-08-phone.207965c8.webp",
  },
  "modern-10-phone": {
    avif: "https://cdn.databayt.org/balqalam/home/modern-10-phone.4b812576.avif",
    webp: "https://cdn.databayt.org/balqalam/home/modern-10-phone.06564e5f.webp",
  },
  "ha-compare-1": {
    avif: "https://cdn.databayt.org/balqalam/home/ha-compare-1.69ef92a9.avif",
    webp: "https://cdn.databayt.org/balqalam/home/ha-compare-1.54e199f9.webp",
  },
  "ha-compare-2": {
    avif: "https://cdn.databayt.org/balqalam/home/ha-compare-2.570882a7.avif",
    webp: "https://cdn.databayt.org/balqalam/home/ha-compare-2.2049cff0.webp",
  },
} as const

/** <video poster> URLs — WebP only; a poster cannot format-negotiate. */
export const CDN_POSTERS = {
  "modern-01-poster":
    "https://cdn.databayt.org/balqalam/home/modern-01-poster.5b0402ce.webp",
  "balqalam-wordmarks-poster":
    "https://cdn.databayt.org/balqalam/home/balqalam-wordmarks-poster.bd329dd0.webp",
} as const

/** Video, published in its authored codec. */
export const CDN_VIDEOS = {
  "modern-01-webm":
    "https://cdn.databayt.org/balqalam/home/modern-01-webm.6d5eaffa.webm",
  "modern-01-phone-mp4":
    "https://cdn.databayt.org/balqalam/home/modern-01-phone-mp4.3cddcc33.mp4",
  "balqalam-wordmarks-mp4":
    "https://cdn.databayt.org/balqalam/home/balqalam-wordmarks-mp4.bb73cb8e.mp4",
} as const

export type CdnImage = keyof typeof CDN_IMAGES
export type CdnPoster = keyof typeof CDN_POSTERS
export type CdnVideo = keyof typeof CDN_VIDEOS
