name: Documentation Issue
description: Report incorrect or missing documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated documentation
        - Unclear/confusing documentation
        - Typo or grammatical error
        - Missing code examples
        - Broken links
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation located?
      placeholder: "e.g., https://ed.databayt.org/docs/contributing or docs/architecture.mdx"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is wrong or missing?
      placeholder: Describe the issue with the documentation...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: "I think it would be clearer if..."

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in fixing this yourself?
      options:
        - label: I would be willing to submit a PR to fix this

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow the project's Code of Conduct
          required: true
