// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details

/**
 * Public Invoice Share Page
 *
 * Reached via an unguessable share token generated by shareInvoice().
 * No authentication required — the token itself is the credential (the exact
 * report-card share pattern). Renders the minimal payload returned by
 * getSharedInvoice() as the print-first InvoiceSheet; a parent opening a
 * WhatsApp link can read and print the invoice without an account.
 */
import type { Metadata } from "next"

import { typography } from "@/lib/typography"
import {
  Card,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import type { Locale } from "@/components/internationalization/config"
import { getDictionary } from "@/components/internationalization/dictionaries"
import { InvoicePrintButton } from "@/components/school-dashboard/finance/invoice/invoice-print-button"
import { InvoiceSheet } from "@/components/school-dashboard/finance/invoice/invoice-sheet"
import { getSharedInvoice } from "@/components/school-dashboard/finance/invoice/share"

export const metadata: Metadata = {
  robots: { index: false, follow: false },
}

interface PublicInvoicePageProps {
  params: Promise<{
    lang: Locale
    token: string
  }>
}

export default async function PublicInvoicePage({
  params,
}: PublicInvoicePageProps) {
  const { lang, token } = await params
  const isRtl = lang === "ar"
  const dictionary = await getDictionary(lang)
  const share = ((dictionary as Record<string, any>)?.finance?.invoiceShare ??
    {}) as Record<string, string>

  const result = await getSharedInvoice(token)

  if (!result.valid || !result.data) {
    return (
      <main
        className="flex min-h-screen items-center justify-center p-4"
        dir={isRtl ? "rtl" : "ltr"}
      >
        <Card className="mx-auto w-full max-w-md">
          <CardHeader className="text-center">
            <CardTitle className={typography.h3}>
              {share.notFoundTitle || "Invoice unavailable"}
            </CardTitle>
            <CardDescription>
              {share.notFoundDescription ||
                "This invoice link is invalid, expired, or has been revoked."}
            </CardDescription>
          </CardHeader>
        </Card>
      </main>
    )
  }

  return (
    <main
      className="bg-muted/30 print:bg-background min-h-screen"
      dir={isRtl ? "rtl" : "ltr"}
    >
      <div className="mx-auto flex max-w-3xl justify-end px-6 pt-6 print:hidden">
        <InvoicePrintButton label={share.print || "Print"} />
      </div>
      <div className="pt-4 pb-16 print:p-0">
        <div className="bg-background mx-auto max-w-3xl shadow-sm print:shadow-none">
          <InvoiceSheet
            data={result.data}
            dictionary={dictionary}
            lang={lang}
          />
        </div>
      </div>
    </main>
  )
}
