// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details

import type { Metadata } from "next"

import { detectFeeProvisioningDrift } from "@/lib/fee-provisioning"
import { getTenantContext } from "@/lib/tenant-context"
import { type Locale } from "@/components/internationalization/config"
import { getDictionary } from "@/components/internationalization/dictionaries"
import { type FeeStructureRow } from "@/components/school-dashboard/finance/fees/columns"
import { FeeDriftBanner } from "@/components/school-dashboard/finance/fees/drift-banner"
import { getFeeStructureList } from "@/components/school-dashboard/finance/fees/queries"
import { FeeStructuresTable } from "@/components/school-dashboard/finance/fees/table"
import { getLabels } from "@/components/translation/person"

interface Props {
  params: Promise<{ lang: Locale; subdomain: string }>
  searchParams: Promise<Record<string, string | string[] | undefined>>
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { lang } = await params
  const dictionary = await getDictionary(lang)
  return {
    title: dictionary?.finance?.feesPage?.feeStructures || "Fee Structures",
  }
}

export default async function FeeStructuresPage({ params }: Props) {
  const { lang } = await params
  const dictionary = await getDictionary(lang)
  const { schoolId } = await getTenantContext()

  if (!schoolId) {
    return (
      <p className="text-muted-foreground">
        {dictionary?.finance?.common?.schoolNotFound ||
          "School context not found"}
      </p>
    )
  }

  const [{ rows, count }, drift] = await Promise.all([
    getFeeStructureList(schoolId, { page: 1, perPage: 20 }),
    detectFeeProvisioningDrift(schoolId),
  ])

  // Map to serializable row type with translation — one batched, deduped
  // resolution for structure + class names (no per-row N+1)
  const labels = await getLabels(
    rows.flatMap((fs) => [fs.name, fs.class?.name]),
    lang,
    schoolId
  )
  const data: FeeStructureRow[] = rows.map((fs) => ({
    id: fs.id,
    name: labels.get(fs.name) ?? fs.name,
    academicYear: fs.academicYear,
    className: fs.class?.name
      ? (labels.get(fs.class.name) ?? fs.class.name)
      : null,
    totalAmount: Number(fs.totalAmount),
    installments: fs.installments,
    assignmentCount: fs._count?.feeAssignments || 0,
    isActive: fs.isActive,
    isAutoGenerated: fs.isAutoGenerated ?? false,
    isLocked: fs.isLocked ?? false,
    createdAt: fs.createdAt.toISOString(),
  }))

  return (
    <>
      {drift.hasDrift && (
        <FeeDriftBanner
          staleRowCount={drift.staleRowCount}
          changes={drift.changes}
          signalHash={drift.signalHash}
          schoolId={schoolId}
        />
      )}
      <FeeStructuresTable initialData={data} total={count} lang={lang} />
    </>
  )
}
