// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details

import { detectFeeProvisioningDrift } from "@/lib/fee-provisioning"
import { getTenantContext } from "@/lib/tenant-context"
import { type Locale } from "@/components/internationalization/config"
import { getDictionary } from "@/components/internationalization/dictionaries"
import { type FeeStructureRow } from "@/components/school-dashboard/finance/fees/columns"
import { FeeDriftBanner } from "@/components/school-dashboard/finance/fees/drift-banner"
import { getFeeStructureList } from "@/components/school-dashboard/finance/fees/queries"
import { FeeStructuresTable } from "@/components/school-dashboard/finance/fees/table"
import { getText } from "@/components/translation/display"
import { detectLang } from "@/components/translation/util"

export const metadata = { title: "Fee Structures" }

interface Props {
  params: Promise<{ lang: Locale; subdomain: string }>
  searchParams: Promise<Record<string, string | string[] | undefined>>
}

export default async function FeeStructuresPage({ params }: Props) {
  const { lang } = await params
  const dictionary = await getDictionary(lang)
  const { schoolId } = await getTenantContext()

  if (!schoolId) {
    return (
      <p className="text-muted-foreground">
        {dictionary?.finance?.common?.schoolNotFound ||
          "School context not found"}
      </p>
    )
  }

  const [{ rows, count }, drift] = await Promise.all([
    getFeeStructureList(schoolId, { page: 1, perPage: 20 }),
    detectFeeProvisioningDrift(schoolId),
  ])

  // Map to serializable row type with translation
  const data: FeeStructureRow[] = await Promise.all(
    rows.map(async (fs) => ({
      id: fs.id,
      name: await getText(fs.name, detectLang(fs.name), lang, schoolId),
      academicYear: fs.academicYear,
      className: fs.class?.name
        ? await getText(
            fs.class.name,
            detectLang(fs.class.name),
            lang,
            schoolId
          )
        : null,
      totalAmount: Number(fs.totalAmount),
      installments: fs.installments,
      assignmentCount: fs._count?.feeAssignments || 0,
      isActive: fs.isActive,
      isAutoGenerated: fs.isAutoGenerated ?? false,
      isLocked: fs.isLocked ?? false,
      createdAt: fs.createdAt.toISOString(),
    }))
  )

  return (
    <>
      {drift.hasDrift && (
        <FeeDriftBanner
          staleRowCount={drift.staleRowCount}
          changes={drift.changes}
          signalHash={drift.signalHash}
          schoolId={schoolId}
        />
      )}
      <FeeStructuresTable initialData={data} total={count} lang={lang} />
    </>
  )
}
