"use client"

// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details
import { useEffect, useMemo, useState, useTransition } from "react"
import { useRouter } from "next/navigation"
import { AlertTriangle, X } from "lucide-react"

import type { FeeDriftChange } from "@/lib/fee-provisioning"
import { Button } from "@/components/ui/button"
import { ErrorToast, SuccessToast } from "@/components/atom/toast"
import { useDictionary } from "@/components/internationalization/use-dictionary"

import { syncAutoGeneratedFees } from "./actions"

interface Props {
  staleRowCount: number
  changes: FeeDriftChange[]
  signalHash: string
  schoolId: string
}

const DISMISS_PREFIX = "fee-drift-dismissed:"

const FIELD_FALLBACKS: Record<FeeDriftChange["field"], string> = {
  tuitionFee: "Tuition fee",
  currency: "Currency",
  country: "Country",
  schoolType: "School type",
  schoolLevel: "School level",
}

function formatValue(v: string | number | null): string {
  if (v === null || v === "") return "—"
  return String(v)
}

export function FeeDriftBanner({
  staleRowCount,
  changes,
  signalHash,
  schoolId,
}: Props) {
  const router = useRouter()
  const { dictionary } = useDictionary()
  const fdr = (dictionary as any)?.finance?.feeDrift as
    | Record<string, string>
    | undefined
  const [isPending, startTransition] = useTransition()
  const [dismissed, setDismissed] = useState(true) // default true so server-render doesn't flash

  const dismissKey = useMemo(
    () => `${DISMISS_PREFIX}${schoolId}:${signalHash}`,
    [schoolId, signalHash]
  )

  // Read dismiss state from localStorage after hydration
  useEffect(() => {
    try {
      setDismissed(window.localStorage.getItem(dismissKey) === "1")
    } catch {
      setDismissed(false)
    }
  }, [dismissKey])

  if (dismissed || staleRowCount === 0) return null

  const handleRecompute = () => {
    startTransition(async () => {
      const result = await syncAutoGeneratedFees("recompute")
      if (!result.success || !result.data) {
        ErrorToast(fdr?.syncFailed || "Sync failed")
        return
      }
      const { updated, created } = result.data
      SuccessToast(
        (fdr?.recomputed || "Recomputed — {updated} updated, {created} created")
          .replace("{updated}", String(updated))
          .replace("{created}", String(created))
      )
      router.refresh()
    })
  }

  const handleDismiss = () => {
    try {
      window.localStorage.setItem(dismissKey, "1")
    } catch {
      // ignore
    }
    setDismissed(true)
  }

  return (
    <div className="mb-4 flex items-start gap-3 rounded-md border border-amber-300 bg-amber-50 p-4 dark:border-amber-900 dark:bg-amber-950/30">
      <AlertTriangle
        className="mt-0.5 h-5 w-5 shrink-0 text-amber-600 dark:text-amber-400"
        aria-hidden="true"
      />
      <div className="flex-1 text-sm">
        <p className="font-medium">
          {fdr?.title ||
            "School settings changed since these fees were provisioned"}
        </p>
        <p className="text-muted-foreground mt-1">
          {(
            fdr?.staleSummary ||
            "{count} auto-generated fee structure(s) are using stale inputs:"
          ).replace("{count}", String(staleRowCount))}
        </p>
        <ul className="mt-2 space-y-0.5 text-xs">
          {changes.map((c) => (
            <li key={c.field}>
              <span className="font-medium">
                {fdr?.[c.field] || FIELD_FALLBACKS[c.field]}:
              </span>{" "}
              <span className="text-muted-foreground">
                {fdr?.stored || "stored"} <bdi>{formatValue(c.stored)}</bdi> →{" "}
                {fdr?.current || "current"} <bdi>{formatValue(c.current)}</bdi>
              </span>
            </li>
          ))}
        </ul>
        <div className="mt-3 flex gap-2">
          <Button
            size="sm"
            variant="default"
            onClick={handleRecompute}
            disabled={isPending}
          >
            {isPending
              ? fdr?.recomputing || "Recomputing…"
              : fdr?.recompute || "Recompute now"}
          </Button>
          <Button
            size="sm"
            variant="ghost"
            onClick={handleDismiss}
            disabled={isPending}
          >
            {fdr?.dismiss || "Dismiss"}
          </Button>
        </div>
      </div>
      <button
        type="button"
        onClick={handleDismiss}
        aria-label={fdr?.close || "Close"}
        className="text-muted-foreground hover:text-foreground"
      >
        <X className="h-4 w-4" aria-hidden="true" />
      </button>
    </div>
  )
}
