"use client"

// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details
import { useCallback, useState, useTransition } from "react"
import { useRouter } from "next/navigation"
import { ChevronDown, RefreshCw } from "lucide-react"

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { ErrorToast, SuccessToast } from "@/components/atom/toast"
import { useDictionary } from "@/components/internationalization/use-dictionary"

import { syncAutoGeneratedFees } from "./actions"

type Mode = "new-scope" | "recompute" | "reset"

export function SyncFeesButton() {
  const router = useRouter()
  const [isPending, startTransition] = useTransition()
  const [confirmMode, setConfirmMode] = useState<Mode | null>(null)
  const { dictionary } = useDictionary()
  const s = (dictionary as any)?.finance?.fees?.sync as
    | Record<string, string>
    | undefined

  const execute = useCallback(
    (mode: Mode) => {
      startTransition(async () => {
        const result = await syncAutoGeneratedFees(mode)
        if (!result.success || !result.data) {
          ErrorToast(result.error || s?.failed || "Sync failed")
          return
        }
        const {
          created,
          updated,
          lockedSkipped,
          deactivated,
          assignedStudents,
          errors,
          scope,
        } = result.data
        const tpl = (key: string, n: number) =>
          (s?.[key] || `{count} ${key}`).replace("{count}", String(n))
        const parts = [
          created > 0 ? tpl("created", created) : null,
          updated > 0 ? tpl("updated", updated) : null,
          lockedSkipped > 0 ? tpl("lockedSkipped", lockedSkipped) : null,
          deactivated > 0 ? tpl("deactivated", deactivated) : null,
          assignedStudents > 0
            ? tpl("assignedStudents", assignedStudents)
            : null,
          errors > 0 ? tpl("errors", errors) : null,
        ].filter(Boolean)
        const summary =
          parts.length > 0 ? parts.join(" · ") : s?.noChanges || "no changes"
        const prefix =
          scope === "school-wide-fallback"
            ? s?.schoolWidePrefix || "School-wide fallback — "
            : ""
        SuccessToast(`${prefix}${summary}`)
        router.refresh()
      })
    },
    [router, s]
  )

  const run = useCallback(
    (mode: Mode) => {
      if (mode === "new-scope") {
        execute(mode)
        return
      }
      setConfirmMode(mode)
    },
    [execute]
  )

  const handleConfirm = useCallback(() => {
    if (!confirmMode) return
    const mode = confirmMode
    setConfirmMode(null)
    execute(mode)
  }, [confirmMode, execute])

  const confirmTitle =
    confirmMode === "reset"
      ? s?.confirmResetTitle || "Reset all auto-generated fee structures?"
      : s?.confirmRecomputeTitle || "Recompute auto-generated fee structures?"
  const confirmBody =
    confirmMode === "reset"
      ? s?.confirmResetBody ||
        "This also overwrites LOCKED rows. Admin-created rows are still untouched."
      : s?.confirmRecomputeBody ||
        "Recompute auto-generated fee structures from current school settings."

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button
            variant="outline"
            size="sm"
            disabled={isPending}
            aria-label={s?.trigger || "Sync"}
          >
            <RefreshCw
              className={`h-4 w-4 ${isPending ? "animate-spin" : ""}`}
              aria-hidden="true"
            />
            <ChevronDown className="ms-1 h-4 w-4" aria-hidden="true" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-80">
          <DropdownMenuLabel>
            {s?.menuLabel || "Fee provisioning"}
          </DropdownMenuLabel>
          <DropdownMenuSeparator />
          <DropdownMenuItem
            onClick={() => run("new-scope")}
            className="flex-col items-start gap-1"
          >
            <span className="font-medium">
              {s?.newScope || "Sync new scope only"}
            </span>
            <span className="text-muted-foreground text-xs">
              {s?.newScopeDescription ||
                "Only create missing rows (for newly added grades). Never modifies existing rows."}
            </span>
          </DropdownMenuItem>
          <DropdownMenuItem
            onClick={() => run("recompute")}
            className="flex-col items-start gap-1"
          >
            <span className="font-medium">
              {s?.recompute || "Recompute auto-generated"}
            </span>
            <span className="text-muted-foreground text-xs">
              {s?.recomputeDescription ||
                "Re-price unlocked auto-generated rows from current settings. Locked rows are skipped."}
            </span>
          </DropdownMenuItem>
          <DropdownMenuSeparator />
          <DropdownMenuItem
            onClick={() => run("reset")}
            className="text-destructive focus:text-destructive flex-col items-start gap-1"
          >
            <span className="font-medium">
              {s?.reset || "Reset to defaults"}
            </span>
            <span className="text-muted-foreground text-xs">
              {s?.resetDescription ||
                "Overwrites every auto-generated row including locked ones. Admin-created rows stay untouched."}
            </span>
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>

      <AlertDialog
        open={confirmMode !== null}
        onOpenChange={(open) => !open && setConfirmMode(null)}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{confirmTitle}</AlertDialogTitle>
            <AlertDialogDescription className="whitespace-pre-line">
              {confirmBody}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{s?.cancel || "Cancel"}</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleConfirm}
              className={
                confirmMode === "reset"
                  ? "bg-destructive hover:bg-destructive/90"
                  : undefined
              }
            >
              {s?.confirm || "Continue"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  )
}
