"use client"

// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details
import { useCallback, useTransition } from "react"
import { useRouter } from "next/navigation"
import { ChevronDown, RefreshCw } from "lucide-react"

import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { ErrorToast, SuccessToast } from "@/components/atom/toast"

import { syncAutoGeneratedFees } from "./actions"

type Mode = "new-scope" | "recompute" | "reset"

const CONFIRM_BY_MODE: Record<Mode, string | null> = {
  "new-scope": null, // safe — no destructive action
  recompute:
    "Recompute auto-generated fee structures from current school settings?\n\n• Admin-created rows: untouched\n• Locked rows: untouched\n• Unlocked auto-generated rows: overwritten with current tuition and currency",
  reset:
    "RESET all auto-generated fee structures to defaults?\n\nThis also overwrites LOCKED rows. Admin-created rows are still untouched.",
}

export function SyncFeesButton() {
  const router = useRouter()
  const [isPending, startTransition] = useTransition()

  const run = useCallback(
    (mode: Mode) => {
      const confirmText = CONFIRM_BY_MODE[mode]
      if (confirmText && !window.confirm(confirmText)) return

      startTransition(async () => {
        const result = await syncAutoGeneratedFees(mode)
        if (!result.success || !result.data) {
          ErrorToast(result.error || "Sync failed")
          return
        }
        const {
          created,
          updated,
          lockedSkipped,
          deactivated,
          assignedStudents,
          errors,
          scope,
        } = result.data
        const parts = [
          created > 0 ? `${created} created` : null,
          updated > 0 ? `${updated} updated` : null,
          lockedSkipped > 0 ? `${lockedSkipped} locked skipped` : null,
          deactivated > 0 ? `${deactivated} orphans deactivated` : null,
          assignedStudents > 0
            ? `${assignedStudents} student assignments`
            : null,
          errors > 0 ? `${errors} errors` : null,
        ].filter(Boolean)
        const summary = parts.length > 0 ? parts.join(" · ") : "no changes"
        SuccessToast(
          `${scope === "school-wide-fallback" ? "School-wide fallback — " : ""}${summary}`
        )
        router.refresh()
      })
    },
    [router]
  )

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" disabled={isPending}>
          <RefreshCw
            className={`h-4 w-4 ${isPending ? "animate-spin" : ""}`}
            aria-hidden="true"
          />
          <span className="mx-2">{isPending ? "Syncing…" : "Sync Fees"}</span>
          <ChevronDown className="h-4 w-4" aria-hidden="true" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-80">
        <DropdownMenuLabel>Fee provisioning</DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem
          onClick={() => run("new-scope")}
          className="flex-col items-start gap-1"
        >
          <span className="font-medium">Sync new scope only</span>
          <span className="text-muted-foreground text-xs">
            Only create missing rows (for newly added grades). Never modifies
            existing rows.
          </span>
        </DropdownMenuItem>
        <DropdownMenuItem
          onClick={() => run("recompute")}
          className="flex-col items-start gap-1"
        >
          <span className="font-medium">Recompute auto-generated</span>
          <span className="text-muted-foreground text-xs">
            Re-price unlocked auto-generated rows from current settings. Locked
            rows are skipped.
          </span>
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem
          onClick={() => run("reset")}
          className="text-destructive focus:text-destructive flex-col items-start gap-1"
        >
          <span className="font-medium">Reset to defaults</span>
          <span className="text-muted-foreground text-xs">
            Overwrites every auto-generated row including locked ones. Admin-
            created rows stay untouched.
          </span>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
