"use client"

// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details
import * as React from "react"
import { useCallback, useMemo } from "react"
import { useRouter } from "next/navigation"
import { Users } from "lucide-react"

import { formatCurrency } from "@/lib/i18n-format"
import { actionErrorMessage } from "@/lib/resolve-action-error"
import { useDebouncedSearch } from "@/hooks/use-debounced-search"
import { usePlatformData } from "@/hooks/use-platform-data"
import { usePlatformView } from "@/hooks/use-platform-view"
import { Badge } from "@/components/ui/badge"
import {
  confirmDeleteDialog,
  DeleteToast,
  ErrorToast,
} from "@/components/atom/toast"
import type { Locale } from "@/components/internationalization/config"
import { useDictionary } from "@/components/internationalization/use-dictionary"
import {
  ItemCard,
  ListingViews,
  PlatformToolbar,
  RowActions,
  TableGrid,
} from "@/components/school-dashboard/shared"
import { DataTable } from "@/components/table/data-table"
import { useDataTable } from "@/components/table/use-data-table"

import {
  deleteFeeStructure,
  getFeeStructures,
  toggleFeeStructureActive,
  toggleFeeStructureLocked,
} from "./actions"
import { getFeeStructureColumns, type FeeStructureRow } from "./columns"
import { STATUS_COLORS } from "./config"
import { SyncFeesButton } from "./sync-fees-button"

interface FeeStructuresTableProps {
  initialData: FeeStructureRow[]
  total: number
  lang: Locale
  perPage?: number
  /** The school's currency — `School.currency`, never a default. */
  currency?: string
}

function FeeStructuresTableInner({
  initialData,
  total,
  lang,
  perPage = 20,
  currency,
}: FeeStructuresTableProps) {
  const router = useRouter()
  const { dictionary } = useDictionary()
  const searchT = (dictionary as any)?.finance?.fees?.search as
    | Record<string, string>
    | undefined
  const structureCol = (dictionary as any)?.finance?.fees?.structureColumns as
    | Record<string, string>
    | undefined
  const [searchValue, debouncedSearch, setSearchValue] = useDebouncedSearch(300)

  // View mode (table/grid) — cards by default on a phone
  const { view, phoneView, toggleView } = usePlatformView({
    defaultView: "table",
    phoneView: "grid",
  })

  // Data management with optimistic updates
  const {
    data,
    total: dataTotal,
    isLoading,
    hasMore,
    loadMore,
    refresh,
    optimisticRemove,
  } = usePlatformData<FeeStructureRow>({
    initialData,
    total,
    perPage,
    filters: debouncedSearch ? { search: debouncedSearch } : undefined,
    fetcher: async (params) => {
      // `search` arrives via the filters object above; getFeeStructures gained
      // an optional search param so the query — not the client — does the work.
      const result = await getFeeStructures(
        typeof params.search === "string" ? params.search : undefined
      )
      if (!result.success || !result.data) {
        return { rows: [], total: 0 }
      }
      const rows: FeeStructureRow[] = result.data.map((fs: any) => ({
        id: fs.id,
        name: fs.name,
        academicYear: fs.academicYear,
        className: fs.class?.name || null,
        totalAmount: Number(fs.totalAmount),
        installments: fs.installments,
        assignmentCount: fs._count?.feeAssignments || 0,
        isActive: fs.isActive,
        isAutoGenerated: fs.isAutoGenerated ?? false,
        isLocked: fs.isLocked ?? false,
        createdAt:
          fs.createdAt instanceof Date
            ? fs.createdAt.toISOString()
            : String(fs.createdAt),
      }))
      return { rows, total: rows.length }
    },
  })

  // Single-row actions
  const handleToggleActive = useCallback(
    async (id: string) => {
      const result = await toggleFeeStructureActive(id)
      if (result.success) {
        refresh()
      } else {
        ErrorToast(
          actionErrorMessage(
            result.error,
            dictionary,
            dictionary?.common?.errors?.UPDATE_FAILED || "Failed to update"
          )
        )
      }
    },
    [refresh]
  )

  const handleToggleLocked = useCallback(
    async (id: string) => {
      const result = await toggleFeeStructureLocked(id)
      if (result.success) {
        refresh()
      } else {
        ErrorToast(
          actionErrorMessage(
            result.error,
            dictionary,
            dictionary?.common?.errors?.UPDATE_FAILED || "Failed to update"
          )
        )
      }
    },
    [refresh]
  )

  const handleSingleDelete = useCallback(
    async (id: string) => {
      const ok = await confirmDeleteDialog("Delete this fee structure?")
      if (!ok) return
      const result = await deleteFeeStructure(id)
      if (result.success) {
        optimisticRemove(id)
        DeleteToast()
      } else {
        ErrorToast(
          actionErrorMessage(
            result.error,
            dictionary,
            dictionary?.common?.failedToDelete || "Failed to delete"
          )
        )
      }
    },
    [optimisticRemove]
  )

  // Generate columns on the client side with lang
  const columns = useMemo(
    () =>
      getFeeStructureColumns(
        lang,
        structureCol,
        {
          onToggleActive: handleToggleActive,
          onToggleLocked: handleToggleLocked,
          onDelete: handleSingleDelete,
        },
        currency
      ),
    [
      lang,
      structureCol,
      currency,
      handleToggleActive,
      handleToggleLocked,
      handleSingleDelete,
    ]
  )

  // Table instance
  const { table } = useDataTable<FeeStructureRow>({
    data,
    columns,
    pageCount: 1,
    enableClientFiltering: true,
    initialState: {
      pagination: {
        pageIndex: 0,
        pageSize: data.length || perPage,
      },
      columnVisibility: {
        createdAt: false,
        className: false,
        academicYear: false,
      },
    },
  })

  // Handle search
  const handleSearchChange = useCallback(
    (value: string) => {
      setSearchValue(value)
    },
    [setSearchValue]
  )

  // Handle create
  const handleCreate = useCallback(() => {
    router.push(`/${lang}/finance/fees/structures/new`)
  }, [router, lang])

  return (
    <>
      <PlatformToolbar
        table={table}
        view={view}
        phoneView={phoneView}
        onToggleView={toggleView}
        searchValue={searchValue}
        onSearchChange={handleSearchChange}
        searchPlaceholder={searchT?.feeStructures || "Search fee structures..."}
        onCreate={handleCreate}
        entityName="fee-structures"
        additionalActions={<SyncFeesButton />}
      />

      <ListingViews
        view={view}
        phoneView={phoneView}
        table={
          <DataTable
            table={table}
            paginationMode="load-more"
            hasMore={hasMore}
            isLoading={isLoading}
            onLoadMore={loadMore}
          />
        }
        grid={
          <TableGrid
            table={table}
            hasMore={hasMore}
            isLoading={isLoading}
            onLoadMore={loadMore}
          >
            {(row) => {
              const fee = row.original
              return (
                <ItemCard
                  key={row.id}
                  href={`/${lang}/finance/fees/structures/${fee.id}`}
                  eyebrow={fee.academicYear}
                  title={fee.name}
                  value={formatCurrency(
                    fee.totalAmount,
                    lang,
                    currency || "USD"
                  )}
                  badges={
                    <>
                      <Badge
                        variant="outline"
                        className={
                          fee.isActive
                            ? STATUS_COLORS.ACTIVE
                            : STATUS_COLORS.INACTIVE
                        }
                      >
                        {fee.isActive
                          ? structureCol?.active
                          : structureCol?.inactive}
                      </Badge>
                      {fee.isAutoGenerated ? (
                        <Badge variant="outline" className="bg-background">
                          {structureCol?.auto}
                        </Badge>
                      ) : null}
                      {fee.isLocked ? (
                        <Badge variant="outline" className="bg-background">
                          {structureCol?.locked}
                        </Badge>
                      ) : null}
                    </>
                  }
                  meta={
                    <span className="inline-flex items-center gap-1">
                      <Users className="size-3" aria-hidden="true" />
                      {fee.assignmentCount}
                    </span>
                  }
                  actions={<RowActions row={row} />}
                />
              )
            }}
          </TableGrid>
        }
      />
    </>
  )
}

export const FeeStructuresTable = React.memo(FeeStructuresTableInner)
