"use client"

// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details
import * as React from "react"
import { useCallback, useMemo, useState } from "react"
import { useRouter } from "next/navigation"

import { useDebouncedSearch } from "@/hooks/use-debounced-search"
import { usePlatformData } from "@/hooks/use-platform-data"
import { usePlatformView } from "@/hooks/use-platform-view"
import {
  confirmDeleteDialog,
  DeleteToast,
  ErrorToast,
} from "@/components/atom/toast"
import type { Locale } from "@/components/internationalization/config"
import { useDictionary } from "@/components/internationalization/use-dictionary"
import { PlatformToolbar } from "@/components/school-dashboard/shared"
import {
  BulkActionsToolbar,
  createDeleteAction,
  createExportAction,
} from "@/components/table/bulk-actions-toolbar"
import { DataTable } from "@/components/table/data-table"
import { getSelectColumn } from "@/components/table/select-column"
import { useDataTable } from "@/components/table/use-data-table"

import {
  deleteFeeStructure,
  getFeeStructures,
  toggleFeeStructureActive,
  toggleFeeStructureLocked,
} from "./actions"
import { getFeeStructureColumns, type FeeStructureRow } from "./columns"
import { SyncFeesButton } from "./sync-fees-button"

interface FeeStructuresTableProps {
  initialData: FeeStructureRow[]
  total: number
  lang: Locale
  perPage?: number
}

function FeeStructuresTableInner({
  initialData,
  total,
  lang,
  perPage = 20,
}: FeeStructuresTableProps) {
  const router = useRouter()
  const { dictionary } = useDictionary()
  const searchT = (dictionary as any)?.finance?.fees?.search as
    | Record<string, string>
    | undefined
  const structureCol = (dictionary as any)?.finance?.fees?.structureColumns as
    | Record<string, string>
    | undefined
  const [searchValue, debouncedSearch, setSearchValue] = useDebouncedSearch(300)

  // View mode (table/grid)
  const { view, toggleView } = usePlatformView({ defaultView: "table" })

  // Data management with optimistic updates
  const {
    data,
    total: dataTotal,
    isLoading,
    hasMore,
    loadMore,
    refresh,
    optimisticRemove,
  } = usePlatformData<FeeStructureRow>({
    initialData,
    total,
    perPage,
    fetcher: async (params) => {
      const result = await getFeeStructures()
      if (!result.success || !result.data) {
        return { rows: [], total: 0 }
      }
      const rows: FeeStructureRow[] = result.data.map((fs: any) => ({
        id: fs.id,
        name: fs.name,
        academicYear: fs.academicYear,
        className: fs.class?.name || null,
        totalAmount: Number(fs.totalAmount),
        installments: fs.installments,
        assignmentCount: fs._count?.feeAssignments || 0,
        isActive: fs.isActive,
        isAutoGenerated: fs.isAutoGenerated ?? false,
        isLocked: fs.isLocked ?? false,
        createdAt:
          fs.createdAt instanceof Date
            ? fs.createdAt.toISOString()
            : String(fs.createdAt),
      }))
      return { rows, total: rows.length }
    },
  })

  // Single-row actions
  const handleToggleActive = useCallback(
    async (id: string) => {
      const result = await toggleFeeStructureActive(id)
      if (result.success) {
        refresh()
      } else {
        ErrorToast(result.error || "Failed to toggle status")
      }
    },
    [refresh]
  )

  const handleToggleLocked = useCallback(
    async (id: string) => {
      const result = await toggleFeeStructureLocked(id)
      if (result.success) {
        refresh()
      } else {
        ErrorToast(result.error || "Failed to toggle lock")
      }
    },
    [refresh]
  )

  const handleSingleDelete = useCallback(
    async (id: string) => {
      const ok = await confirmDeleteDialog("Delete this fee structure?")
      if (!ok) return
      const result = await deleteFeeStructure(id)
      if (result.success) {
        optimisticRemove(id)
        DeleteToast()
      } else {
        ErrorToast(result.error || "Failed to delete")
      }
    },
    [optimisticRemove]
  )

  // Generate columns on the client side with lang
  const columns = useMemo(
    () => [
      getSelectColumn<FeeStructureRow>(),
      ...getFeeStructureColumns(lang, structureCol, {
        onToggleActive: handleToggleActive,
        onToggleLocked: handleToggleLocked,
        onDelete: handleSingleDelete,
      }),
    ],
    [
      lang,
      structureCol,
      handleToggleActive,
      handleToggleLocked,
      handleSingleDelete,
    ]
  )

  // Table instance
  const { table } = useDataTable<FeeStructureRow>({
    data,
    columns,
    pageCount: 1,
    enableClientFiltering: true,
    initialState: {
      pagination: {
        pageIndex: 0,
        pageSize: data.length || perPage,
      },
      columnVisibility: {
        createdAt: false,
      },
    },
  })

  // Handle search
  const handleSearchChange = useCallback(
    (value: string) => {
      setSearchValue(value)
    },
    [setSearchValue]
  )

  // Handle create
  const handleCreate = useCallback(() => {
    router.push(`/${lang}/finance/fees/structures/new`)
  }, [router, lang])

  // Bulk delete handler
  const handleBulkDelete = useCallback(
    async (rows: FeeStructureRow[]) => {
      const deleteMsg = `Delete ${rows.length} fee structure(s)?`
      const ok = await confirmDeleteDialog(deleteMsg)
      if (!ok) return

      const errors: string[] = []
      for (const row of rows) {
        const result = await deleteFeeStructure(row.id)
        if (result.success) {
          optimisticRemove(row.id)
        } else {
          errors.push(`${row.name}: ${result.error}`)
        }
      }

      if (errors.length > 0) {
        ErrorToast(errors.join("\n"))
      } else {
        DeleteToast()
      }
      table.toggleAllPageRowsSelected(false)
    },
    [optimisticRemove, table]
  )

  // Bulk export handler
  const handleBulkExport = useCallback(
    async (rows: FeeStructureRow[]) => {
      const header = "Name,Academic Year,Class,Total Amount,Installments,Active"
      const csv = rows
        .map(
          (r) =>
            `${r.name},${r.academicYear},${r.className || "All Classes"},${r.totalAmount},${r.installments},${r.isActive}`
        )
        .join("\n")
      const csvContent = `${header}\n${csv}`

      // Download
      const blob = new Blob([csvContent], {
        type: "text/csv;charset=utf-8;",
      })
      const link = document.createElement("a")
      link.href = URL.createObjectURL(blob)
      link.download = "fee-structures.csv"
      link.click()
      table.toggleAllPageRowsSelected(false)
    },
    [table]
  )

  // Bulk actions
  const bulkActions = useMemo(
    () => [
      createDeleteAction<FeeStructureRow>(handleBulkDelete, lang),
      createExportAction<FeeStructureRow>(handleBulkExport, lang),
    ],
    [handleBulkDelete, handleBulkExport, lang]
  )

  return (
    <>
      <PlatformToolbar
        table={table}
        view={view}
        onToggleView={toggleView}
        searchValue={searchValue}
        onSearchChange={handleSearchChange}
        searchPlaceholder={searchT?.feeStructures || "Search fee structures..."}
        onCreate={handleCreate}
        entityName="fee-structures"
        additionalActions={<SyncFeesButton />}
      />

      <DataTable
        table={table}
        paginationMode="load-more"
        hasMore={hasMore}
        isLoading={isLoading}
        onLoadMore={loadMore}
      />

      <BulkActionsToolbar table={table} actions={bulkActions} lang={lang} />
    </>
  )
}

export const FeeStructuresTable = React.memo(FeeStructuresTableInner)
