"use server"

// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details
//
// Transport route fees → billing (finance-owned provisioning).
//
// transportation/actions/fees.ts::previewTransportFees is deliberately
// read-only — per transportation/CLAUDE.md, fee-record creation belongs to
// finance. This action closes that loop: for a billing month it materializes
// one auto-generated FeeStructure per fee-bearing route, one FeeAssignment per
// actively-assigned student, and the matching UserInvoice rows through the
// same `ensureInvoicesForAssignment` pipeline enrollment fees use.
//
// Idempotent end to end: the FeeStructure is matched by
// sourceSignals.{transportRouteId,billingMonth}, assignments by the
// @@unique([studentId, feeStructureId, academicYear]) constraint, and invoice
// sync by its own count-guard — re-running a month creates nothing twice.
import { revalidatePath } from "next/cache"
import { z } from "zod"

import { ACTION_ERRORS, actionError } from "@/lib/action-errors"
import type { ActionResponse } from "@/lib/action-response"
import { db } from "@/lib/db"
import { ensureInvoicesForAssignment } from "@/lib/fee-invoice-sync"
import { getDictionary } from "@/components/internationalization/dictionaries"

import { isFinanceAuthError, requireFinanceActor } from "../guard"

const inputSchema = z.object({
  /** Billing month in `YYYY-MM` form (the FeeStructure is per route+month). */
  billingMonth: z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),
  /** Defaults to the school's latest SchoolYear when omitted. */
  academicYear: z.string().trim().min(1).max(20).optional(),
})

export interface TransportProvisionResult {
  routesProcessed: number
  studentsProvisioned: number
  invoicesCreated: number
  skippedExisting: number
}

export async function provisionTransportFees(
  raw: unknown
): Promise<ActionResponse<TransportProvisionResult>> {
  try {
    const ctx = await requireFinanceActor("fees", "create")
    if (isFinanceAuthError(ctx)) return ctx
    const { schoolId } = ctx

    const parsed = inputSchema.safeParse(raw)
    if (!parsed.success) return actionError(ACTION_ERRORS.VALIDATION_ERROR)
    const { billingMonth } = parsed.data

    const school = await db.school.findUnique({
      where: { id: schoolId },
      select: { currency: true, preferredLanguage: true },
    })
    const academicYear =
      parsed.data.academicYear ?? (await resolveCurrentAcademicYear(schoolId))

    const dictionary = await getDictionary(
      school?.preferredLanguage === "ar" ? "ar" : "en"
    )
    const transportLabel =
      ((dictionary as Record<string, any>)?.finance?.feeComponents
        ?.transportFee as string | undefined) || "Transport Fee"

    const assignments = await db.routeAssignment.findMany({
      where: { schoolId, status: "ACTIVE", deletedAt: null },
      select: {
        studentId: true,
        route: { select: { id: true, name: true, monthlyFee: true } },
      },
    })

    // Group fee-bearing routes; routes without a monthlyFee bill nothing.
    const byRoute = new Map<
      string,
      { name: string; monthlyFee: number; studentIds: Set<string> }
    >()
    for (const a of assignments) {
      if (!a.route) continue
      const fee = Number(a.route.monthlyFee ?? 0)
      if (!Number.isFinite(fee) || fee <= 0) continue
      const entry = byRoute.get(a.route.id) ?? {
        name: a.route.name,
        monthlyFee: fee,
        studentIds: new Set<string>(),
      }
      entry.studentIds.add(a.studentId)
      byRoute.set(a.route.id, entry)
    }

    let routesProcessed = 0
    let studentsProvisioned = 0
    let invoicesCreated = 0
    let skippedExisting = 0
    const newAssignmentIds: string[] = []

    for (const [routeId, route] of byRoute) {
      // Structure + assignments per route in one short transaction. Invoice
      // sync runs after commit (idempotent, heals on re-run) so the
      // transaction stays small even for large routes.
      const result = await db.$transaction(async (tx) => {
        let structure = await tx.feeStructure.findFirst({
          where: {
            schoolId,
            isAutoGenerated: true,
            AND: [
              {
                sourceSignals: {
                  path: ["transportRouteId"],
                  equals: routeId,
                },
              },
              {
                sourceSignals: { path: ["billingMonth"], equals: billingMonth },
              },
            ],
          },
          select: { id: true },
        })

        if (!structure) {
          structure = await tx.feeStructure.create({
            data: {
              schoolId,
              name: `${transportLabel} — ${route.name} — ${billingMonth}`,
              academicYear,
              tuitionFee: 0,
              transportFee: route.monthlyFee,
              totalAmount: route.monthlyFee,
              installments: 1,
              isActive: true,
              isAutoGenerated: true,
              currency: school?.currency ?? null,
              sourceSignals: {
                transportRouteId: routeId,
                billingMonth,
                source: "transport-provisioning",
              },
            },
            select: { id: true },
          })
        }

        const existing = await tx.feeAssignment.findMany({
          where: { schoolId, feeStructureId: structure.id },
          select: { studentId: true },
        })
        const alreadyAssigned = new Set(existing.map((e) => e.studentId))

        const createdIds: string[] = []
        let skipped = 0
        for (const studentId of route.studentIds) {
          if (alreadyAssigned.has(studentId)) {
            skipped++
            continue
          }
          const created = await tx.feeAssignment.create({
            data: {
              schoolId,
              studentId,
              feeStructureId: structure.id,
              academicYear,
              finalAmount: route.monthlyFee,
              currency: school?.currency ?? null,
            },
            select: { id: true },
          })
          createdIds.push(created.id)
        }
        return { createdIds, skipped }
      })

      routesProcessed++
      studentsProvisioned += result.createdIds.length
      skippedExisting += result.skipped
      newAssignmentIds.push(...result.createdIds)
    }

    for (const assignmentId of newAssignmentIds) {
      try {
        const res = await ensureInvoicesForAssignment(schoolId, assignmentId)
        invoicesCreated += res.invoicesCreated
      } catch (err) {
        console.warn(
          "[provisionTransportFees] Invoice sync failed for assignment",
          assignmentId,
          err
        )
      }
    }

    revalidatePath("/finance/fees")
    revalidatePath("/finance/invoice")

    return {
      success: true,
      data: {
        routesProcessed,
        studentsProvisioned,
        invoicesCreated,
        skippedExisting,
      },
    }
  } catch (error) {
    console.error("[provisionTransportFees]", error)
    return actionError(ACTION_ERRORS.CREATE_FAILED)
  }
}

// Same resolution used by fee-auto-assign/fee-provisioning (private there):
// latest SchoolYear name, calendar-year pair fallback.
async function resolveCurrentAcademicYear(schoolId: string): Promise<string> {
  const currentYear = await db.schoolYear.findFirst({
    where: { schoolId },
    orderBy: { startDate: "desc" },
    select: { yearName: true },
  })
  return (
    currentYear?.yearName ??
    `${new Date().getFullYear()}-${new Date().getFullYear() + 1}`
  )
}
