#!/usr/bin/env python3
# Copyright (c) 2025-present databayt
# Licensed under SSPL-1.0 -- see LICENSE for details
"""Generate `src/components/lumos/shared/video-player/sf-symbols.tsx`.

The lumos player and the live room mirror Apple's TV app (`public/apple-tv/`),
whose every control is an SF Symbol. The outlines here come from the OS itself:
`sym2png.swift` draws each symbol at 1000pt through AppKit, potrace turns the
bitmap back into curves, and the result is written in HUNDREDTHS OF THE POINT
SIZE — so a glyph drawn at `pt` is `w/100·pt × h/100·pt` px, exactly how the OS
sizes differently shaped symbols at one point size.

    python3 scripts/sf-icons/extract.py            # macOS + potrace + Pillow

Edit `manifest.json`, never the generated file.
"""

import json
import os
import re
import subprocess
import sys
import tempfile

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, "src/components/lumos/shared/video-player/sf-symbols.tsx")
PT = 1000


def parse_potrace(d):
    """potrace's SVG path (absolute M, relative m/l/c) → absolute segments."""
    toks = re.findall(r"[MmLlCcZz]|-?\d+(?:\.\d+)?", d)
    i, cmd = 0, None
    cx = cy = sx = sy = 0.0
    out = []
    while i < len(toks):
        t = toks[i]
        if t in "MmLlCcZz":
            cmd = t
            i += 1
            if cmd in "Zz":
                out.append(("Z",))
                cx, cy = sx, sy
            continue
        n = 6 if cmd in "Cc" else 2
        v = [float(x) for x in toks[i : i + n]]
        i += n
        rel = cmd.islower()
        pts = []
        for k in range(0, n, 2):
            pts += [cx + v[k], cy + v[k + 1]] if rel else [v[k], v[k + 1]]
        if cmd in "Mm":
            out.append(("M", *pts))
            sx, sy = pts
            cmd = "l" if rel else "L"
        else:
            out.append(("C" if cmd in "Cc" else "L", *pts))
        cx, cy = pts[-2], pts[-1]
    return out


def fmt(v):
    s = f"{v:.1f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def trace(path):
    im = Image.open(path).convert("L")
    ink = im.point(lambda p: 255 if p < 128 else 0)
    x0, y0, x1, y1 = ink.getbbox()
    bw = im.point(lambda p: 0 if p < 128 else 255, "1")
    with tempfile.TemporaryDirectory() as tmp:
        pbm, svg = os.path.join(tmp, "g.pbm"), os.path.join(tmp, "g.svg")
        bw.save(pbm)
        subprocess.run(
            ["potrace", "-b", "svg", "--flat", "-t", "4", "-a", "1", "-O", "0.4", "-u", "10", "-o", svg, pbm],
            check=True,
        )
        text = open(svg).read()
    tx, ty, kx, ky = map(
        float,
        re.search(r'translate\(([\d.]+),([\d.]+)\) scale\(([\d.]+),(-?[\d.]+)\)', text).groups(),
    )
    unit = PT / 100.0
    d = []
    for chunk in re.findall(r'<path d="([^"]+)"', text):
        for seg in parse_potrace(chunk):
            if seg[0] == "Z":
                d.append("Z")
                continue
            xy = seg[1:]
            nums = []
            for k in range(0, len(xy), 2):
                nums.append(fmt((tx + kx * xy[k] - x0) / unit))
                nums.append(fmt((ty + ky * xy[k + 1] - y0) / unit))
            d.append(seg[0] + " ".join(nums))
    return round((x1 - x0) / unit, 1), round((y1 - y0) / unit, 1), "".join(d)


def ident(name):
    parts = re.split(r"[.\-]", name)
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def main():
    manifest = json.load(open(os.path.join(HERE, "manifest.json")))["symbols"]
    specs = [f'{s["name"]}:{s["weight"]}' for s in manifest]
    with tempfile.TemporaryDirectory() as tmp:
        res = subprocess.run(
            ["swift", os.path.join(HERE, "sym2png.swift"), tmp, str(PT), *specs],
            capture_output=True,
            text=True,
            check=True,
        )
        rendered = {}
        for line in res.stdout.splitlines():
            if not line.startswith("{"):
                continue
            meta = json.loads(line)
            if "error" in meta:
                sys.exit(f"missing symbol: {meta['name']}")
            rendered[meta["name"]] = trace(meta["file"])

    lines = [
        "// Copyright (c) 2025-present databayt",
        "// Licensed under SSPL-1.0 -- see LICENSE for details",
        "//",
        "// GENERATED by scripts/sf-icons/extract.py from scripts/sf-icons/manifest.json.",
        "// Do not edit by hand — change the manifest and regenerate.",
        "//",
        "// SF Symbols as drawn by macOS, traced back to curves. Apple's SF Symbols",
        "// licence limits their use to interfaces on Apple platforms.",
        'import type { SVGProps } from "react"',
        "",
        'import { cn } from "@/lib/utils"',
        "",
        "/** One symbol, in hundredths of its point size. */",
        "export interface SfGlyph {",
        "  w: number",
        "  h: number",
        "  d: string",
        "}",
        "",
    ]
    for s in manifest:
        w, h, d = rendered[s["name"]]
        lines.append(f'/** `{s["name"]}` · {s["weight"]} — {s["use"]} */')
        lines.append(f'export const {ident(s["name"])}: SfGlyph = {{')
        lines.append(f"  w: {w},")
        lines.append(f"  h: {h},")
        lines.append(f'  d: "{d}",')
        lines.append("}")
        lines.append("")
    lines += [
        "type SfSymbolProps = Omit<",
        "  SVGProps<SVGSVGElement>,",
        '  "width" | "height" | "viewBox" | "children"',
        "> & {",
        "  glyph: SfGlyph",
        "  /** The symbol's point size, as the OS would be configured — NOT a box. */",
        "  pt: number",
        "}",
        "",
        "/**",
        " * Draw a symbol at a point size. The box follows the glyph's own shape, so",
        " * `pip.enter` comes out wider than `xmark` at the same `pt` — the optical",
        " * rhythm a row of symbols has on iOS, which a square `size-5` would flatten.",
        " */",
        "export function SfSymbol({ glyph, pt, className, ...rest }: SfSymbolProps) {",
        "  return (",
        "    <svg",
        "      viewBox={`0 0 ${glyph.w} ${glyph.h}`}",
        "      width={Math.round(glyph.w * pt) / 100}",
        "      height={Math.round(glyph.h * pt) / 100}",
        '      fill="currentColor"',
        "      aria-hidden",
        "      focusable={false}",
        '      className={cn("shrink-0", className)}',
        "      {...rest}",
        "    >",
        "      <path d={glyph.d} />",
        "    </svg>",
        "  )",
        "}",
        "",
    ]
    open(OUT, "w").write("\n".join(lines))
    size = os.path.getsize(OUT)
    print(f"wrote {os.path.relpath(OUT, ROOT)} ({len(manifest)} symbols, {size // 1024} KB)")


if __name__ == "__main__":
    main()
