"use server"

// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details
import { revalidatePath } from "next/cache"
import { after } from "next/server"

import {
  createActionResponse,
  type ActionResponse,
} from "@/lib/action-response"
import { db } from "@/lib/db"
import { dispatchSetupGuideNotifications } from "@/lib/setup-guide-notifications"
import { syncStudentGrades } from "@/lib/sync-student-grades"
import { repairProvisioning } from "@/components/catalog/provision"

import { requireSchoolOwnership } from "../auth-helpers"

export async function completeOnboarding(
  schoolId: string,
  // TODO: legalData (operationalStatus, safetyFeatures) is collected but not yet persisted.
  // Needs a ComplianceLog entry or School schema fields in a future PR.
  legalData: {
    operationalStatus: string
    safetyFeatures: string[]
  }
): Promise<ActionResponse> {
  try {
    const authContext = await requireSchoolOwnership(schoolId)

    // Check domain exists BEFORE marking school active
    const schoolCheck = await db.school.findUnique({
      where: { id: schoolId },
      select: { domain: true },
    })

    if (!schoolCheck?.domain) {
      return { success: false, code: "SUBDOMAIN_NOT_CONFIGURED" }
    }

    const school = await db.school.update({
      where: { id: schoolId },
      data: {
        isActive: true,
        isPublished: true,
        onboardingCompletedAt: new Date(),
        onboardingStep: "completed",
      },
      select: {
        id: true,
        name: true,
        domain: true,
        country: true,
        timetableStructure: true,
        schoolLevel: true,
        schoolType: true,
        preferredLanguage: true,
      },
    })

    // Provision defaults after response is sent.
    // Uses next/server after() so Vercel keeps the function alive until completion
    // (unlike fire-and-forget promises which get terminated on serverless).
    after(async () => {
      try {
        await provisionSchoolDefaults(schoolId, school, authContext.userId)
      } catch (err) {
        console.error(
          `[completeOnboarding] Provisioning failed for ${schoolId}:`,
          err
        )
      }
    })

    revalidatePath(`/onboarding/${schoolId}`)

    return createActionResponse({
      success: true,
      school,
      redirectUrl: `/onboarding/${schoolId}/congratulations`,
    })
  } catch (error) {
    return createActionResponse(undefined, error)
  }
}

/**
 * Background provisioning for a newly onboarded school.
 * Runs all setup steps (defaults, catalog, timetable, classrooms, sections).
 * Called fire-and-forget so it doesn't block the onboarding response.
 */
async function provisionSchoolDefaults(
  schoolId: string,
  school: {
    country: string | null
    timetableStructure: string | null
    schoolLevel: string | null
    schoolType: string | null
    preferredLanguage: string | null
  },
  userId: string
) {
  // Defaults → academic structure → selections → schedule → sections →
  // timetable slots → join code. The doctor runs whichever stages are missing
  // (all of them on a fresh school), each one idempotent, one failed stage
  // never blocking the rest. A later re-run (manual publishSchool, operator
  // repair) completes any stage lost to a serverless timeout here.
  const repair = await repairProvisioning(schoolId).catch((err) => {
    console.error(
      `[provisionSchoolDefaults] Provisioning failed for ${schoolId}:`,
      err
    )
    return null
  })
  if (repair) {
    const failures = repair.failed.length
      ? ` | failed: ${repair.failed.map((f) => `${f.stage} (${f.error})`).join(", ")}`
      : ""
    console.log(
      `[provisionSchoolDefaults] ${schoolId} stages run: [${repair.repaired.join(", ")}]${failures}`
    )
  }

  // Re-resolve student grades now that AcademicGrade records exist
  const syncResult = await syncStudentGrades(schoolId).catch((err) => {
    console.error(
      `[provisionSchoolDefaults] Grade sync failed for ${schoolId}:`,
      err
    )
    return { updated: 0 }
  })
  if (syncResult.updated > 0) {
    console.log(
      `[provisionSchoolDefaults] Synced grades for ${syncResult.updated} students`
    )
  }

  // Step 5: Auto-provision per-grade FeeStructures from onboarding pricing.
  // Uses School.tuitionFee / School.currency and the grades created by catalog
  // setup. Marks each row as isAutoGenerated so the Sync Fees button can
  // re-process them later. Fans out to existing students so /finance/fees/my
  // is non-empty for each enrolled student.
  const { provisionSchoolFees } = await import("@/lib/fee-provisioning")
  await provisionSchoolFees(schoolId).catch((err) =>
    console.error(
      `[provisionSchoolDefaults] Fee provisioning failed for ${schoolId}:`,
      err
    )
  )

  // Dispatch setup guide notifications to the admin
  await dispatchSetupGuideNotifications(
    schoolId,
    userId,
    school.preferredLanguage || "ar"
  ).catch((err) => {
    console.error(
      `[provisionSchoolDefaults] Setup guide notifications failed for ${schoolId}:`,
      err
    )
  })

  console.log(
    `[provisionSchoolDefaults] All provisioning complete for school ${schoolId}`
  )
}

export async function getSchoolOnboardingStatus(
  schoolId: string
): Promise<ActionResponse> {
  try {
    await requireSchoolOwnership(schoolId)

    const school = await db.school.findUnique({
      where: { id: schoolId },
      select: {
        id: true,
        name: true,
        domain: true,
        isActive: true,
        isPublished: true,
        onboardingCompletedAt: true,
      },
    })

    if (!school) throw new Error("School not found")

    return createActionResponse({
      isCompleted: !!school.onboardingCompletedAt,
      isActive: school.isActive,
      isPublished: school.isPublished,
      domain: school.domain,
      name: school.name,
    })
  } catch (error) {
    return createActionResponse(undefined, error)
  }
}
