-- Backfill (idempotent, fills NULLs only — never overwrites). Run branch-first,
-- then on main with approval, AFTER migration 20261004190000_fee_grade.
--
-- A fee structure charges a grade. Auto-generated structures already carry
-- it in sourceSignals.gradeId; admin structures linked to a class take that
-- class's grade. Structures with neither stay school-wide.

UPDATE "FeeStructure" AS f
SET "gradeId" = f."sourceSignals"->>'gradeId'
WHERE f."gradeId" IS NULL
  AND f."isAutoGenerated" = true
  AND f."sourceSignals"->>'gradeId' IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM "academic_grades" AS g
    WHERE g."id" = f."sourceSignals"->>'gradeId'
      AND g."schoolId" = f."schoolId"
  );

UPDATE "FeeStructure" AS f
SET "gradeId" = c."gradeId"
FROM "classes" AS c
WHERE f."classId" = c."id"
  AND f."schoolId" = c."schoolId"
  AND f."gradeId" IS NULL
  AND c."gradeId" IS NOT NULL;

-- Check: class-linked structures left without a grade (their class had none).
-- SELECT count(*) FROM "FeeStructure" WHERE "classId" IS NOT NULL AND "gradeId" IS NULL;
