/**
 * Theme Presets
 *
 * Collection of beautiful pre-configured themes.
 * Each theme includes light and dark mode variants in flat structure.
 * Following tweakcn pattern with HEX colors for presets.
 */

import type { ThemePreset } from '@/types/theme-editor'
import {
  DEFAULT_FONT_SANS,
  DEFAULT_FONT_SERIF,
  DEFAULT_FONT_MONO,
} from './config'

// Legacy preset interface for backwards compatibility with actions.ts
export interface LegacyThemePreset {
  id: string
  name: string
  description: string
  config: {
    name: string
    light: any
    dark: any
  }
}

// Built-in presets in new flat structure
export const builtInPresets: ThemePreset[] = [
  {
    label: 'Modern Minimal',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#ffffff',
        foreground: '#333333',
        card: '#ffffff',
        'card-foreground': '#333333',
        popover: '#ffffff',
        'popover-foreground': '#333333',
        primary: '#3b82f6',
        'primary-foreground': '#ffffff',
        secondary: '#f3f4f6',
        'secondary-foreground': '#4b5563',
        muted: '#f9fafb',
        'muted-foreground': '#6b7280',
        accent: '#e0f2fe',
        'accent-foreground': '#1e3a8a',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#e5e7eb',
        input: '#e5e7eb',
        ring: '#3b82f6',
        'chart-1': '#3b82f6',
        'chart-2': '#2563eb',
        'chart-3': '#1d4ed8',
        'chart-4': '#1e40af',
        'chart-5': '#1e3a8a',
        radius: '0.375rem',
        sidebar: '#f9fafb',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#3b82f6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#e0f2fe',
        'sidebar-accent-foreground': '#1e3a8a',
        'sidebar-border': '#e5e7eb',
        'sidebar-ring': '#3b82f6',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
      },
      dark: {
        background: '#171717',
        foreground: '#e5e5e5',
        card: '#262626',
        'card-foreground': '#e5e5e5',
        popover: '#262626',
        'popover-foreground': '#e5e5e5',
        primary: '#3b82f6',
        'primary-foreground': '#ffffff',
        secondary: '#262626',
        'secondary-foreground': '#e5e5e5',
        muted: '#1f1f1f',
        'muted-foreground': '#a3a3a3',
        accent: '#1e3a8a',
        'accent-foreground': '#bfdbfe',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#404040',
        input: '#404040',
        ring: '#3b82f6',
        'chart-1': '#60a5fa',
        'chart-2': '#3b82f6',
        'chart-3': '#2563eb',
        'chart-4': '#1d4ed8',
        'chart-5': '#1e40af',
        radius: '0.375rem',
        sidebar: '#171717',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#3b82f6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#1e3a8a',
        'sidebar-accent-foreground': '#bfdbfe',
        'sidebar-border': '#404040',
        'sidebar-ring': '#3b82f6',
      },
    },
  },

  {
    label: 'Violet Bloom',
    source: 'BUILT_IN',
    createdAt: '2025-06-26',
    styles: {
      light: {
        background: '#fdfdfd',
        foreground: '#000000',
        card: '#fdfdfd',
        'card-foreground': '#000000',
        popover: '#fcfcfc',
        'popover-foreground': '#000000',
        primary: '#7033ff',
        'primary-foreground': '#ffffff',
        secondary: '#edf0f4',
        'secondary-foreground': '#080808',
        muted: '#f5f5f5',
        'muted-foreground': '#525252',
        accent: '#e2ebff',
        'accent-foreground': '#1e69dc',
        destructive: '#e54b4f',
        'destructive-foreground': '#ffffff',
        border: '#e7e7ee',
        input: '#ebebeb',
        ring: '#000000',
        'chart-1': '#4ac885',
        'chart-2': '#7033ff',
        'chart-3': '#fd822b',
        'chart-4': '#3276e4',
        'chart-5': '#747474',
        sidebar: '#f5f8fb',
        'sidebar-foreground': '#000000',
        'sidebar-primary': '#000000',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#ebebeb',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#ebebeb',
        'sidebar-ring': '#000000',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '1.4rem',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.16',
        'shadow-blur': '3px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
        'letter-spacing': '-0.025em',
        spacing: '0.27rem',
      },
      dark: {
        background: '#1a1b1e',
        foreground: '#f0f0f0',
        card: '#222327',
        'card-foreground': '#f0f0f0',
        popover: '#222327',
        'popover-foreground': '#f0f0f0',
        primary: '#8c5cff',
        'primary-foreground': '#ffffff',
        secondary: '#2a2c33',
        'secondary-foreground': '#f0f0f0',
        muted: '#2a2c33',
        'muted-foreground': '#a0a0a0',
        accent: '#1e293b',
        'accent-foreground': '#79c0ff',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#33353a',
        input: '#33353a',
        ring: '#8c5cff',
        'chart-1': '#4ade80',
        'chart-2': '#8c5cff',
        'chart-3': '#fca5a5',
        'chart-4': '#5993f4',
        'chart-5': '#a0a0a0',
        sidebar: '#161618',
        'sidebar-foreground': '#f0f0f0',
        'sidebar-primary': '#8c5cff',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#2a2c33',
        'sidebar-accent-foreground': '#8c5cff',
        'sidebar-border': '#33353a',
        'sidebar-ring': '#8c5cff',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '1.4rem',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.16',
        'shadow-blur': '3px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
        'letter-spacing': '-0.025em',
        spacing: '0.27rem',
      },
    },
  },

  {
    label: 'T3 Chat',
    source: 'BUILT_IN',
    createdAt: '2025-04-19',
    styles: {
      light: {
        background: '#faf5fa',
        foreground: '#501854',
        card: '#faf5fa',
        'card-foreground': '#501854',
        popover: '#ffffff',
        'popover-foreground': '#501854',
        primary: '#a84370',
        'primary-foreground': '#ffffff',
        secondary: '#f1c4e6',
        'secondary-foreground': '#77347c',
        muted: '#f6e5f3',
        'muted-foreground': '#834588',
        accent: '#f1c4e6',
        'accent-foreground': '#77347c',
        destructive: '#d32f2f',
        'destructive-foreground': '#ffffff',
        border: '#e8b8e1',
        input: '#ffffff',
        ring: '#a84370',
        'chart-1': '#a84370',
        'chart-2': '#7b1fa2',
        'chart-3': '#ec407a',
        'chart-4': '#ab47bc',
        'chart-5': '#9c27b0',
        sidebar: '#f7ebf5',
        'sidebar-foreground': '#501854',
        'sidebar-primary': '#a84370',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#f1c4e6',
        'sidebar-accent-foreground': '#77347c',
        'sidebar-border': '#e8b8e1',
        'sidebar-ring': '#a84370',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.75rem',
      },
      dark: {
        background: '#1a0d1c',
        foreground: '#f3e5f5',
        card: '#2a1b2e',
        'card-foreground': '#f3e5f5',
        popover: '#2a1b2e',
        'popover-foreground': '#f3e5f5',
        primary: '#ce93d8',
        'primary-foreground': '#1a0d1c',
        secondary: '#4a2b52',
        'secondary-foreground': '#f3e5f5',
        muted: '#3a2744',
        'muted-foreground': '#ba68c8',
        accent: '#6a3a75',
        'accent-foreground': '#f3e5f5',
        destructive: '#ef5350',
        'destructive-foreground': '#ffffff',
        border: '#5a3a62',
        input: '#3a2744',
        ring: '#ce93d8',
        'chart-1': '#ce93d8',
        'chart-2': '#ab47bc',
        'chart-3': '#f48fb1',
        'chart-4': '#ba68c8',
        'chart-5': '#9c27b0',
        sidebar: '#110a14',
        'sidebar-foreground': '#f3e5f5',
        'sidebar-primary': '#ce93d8',
        'sidebar-primary-foreground': '#1a0d1c',
        'sidebar-accent': '#6a3a75',
        'sidebar-accent-foreground': '#f3e5f5',
        'sidebar-border': '#5a3a62',
        'sidebar-ring': '#ce93d8',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.75rem',
      },
    },
  },

  {
    label: 'Notebook',
    source: 'BUILT_IN',
    createdAt: '2025-05-10',
    styles: {
      light: {
        background: '#f9f9f9',
        foreground: '#3a3a3a',
        card: '#ffffff',
        'card-foreground': '#3a3a3a',
        popover: '#ffffff',
        'popover-foreground': '#3a3a3a',
        primary: '#606060',
        'primary-foreground': '#f0f0f0',
        secondary: '#dedede',
        'secondary-foreground': '#3a3a3a',
        muted: '#e3e3e3',
        'muted-foreground': '#505050',
        accent: '#f3eac8',
        'accent-foreground': '#5d4037',
        destructive: '#c87a7a',
        'destructive-foreground': '#ffffff',
        border: '#747272',
        input: '#ffffff',
        ring: '#a0a0a0',
        'chart-1': '#333333',
        'chart-2': '#555555',
        'chart-3': '#777777',
        'chart-4': '#999999',
        'chart-5': '#bbbbbb',
        sidebar: '#f0f0f0',
        'sidebar-foreground': '#3a3a3a',
        'sidebar-primary': '#606060',
        'sidebar-primary-foreground': '#f0f0f0',
        'sidebar-accent': '#f3eac8',
        'sidebar-accent-foreground': '#5d4037',
        'sidebar-border': '#c0c0c0',
        'sidebar-ring': '#a0a0a0',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.625rem',
        'shadow-color': '#000000',
        'shadow-opacity': '0.03',
        'shadow-blur': '5px',
        'shadow-spread': '0px',
        'shadow-offset-x': '1px',
        'shadow-offset-y': '4px',
        'letter-spacing': '0.5px',
        spacing: '0.25rem',
      },
      dark: {
        background: '#2b2b2b',
        foreground: '#dcdcdc',
        card: '#333333',
        'card-foreground': '#dcdcdc',
        popover: '#333333',
        'popover-foreground': '#dcdcdc',
        primary: '#b0b0b0',
        'primary-foreground': '#2b2b2b',
        secondary: '#5a5a5a',
        'secondary-foreground': '#c0c0c0',
        muted: '#454545',
        'muted-foreground': '#a0a0a0',
        accent: '#e0e0e0',
        'accent-foreground': '#333333',
        destructive: '#d9afaf',
        'destructive-foreground': '#2b2b2b',
        border: '#4f4f4f',
        input: '#333333',
        ring: '#c0c0c0',
        'chart-1': '#efefef',
        'chart-2': '#d0d0d0',
        'chart-3': '#b0b0b0',
        'chart-4': '#909090',
        'chart-5': '#707070',
        sidebar: '#212121',
        'sidebar-foreground': '#dcdcdc',
        'sidebar-primary': '#b0b0b0',
        'sidebar-primary-foreground': '#212121',
        'sidebar-accent': '#e0e0e0',
        'sidebar-accent-foreground': '#333333',
        'sidebar-border': '#4f4f4f',
        'sidebar-ring': '#c0c0c0',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.625rem',
        'shadow-color': '#000000',
        'shadow-opacity': '0.03',
        'shadow-blur': '5px',
        'shadow-spread': '0px',
        'shadow-offset-x': '1px',
        'shadow-offset-y': '4px',
        'letter-spacing': '0.5px',
        spacing: '0.25rem',
      },
    },
  },

  {
    label: 'Doom 64',
    source: 'BUILT_IN',
    createdAt: '2025-04-28',
    styles: {
      light: {
        background: '#cccccc',
        foreground: '#1f1f1f',
        card: '#b0b0b0',
        'card-foreground': '#1f1f1f',
        popover: '#b0b0b0',
        'popover-foreground': '#1f1f1f',
        primary: '#b71c1c',
        'primary-foreground': '#ffffff',
        secondary: '#556b2f',
        'secondary-foreground': '#ffffff',
        muted: '#b8b8b8',
        'muted-foreground': '#4a4a4a',
        accent: '#4682b4',
        'accent-foreground': '#ffffff',
        destructive: '#ff6f00',
        'destructive-foreground': '#000000',
        border: '#505050',
        input: '#505050',
        ring: '#b71c1c',
        'chart-1': '#b71c1c',
        'chart-2': '#556b2f',
        'chart-3': '#4682b4',
        'chart-4': '#ff6f00',
        'chart-5': '#8d6e63',
        sidebar: '#b0b0b0',
        'sidebar-foreground': '#1f1f1f',
        'sidebar-primary': '#b71c1c',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#4682b4',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#505050',
        'sidebar-ring': '#b71c1c',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0px',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.4',
        'shadow-blur': '4px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
        'letter-spacing': '0em',
        spacing: '0.25rem',
      },
      dark: {
        background: '#1a1a1a',
        foreground: '#e0e0e0',
        card: '#2a2a2a',
        'card-foreground': '#e0e0e0',
        popover: '#2a2a2a',
        'popover-foreground': '#e0e0e0',
        primary: '#e53935',
        'primary-foreground': '#ffffff',
        secondary: '#689f38',
        'secondary-foreground': '#000000',
        muted: '#252525',
        'muted-foreground': '#a0a0a0',
        accent: '#64b5f6',
        'accent-foreground': '#000000',
        destructive: '#ffa000',
        'destructive-foreground': '#000000',
        border: '#4a4a4a',
        input: '#4a4a4a',
        ring: '#e53935',
        'chart-1': '#e53935',
        'chart-2': '#689f38',
        'chart-3': '#64b5f6',
        'chart-4': '#ffa000',
        'chart-5': '#a1887f',
        sidebar: '#141414',
        'sidebar-foreground': '#e0e0e0',
        'sidebar-primary': '#e53935',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#64b5f6',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#4a4a4a',
        'sidebar-ring': '#e53935',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0px',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.6',
        'shadow-blur': '5px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
        'letter-spacing': '0em',
        spacing: '0.25rem',
      },
    },
  },

  {
    label: 'Ocean Blue',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#f0f9ff',
        foreground: '#0c4a6e',
        card: '#ffffff',
        'card-foreground': '#0c4a6e',
        popover: '#ffffff',
        'popover-foreground': '#0c4a6e',
        primary: '#0284c7',
        'primary-foreground': '#ffffff',
        secondary: '#e0f2fe',
        'secondary-foreground': '#075985',
        muted: '#f0f9ff',
        'muted-foreground': '#64748b',
        accent: '#bae6fd',
        'accent-foreground': '#0c4a6e',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#bae6fd',
        input: '#e0f2fe',
        ring: '#0284c7',
        'chart-1': '#0ea5e9',
        'chart-2': '#0284c7',
        'chart-3': '#0369a1',
        'chart-4': '#075985',
        'chart-5': '#0c4a6e',
        sidebar: '#f0f9ff',
        'sidebar-foreground': '#0c4a6e',
        'sidebar-primary': '#0284c7',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#bae6fd',
        'sidebar-accent-foreground': '#0c4a6e',
        'sidebar-border': '#bae6fd',
        'sidebar-ring': '#0284c7',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.5rem',
      },
      dark: {
        background: '#0c1821',
        foreground: '#e0f2fe',
        card: '#1e293b',
        'card-foreground': '#e0f2fe',
        popover: '#1e293b',
        'popover-foreground': '#e0f2fe',
        primary: '#38bdf8',
        'primary-foreground': '#0c1821',
        secondary: '#1e3a5f',
        'secondary-foreground': '#e0f2fe',
        muted: '#1e293b',
        'muted-foreground': '#94a3b8',
        accent: '#0c4a6e',
        'accent-foreground': '#bae6fd',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#1e3a5f',
        input: '#1e293b',
        ring: '#38bdf8',
        'chart-1': '#7dd3fc',
        'chart-2': '#38bdf8',
        'chart-3': '#0ea5e9',
        'chart-4': '#0284c7',
        'chart-5': '#0369a1',
        sidebar: '#0a1420',
        'sidebar-foreground': '#e0f2fe',
        'sidebar-primary': '#38bdf8',
        'sidebar-primary-foreground': '#0c1821',
        'sidebar-accent': '#0c4a6e',
        'sidebar-accent-foreground': '#bae6fd',
        'sidebar-border': '#1e3a5f',
        'sidebar-ring': '#38bdf8',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.5rem',
      },
    },
  },
]

// Legacy presets array for backwards compatibility
export const themePresets: LegacyThemePreset[] = builtInPresets.map((preset, index) => ({
  id: preset.label?.toLowerCase().replace(/\s+/g, '-') || `preset-${index}`,
  name: preset.label || 'Untitled',
  description: `Beautiful ${preset.label} theme`,
  config: {
    name: preset.label || 'Untitled',
    light: preset.styles.light,
    dark: preset.styles.dark,
  },
}))

// Helper to get preset by label
export function getPresetByLabel(label: string): ThemePreset | undefined {
  return builtInPresets.find((preset) => preset.label === label)
}

// Helper to get preset by ID (legacy)
export function getPresetById(id: string): LegacyThemePreset | undefined {
  return themePresets.find((preset) => preset.id === id)
}
