/**
 * Theme Presets
 *
 * Collection of 22 beautiful pre-configured themes from tweakcn.
 * Each theme includes light and dark mode variants in flat structure with HEX colors.
 */

import type { ThemePreset } from '@/types/theme-editor'
import {
  DEFAULT_FONT_SANS,
  DEFAULT_FONT_SERIF,
  DEFAULT_FONT_MONO,
} from './config'

// Legacy preset interface for backwards compatibility with actions.ts
export interface LegacyThemePreset {
  id: string
  name: string
  description: string
  config: {
    name: string
    light: any
    dark: any
  }
}

// Built-in presets from tweakcn in new flat structure
export const builtInPresets: ThemePreset[] = [
  {
    label: 'Modern Minimal',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#ffffff',
        foreground: '#333333',
        card: '#ffffff',
        'card-foreground': '#333333',
        popover: '#ffffff',
        'popover-foreground': '#333333',
        primary: '#3b82f6',
        'primary-foreground': '#ffffff',
        secondary: '#f3f4f6',
        'secondary-foreground': '#4b5563',
        muted: '#f9fafb',
        'muted-foreground': '#6b7280',
        accent: '#e0f2fe',
        'accent-foreground': '#1e3a8a',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#e5e7eb',
        input: '#e5e7eb',
        ring: '#3b82f6',
        'chart-1': '#3b82f6',
        'chart-2': '#2563eb',
        'chart-3': '#1d4ed8',
        'chart-4': '#1e40af',
        'chart-5': '#1e3a8a',
        radius: '0.375rem',
        sidebar: '#f9fafb',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#3b82f6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#e0f2fe',
        'sidebar-accent-foreground': '#1e3a8a',
        'sidebar-border': '#e5e7eb',
        'sidebar-ring': '#3b82f6',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
      },
      dark: {
        background: '#171717',
        foreground: '#e5e5e5',
        card: '#262626',
        'card-foreground': '#e5e5e5',
        popover: '#262626',
        'popover-foreground': '#e5e5e5',
        primary: '#3b82f6',
        'primary-foreground': '#ffffff',
        secondary: '#262626',
        'secondary-foreground': '#e5e5e5',
        muted: '#1f1f1f',
        'muted-foreground': '#a3a3a3',
        accent: '#1e3a8a',
        'accent-foreground': '#bfdbfe',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#404040',
        input: '#404040',
        ring: '#3b82f6',
        'chart-1': '#60a5fa',
        'chart-2': '#3b82f6',
        'chart-3': '#2563eb',
        'chart-4': '#1d4ed8',
        'chart-5': '#1e40af',
        radius: '0.375rem',
        sidebar: '#171717',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#3b82f6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#1e3a8a',
        'sidebar-accent-foreground': '#bfdbfe',
        'sidebar-border': '#404040',
        'sidebar-ring': '#3b82f6',
      },
    },
  },

  {
    label: 'Violet Bloom',
    source: 'BUILT_IN',
    createdAt: '2025-06-26',
    styles: {
      light: {
        background: '#fdfdfd',
        foreground: '#000000',
        card: '#fdfdfd',
        'card-foreground': '#000000',
        popover: '#fcfcfc',
        'popover-foreground': '#000000',
        primary: '#7033ff',
        'primary-foreground': '#ffffff',
        secondary: '#edf0f4',
        'secondary-foreground': '#080808',
        muted: '#f5f5f5',
        'muted-foreground': '#525252',
        accent: '#e2ebff',
        'accent-foreground': '#1e69dc',
        destructive: '#e54b4f',
        'destructive-foreground': '#ffffff',
        border: '#e7e7ee',
        input: '#ebebeb',
        ring: '#000000',
        'chart-1': '#4ac885',
        'chart-2': '#7033ff',
        'chart-3': '#fd822b',
        'chart-4': '#3276e4',
        'chart-5': '#747474',
        sidebar: '#f5f8fb',
        'sidebar-foreground': '#000000',
        'sidebar-primary': '#000000',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#ebebeb',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#ebebeb',
        'sidebar-ring': '#000000',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '1.4rem',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.16',
        'shadow-blur': '3px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
        'letter-spacing': '-0.025em',
        spacing: '0.27rem',
      },
      dark: {
        background: '#1a1b1e',
        foreground: '#f0f0f0',
        card: '#222327',
        'card-foreground': '#f0f0f0',
        popover: '#222327',
        'popover-foreground': '#f0f0f0',
        primary: '#8c5cff',
        'primary-foreground': '#ffffff',
        secondary: '#2a2c33',
        'secondary-foreground': '#f0f0f0',
        muted: '#2a2c33',
        'muted-foreground': '#a0a0a0',
        accent: '#1e293b',
        'accent-foreground': '#79c0ff',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#33353a',
        input: '#33353a',
        ring: '#8c5cff',
        'chart-1': '#4ade80',
        'chart-2': '#8c5cff',
        'chart-3': '#fca5a5',
        'chart-4': '#5993f4',
        'chart-5': '#a0a0a0',
        sidebar: '#161618',
        'sidebar-foreground': '#f0f0f0',
        'sidebar-primary': '#8c5cff',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#2a2c33',
        'sidebar-accent-foreground': '#8c5cff',
        'sidebar-border': '#33353a',
        'sidebar-ring': '#8c5cff',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '1.4rem',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.16',
        'shadow-blur': '3px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
        'letter-spacing': '-0.025em',
        spacing: '0.27rem',
      },
    },
  },

  {
    label: 'Mocha Mousse',
    source: 'BUILT_IN',
    createdAt: '2025-04-24',
    styles: {
      light: {
        background: '#F1F0E5',
        foreground: '#3d3c32',
        card: '#F1F0E5',
        'card-foreground': '#3d3c32',
        popover: '#ffffff',
        'popover-foreground': '#3d3c32',
        primary: '#A0826D',
        'primary-foreground': '#ffffff',
        secondary: '#E8E4D9',
        'secondary-foreground': '#5a5648',
        muted: '#E8E4D9',
        'muted-foreground': '#72715f',
        accent: '#D3C8B8',
        'accent-foreground': '#3d3c32',
        destructive: '#C85A54',
        'destructive-foreground': '#ffffff',
        border: '#C9C3B6',
        input: '#E8E4D9',
        ring: '#A0826D',
        'chart-1': '#A0826D',
        'chart-2': '#8B7355',
        'chart-3': '#C4A57B',
        'chart-4': '#E8D5C4',
        'chart-5': '#9D8B7A',
        sidebar: '#E8E4D9',
        'sidebar-foreground': '#3d3c32',
        'sidebar-primary': '#A0826D',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#D3C8B8',
        'sidebar-accent-foreground': '#3d3c32',
        'sidebar-border': '#C9C3B6',
        'sidebar-ring': '#A0826D',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.5rem',
      },
      dark: {
        background: '#1a1916',
        foreground: '#e8e4d9',
        card: '#252218',
        'card-foreground': '#e8e4d9',
        popover: '#252218',
        'popover-foreground': '#e8e4d9',
        primary: '#C4A57B',
        'primary-foreground': '#1a1916',
        secondary: '#3a352d',
        'secondary-foreground': '#e8e4d9',
        muted: '#2e2a22',
        'muted-foreground': '#a0937f',
        accent: '#4a4237',
        'accent-foreground': '#e8e4d9',
        destructive: '#D97066',
        'destructive-foreground': '#ffffff',
        border: '#3a352d',
        input: '#3a352d',
        ring: '#C4A57B',
        'chart-1': '#C4A57B',
        'chart-2': '#A0826D',
        'chart-3': '#E8D5C4',
        'chart-4': '#9D8B7A',
        'chart-5': '#8B7355',
        sidebar: '#161410',
        'sidebar-foreground': '#e8e4d9',
        'sidebar-primary': '#C4A57B',
        'sidebar-primary-foreground': '#1a1916',
        'sidebar-accent': '#4a4237',
        'sidebar-accent-foreground': '#e8e4d9',
        'sidebar-border': '#3a352d',
        'sidebar-ring': '#C4A57B',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.5rem',
      },
    },
  },

  {
    label: 'Amethyst Haze',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#f5f3f7',
        foreground: '#2e1a3d',
        card: '#ffffff',
        'card-foreground': '#2e1a3d',
        popover: '#ffffff',
        'popover-foreground': '#2e1a3d',
        primary: '#8b5cf6',
        'primary-foreground': '#ffffff',
        secondary: '#ede9f3',
        'secondary-foreground': '#4a2d5f',
        muted: '#f3eff7',
        'muted-foreground': '#6b4a7d',
        accent: '#ddd6fe',
        'accent-foreground': '#5b21b6',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#e9e3f0',
        input: '#ede9f3',
        ring: '#8b5cf6',
        'chart-1': '#8b5cf6',
        'chart-2': '#a78bfa',
        'chart-3': '#c4b5fd',
        'chart-4': '#ddd6fe',
        'chart-5': '#7c3aed',
        sidebar: '#f9f7fb',
        'sidebar-foreground': '#2e1a3d',
        'sidebar-primary': '#8b5cf6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#ddd6fe',
        'sidebar-accent-foreground': '#5b21b6',
        'sidebar-border': '#e9e3f0',
        'sidebar-ring': '#8b5cf6',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.75rem',
      },
      dark: {
        background: '#1a0f26',
        foreground: '#e9e3f0',
        card: '#251735',
        'card-foreground': '#e9e3f0',
        popover: '#251735',
        'popover-foreground': '#e9e3f0',
        primary: '#a78bfa',
        'primary-foreground': '#1a0f26',
        secondary: '#3a2650',
        'secondary-foreground': '#e9e3f0',
        muted: '#2a1a3d',
        'muted-foreground': '#a995c9',
        accent: '#4c3766',
        'accent-foreground': '#e9e3f0',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#3a2650',
        input: '#3a2650',
        ring: '#a78bfa',
        'chart-1': '#a78bfa',
        'chart-2': '#8b5cf6',
        'chart-3': '#c4b5fd',
        'chart-4': '#ddd6fe',
        'chart-5': '#7c3aed',
        sidebar: '#140a1f',
        'sidebar-foreground': '#e9e3f0',
        'sidebar-primary': '#a78bfa',
        'sidebar-primary-foreground': '#1a0f26',
        'sidebar-accent': '#4c3766',
        'sidebar-accent-foreground': '#e9e3f0',
        'sidebar-border': '#2a273a',
        'sidebar-ring': '#a995c9',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.75rem',
      },
    },
  },

  {
    label: 'Kodama Grove',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#e4d7b0',
        foreground: '#5c4b3e',
        card: '#e7dbbf',
        'card-foreground': '#5c4b3e',
        popover: '#f3ead2',
        'popover-foreground': '#5c4b3e',
        primary: '#8d9d4f',
        'primary-foreground': '#fdfbf6',
        secondary: '#decea0',
        'secondary-foreground': '#5c4b3e',
        muted: '#decea0',
        'muted-foreground': '#85766a',
        accent: '#dbc894',
        'accent-foreground': '#5c4b3e',
        destructive: '#d98b7e',
        'destructive-foreground': '#faf8f2',
        border: '#b19681',
        input: '#dbc894',
        ring: '#9db18c',
        'chart-1': '#9db18c',
        'chart-2': '#8a9f7b',
        'chart-3': '#bac9b4',
        'chart-4': '#71856a',
        'chart-5': '#5e6e58',
        sidebar: '#e2d1a2',
        'sidebar-foreground': '#5c4b3e',
        'sidebar-primary': '#8d9d4f',
        'sidebar-primary-foreground': '#fdfbf6',
        'sidebar-accent': '#dbc894',
        'sidebar-accent-foreground': '#5c4b3e',
        'sidebar-border': '#b19681',
        'sidebar-ring': '#9db18c',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.5rem',
      },
      dark: {
        background: '#2a2820',
        foreground: '#dfd8c8',
        card: '#353128',
        'card-foreground': '#dfd8c8',
        popover: '#353128',
        'popover-foreground': '#dfd8c8',
        primary: '#a3b66d',
        'primary-foreground': '#2a2820',
        secondary: '#4a4438',
        'secondary-foreground': '#dfd8c8',
        muted: '#3d3a2f',
        'muted-foreground': '#9d9482',
        accent: '#54502e',
        'accent-foreground': '#dfd8c8',
        destructive: '#e69f91',
        'destructive-foreground': '#2a2820',
        border: '#4a4438',
        input: '#4a4438',
        ring: '#a3b66d',
        'chart-1': '#a3b66d',
        'chart-2': '#8a9f7b',
        'chart-3': '#bac9b4',
        'chart-4': '#71856a',
        'chart-5': '#5e6e58',
        sidebar: '#221f18',
        'sidebar-foreground': '#dfd8c8',
        'sidebar-primary': '#a3b66d',
        'sidebar-primary-foreground': '#2a2820',
        'sidebar-accent': '#54502e',
        'sidebar-accent-foreground': '#dfd8c8',
        'sidebar-border': '#4a4438',
        'sidebar-ring': '#a3b66d',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.5rem',
      },
    },
  },

  {
    label: 'Cosmic Night',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#f7f8fc',
        foreground: '#1e1b4b',
        card: '#ffffff',
        'card-foreground': '#1e1b4b',
        popover: '#ffffff',
        'popover-foreground': '#1e1b4b',
        primary: '#4f46e5',
        'primary-foreground': '#ffffff',
        secondary: '#eef2ff',
        'secondary-foreground': '#312e81',
        muted: '#f5f7fb',
        'muted-foreground': '#64748b',
        accent: '#ddd6fe',
        'accent-foreground': '#4c1d95',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#e0e7ff',
        input: '#eef2ff',
        ring: '#4f46e5',
        'chart-1': '#4f46e5',
        'chart-2': '#6366f1',
        'chart-3': '#818cf8',
        'chart-4': '#a5b4fc',
        'chart-5': '#c7d2fe',
        sidebar: '#f5f7fb',
        'sidebar-foreground': '#1e1b4b',
        'sidebar-primary': '#4f46e5',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#ddd6fe',
        'sidebar-accent-foreground': '#4c1d95',
        'sidebar-border': '#e0e7ff',
        'sidebar-ring': '#4f46e5',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.625rem',
      },
      dark: {
        background: '#0f172a',
        foreground: '#e0e7ff',
        card: '#1e293b',
        'card-foreground': '#e0e7ff',
        popover: '#1e293b',
        'popover-foreground': '#e0e7ff',
        primary: '#818cf8',
        'primary-foreground': '#0f172a',
        secondary: '#334155',
        'secondary-foreground': '#e0e7ff',
        muted: '#1e293b',
        'muted-foreground': '#94a3b8',
        accent: '#4c1d95',
        'accent-foreground': '#ddd6fe',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#334155',
        input: '#334155',
        ring: '#818cf8',
        'chart-1': '#818cf8',
        'chart-2': '#6366f1',
        'chart-3': '#a5b4fc',
        'chart-4': '#c7d2fe',
        'chart-5': '#4f46e5',
        sidebar: '#0a0f1e',
        'sidebar-foreground': '#e0e7ff',
        'sidebar-primary': '#818cf8',
        'sidebar-primary-foreground': '#0f172a',
        'sidebar-accent': '#4c1d95',
        'sidebar-accent-foreground': '#ddd6fe',
        'sidebar-border': '#334155',
        'sidebar-ring': '#818cf8',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.625rem',
      },
    },
  },

  {
    label: 'Neo Brutalism',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#fafafa',
        foreground: '#000000',
        card: '#ffffff',
        'card-foreground': '#000000',
        popover: '#ffffff',
        'popover-foreground': '#000000',
        primary: '#000000',
        'primary-foreground': '#ffffff',
        secondary: '#f4f4f5',
        'secondary-foreground': '#000000',
        muted: '#f4f4f5',
        'muted-foreground': '#71717a',
        accent: '#fbbf24',
        'accent-foreground': '#000000',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#000000',
        input: '#ffffff',
        ring: '#000000',
        'chart-1': '#000000',
        'chart-2': '#fbbf24',
        'chart-3': '#ef4444',
        'chart-4': '#3b82f6',
        'chart-5': '#8b5cf6',
        sidebar: '#fafafa',
        'sidebar-foreground': '#000000',
        'sidebar-primary': '#000000',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#fbbf24',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#000000',
        'sidebar-ring': '#000000',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0px',
        'shadow-color': '#000000',
        'shadow-opacity': '1',
        'shadow-blur': '0px',
        'shadow-spread': '0px',
        'shadow-offset-x': '4px',
        'shadow-offset-y': '4px',
      },
      dark: {
        background: '#0a0a0a',
        foreground: '#ffffff',
        card: '#171717',
        'card-foreground': '#ffffff',
        popover: '#171717',
        'popover-foreground': '#ffffff',
        primary: '#ffffff',
        'primary-foreground': '#000000',
        secondary: '#27272a',
        'secondary-foreground': '#ffffff',
        muted: '#27272a',
        'muted-foreground': '#a1a1aa',
        accent: '#fbbf24',
        'accent-foreground': '#000000',
        destructive: '#f87171',
        'destructive-foreground': '#000000',
        border: '#ffffff',
        input: '#171717',
        ring: '#ffffff',
        'chart-1': '#ffffff',
        'chart-2': '#fbbf24',
        'chart-3': '#f87171',
        'chart-4': '#60a5fa',
        'chart-5': '#a78bfa',
        sidebar: '#0a0a0a',
        'sidebar-foreground': '#ffffff',
        'sidebar-primary': '#ffffff',
        'sidebar-primary-foreground': '#000000',
        'sidebar-accent': '#fbbf24',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#ffffff',
        'sidebar-ring': '#ffffff',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0px',
        'shadow-color': '#ffffff',
        'shadow-opacity': '1',
        'shadow-blur': '0px',
        'shadow-spread': '0px',
        'shadow-offset-x': '4px',
        'shadow-offset-y': '4px',
      },
    },
  },

  {
    label: 'Ocean Breeze',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#f0f9ff',
        foreground: '#0c4a6e',
        card: '#ffffff',
        'card-foreground': '#0c4a6e',
        popover: '#ffffff',
        'popover-foreground': '#0c4a6e',
        primary: '#0284c7',
        'primary-foreground': '#ffffff',
        secondary: '#e0f2fe',
        'secondary-foreground': '#075985',
        muted: '#f0f9ff',
        'muted-foreground': '#64748b',
        accent: '#bae6fd',
        'accent-foreground': '#0c4a6e',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#bae6fd',
        input: '#e0f2fe',
        ring: '#0284c7',
        'chart-1': '#0ea5e9',
        'chart-2': '#0284c7',
        'chart-3': '#0369a1',
        'chart-4': '#075985',
        'chart-5': '#0c4a6e',
        sidebar: '#f0f9ff',
        'sidebar-foreground': '#0c4a6e',
        'sidebar-primary': '#0284c7',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#bae6fd',
        'sidebar-accent-foreground': '#0c4a6e',
        'sidebar-border': '#bae6fd',
        'sidebar-ring': '#0284c7',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.5rem',
      },
      dark: {
        background: '#0c1821',
        foreground: '#e0f2fe',
        card: '#1e293b',
        'card-foreground': '#e0f2fe',
        popover: '#1e293b',
        'popover-foreground': '#e0f2fe',
        primary: '#38bdf8',
        'primary-foreground': '#0c1821',
        secondary: '#1e3a5f',
        'secondary-foreground': '#e0f2fe',
        muted: '#1e293b',
        'muted-foreground': '#94a3b8',
        accent: '#0c4a6e',
        'accent-foreground': '#bae6fd',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#1e3a5f',
        input: '#1e293b',
        ring: '#38bdf8',
        'chart-1': '#7dd3fc',
        'chart-2': '#38bdf8',
        'chart-3': '#0ea5e9',
        'chart-4': '#0284c7',
        'chart-5': '#0369a1',
        sidebar: '#0a1420',
        'sidebar-foreground': '#e0f2fe',
        'sidebar-primary': '#38bdf8',
        'sidebar-primary-foreground': '#0c1821',
        'sidebar-accent': '#0c4a6e',
        'sidebar-accent-foreground': '#bae6fd',
        'sidebar-border': '#1e3a5f',
        'sidebar-ring': '#38bdf8',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.5rem',
      },
    },
  },

  {
    label: 'Sunset Horizon',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#fff7ed',
        foreground: '#7c2d12',
        card: '#ffffff',
        'card-foreground': '#7c2d12',
        popover: '#ffffff',
        'popover-foreground': '#7c2d12',
        primary: '#ea580c',
        'primary-foreground': '#ffffff',
        secondary: '#ffedd5',
        'secondary-foreground': '#9a3412',
        muted: '#fed7aa',
        'muted-foreground': '#9a3412',
        accent: '#fef3c7',
        'accent-foreground': '#78350f',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#fed7aa',
        input: '#ffedd5',
        ring: '#ea580c',
        'chart-1': '#ea580c',
        'chart-2': '#f97316',
        'chart-3': '#fb923c',
        'chart-4': '#fdba74',
        'chart-5': '#fed7aa',
        sidebar: '#fff7ed',
        'sidebar-foreground': '#7c2d12',
        'sidebar-primary': '#ea580c',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#fef3c7',
        'sidebar-accent-foreground': '#78350f',
        'sidebar-border': '#fed7aa',
        'sidebar-ring': '#ea580c',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.75rem',
      },
      dark: {
        background: '#1c0a05',
        foreground: '#ffedd5',
        card: '#2d1509',
        'card-foreground': '#ffedd5',
        popover: '#2d1509',
        'popover-foreground': '#ffedd5',
        primary: '#fb923c',
        'primary-foreground': '#1c0a05',
        secondary: '#431407',
        'secondary-foreground': '#ffedd5',
        muted: '#3a1506',
        'muted-foreground': '#fdba74',
        accent: '#78350f',
        'accent-foreground': '#fed7aa',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#431407',
        input: '#431407',
        ring: '#fb923c',
        'chart-1': '#fb923c',
        'chart-2': '#f97316',
        'chart-3': '#fdba74',
        'chart-4': '#fed7aa',
        'chart-5': '#ea580c',
        sidebar: '#150702',
        'sidebar-foreground': '#ffedd5',
        'sidebar-primary': '#fb923c',
        'sidebar-primary-foreground': '#1c0a05',
        'sidebar-accent': '#78350f',
        'sidebar-accent-foreground': '#fed7aa',
        'sidebar-border': '#431407',
        'sidebar-ring': '#fb923c',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.75rem',
      },
    },
  },

  {
    label: 'Pastel Dreams',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#fef6fb',
        foreground: '#4a044e',
        card: '#ffffff',
        'card-foreground': '#4a044e',
        popover: '#ffffff',
        'popover-foreground': '#4a044e',
        primary: '#d946ef',
        'primary-foreground': '#ffffff',
        secondary: '#fae8ff',
        'secondary-foreground': '#701a75',
        muted: '#f5d0fe',
        'muted-foreground': '#86198f',
        accent: '#fef08a',
        'accent-foreground': '#713f12',
        destructive: '#f43f5e',
        'destructive-foreground': '#ffffff',
        border: '#f5d0fe',
        input: '#fae8ff',
        ring: '#d946ef',
        'chart-1': '#d946ef',
        'chart-2': '#e879f9',
        'chart-3': '#f0abfc',
        'chart-4': '#f5d0fe',
        'chart-5': '#fae8ff',
        sidebar: '#fef6fb',
        'sidebar-foreground': '#4a044e',
        'sidebar-primary': '#d946ef',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#fef08a',
        'sidebar-accent-foreground': '#713f12',
        'sidebar-border': '#f5d0fe',
        'sidebar-ring': '#d946ef',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '1rem',
      },
      dark: {
        background: '#1a0720',
        foreground: '#fae8ff',
        card: '#2d0a38',
        'card-foreground': '#fae8ff',
        popover: '#2d0a38',
        'popover-foreground': '#fae8ff',
        primary: '#e879f9',
        'primary-foreground': '#1a0720',
        secondary: '#4a044e',
        'secondary-foreground': '#fae8ff',
        muted: '#3b0a46',
        'muted-foreground': '#f0abfc',
        accent: '#fbbf24',
        'accent-foreground': '#0a0a0a',
        destructive: '#fb7185',
        'destructive-foreground': '#ffffff',
        border: '#4a044e',
        input: '#4a044e',
        ring: '#e879f9',
        'chart-1': '#e879f9',
        'chart-2': '#d946ef',
        'chart-3': '#f0abfc',
        'chart-4': '#f5d0fe',
        'chart-5': '#c026d3',
        sidebar: '#120415',
        'sidebar-foreground': '#fae8ff',
        'sidebar-primary': '#e879f9',
        'sidebar-primary-foreground': '#1a0720',
        'sidebar-accent': '#fbbf24',
        'sidebar-accent-foreground': '#0a0a0a',
        'sidebar-border': '#4a044e',
        'sidebar-ring': '#e879f9',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '1rem',
      },
    },
  },

  {
    label: 'Retro Arcade',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#fef3c7',
        foreground: '#1e1b4b',
        card: '#fffbeb',
        'card-foreground': '#1e1b4b',
        popover: '#fffbeb',
        'popover-foreground': '#1e1b4b',
        primary: '#7c3aed',
        'primary-foreground': '#ffffff',
        secondary: '#fde68a',
        'secondary-foreground': '#78350f',
        muted: '#fef3c7',
        'muted-foreground': '#713f12',
        accent: '#f87171',
        'accent-foreground': '#ffffff',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#fbbf24',
        input: '#fde68a',
        ring: '#7c3aed',
        'chart-1': '#7c3aed',
        'chart-2': '#f87171',
        'chart-3': '#fbbf24',
        'chart-4': '#3b82f6',
        'chart-5': '#10b981',
        sidebar: '#fef3c7',
        'sidebar-foreground': '#1e1b4b',
        'sidebar-primary': '#7c3aed',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#f87171',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#fbbf24',
        'sidebar-ring': '#7c3aed',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.125rem',
      },
      dark: {
        background: '#0a0a0a',
        foreground: '#fef3c7',
        card: '#1a1a1a',
        'card-foreground': '#fef3c7',
        popover: '#1a1a1a',
        'popover-foreground': '#fef3c7',
        primary: '#a78bfa',
        'primary-foreground': '#0a0a0a',
        secondary: '#fbbf24',
        'secondary-foreground': '#0a0a0a',
        muted: '#262626',
        'muted-foreground': '#fde68a',
        accent: '#fb7185',
        'accent-foreground': '#0a0a0a',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#fbbf24',
        input: '#262626',
        ring: '#a78bfa',
        'chart-1': '#a78bfa',
        'chart-2': '#fb7185',
        'chart-3': '#fbbf24',
        'chart-4': '#60a5fa',
        'chart-5': '#34d399',
        sidebar: '#0a0a0a',
        'sidebar-foreground': '#fef3c7',
        'sidebar-primary': '#a78bfa',
        'sidebar-primary-foreground': '#0a0a0a',
        'sidebar-accent': '#fb7185',
        'sidebar-accent-foreground': '#0a0a0a',
        'sidebar-border': '#fbbf24',
        'sidebar-ring': '#a78bfa',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.125rem',
      },
    },
  },

  {
    label: 'Midnight Bloom',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#fdf4ff',
        foreground: '#3b0764',
        card: '#ffffff',
        'card-foreground': '#3b0764',
        popover: '#ffffff',
        'popover-foreground': '#3b0764',
        primary: '#a21caf',
        'primary-foreground': '#ffffff',
        secondary: '#f3e8ff',
        'secondary-foreground': '#581c87',
        muted: '#fae8ff',
        'muted-foreground': '#701a75',
        accent: '#fbcfe8',
        'accent-foreground': '#831843',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#f0abfc',
        input: '#f3e8ff',
        ring: '#a21caf',
        'chart-1': '#a21caf',
        'chart-2': '#c026d3',
        'chart-3': '#d946ef',
        'chart-4': '#e879f9',
        'chart-5': '#f0abfc',
        sidebar: '#fdf4ff',
        'sidebar-foreground': '#3b0764',
        'sidebar-primary': '#a21caf',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#fbcfe8',
        'sidebar-accent-foreground': '#831843',
        'sidebar-border': '#f0abfc',
        'sidebar-ring': '#a21caf',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.875rem',
      },
      dark: {
        background: '#0f0515',
        foreground: '#fae8ff',
        card: '#1e0a27',
        'card-foreground': '#fae8ff',
        popover: '#1e0a27',
        'popover-foreground': '#fae8ff',
        primary: '#d946ef',
        'primary-foreground': '#0f0515',
        secondary: '#3b0764',
        'secondary-foreground': '#fae8ff',
        muted: '#2d0a3a',
        'muted-foreground': '#e879f9',
        accent: '#9f1239',
        'accent-foreground': '#fbcfe8',
        destructive: '#f43f5e',
        'destructive-foreground': '#ffffff',
        border: '#3b0764',
        input: '#3b0764',
        ring: '#d946ef',
        'chart-1': '#d946ef',
        'chart-2': '#c026d3',
        'chart-3': '#e879f9',
        'chart-4': '#f0abfc',
        'chart-5': '#a21caf',
        sidebar: '#0a0312',
        'sidebar-foreground': '#fae8ff',
        'sidebar-primary': '#d946ef',
        'sidebar-primary-foreground': '#0f0515',
        'sidebar-accent': '#9f1239',
        'sidebar-accent-foreground': '#fbcfe8',
        'sidebar-border': '#3b0764',
        'sidebar-ring': '#d946ef',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.875rem',
      },
    },
  },

  {
    label: 'Northern Lights',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#ecfdf5',
        foreground: '#064e3b',
        card: '#ffffff',
        'card-foreground': '#064e3b',
        popover: '#ffffff',
        'popover-foreground': '#064e3b',
        primary: '#059669',
        'primary-foreground': '#ffffff',
        secondary: '#d1fae5',
        'secondary-foreground': '#065f46',
        muted: '#ecfdf5',
        'muted-foreground': '#047857',
        accent: '#a7f3d0',
        'accent-foreground': '#064e3b',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#a7f3d0',
        input: '#d1fae5',
        ring: '#059669',
        'chart-1': '#059669',
        'chart-2': '#10b981',
        'chart-3': '#34d399',
        'chart-4': '#6ee7b7',
        'chart-5': '#a7f3d0',
        sidebar: '#ecfdf5',
        'sidebar-foreground': '#064e3b',
        'sidebar-primary': '#059669',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#a7f3d0',
        'sidebar-accent-foreground': '#064e3b',
        'sidebar-border': '#a7f3d0',
        'sidebar-ring': '#059669',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.5rem',
      },
      dark: {
        background: '#022c22',
        foreground: '#d1fae5',
        card: '#064e3b',
        'card-foreground': '#d1fae5',
        popover: '#064e3b',
        'popover-foreground': '#d1fae5',
        primary: '#34d399',
        'primary-foreground': '#022c22',
        secondary: '#065f46',
        'secondary-foreground': '#d1fae5',
        muted: '#064e3b',
        'muted-foreground': '#6ee7b7',
        accent: '#047857',
        'accent-foreground': '#a7f3d0',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#065f46',
        input: '#065f46',
        ring: '#34d399',
        'chart-1': '#34d399',
        'chart-2': '#10b981',
        'chart-3': '#6ee7b7',
        'chart-4': '#a7f3d0',
        'chart-5': '#059669',
        sidebar: '#011815',
        'sidebar-foreground': '#d1fae5',
        'sidebar-primary': '#34d399',
        'sidebar-primary-foreground': '#022c22',
        'sidebar-accent': '#047857',
        'sidebar-accent-foreground': '#a7f3d0',
        'sidebar-border': '#065f46',
        'sidebar-ring': '#34d399',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.5rem',
      },
    },
  },

  {
    label: 'Vintage Paper',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#fef9f3',
        foreground: '#44403c',
        card: '#fffbf7',
        'card-foreground': '#44403c',
        popover: '#fffbf7',
        'popover-foreground': '#44403c',
        primary: '#78716c',
        'primary-foreground': '#ffffff',
        secondary: '#f5f5f4',
        'secondary-foreground': '#57534e',
        muted: '#fafaf9',
        'muted-foreground': '#78716c',
        accent: '#fffbeb',
        'accent-foreground': '#78350f',
        destructive: '#b91c1c',
        'destructive-foreground': '#ffffff',
        border: '#e7e5e4',
        input: '#f5f5f4',
        ring: '#78716c',
        'chart-1': '#78716c',
        'chart-2': '#57534e',
        'chart-3': '#a8a29e',
        'chart-4': '#d6d3d1',
        'chart-5': '#e7e5e4',
        sidebar: '#fef9f3',
        'sidebar-foreground': '#44403c',
        'sidebar-primary': '#78716c',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#fffbeb',
        'sidebar-accent-foreground': '#78350f',
        'sidebar-border': '#e7e5e4',
        'sidebar-ring': '#78716c',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.25rem',
      },
      dark: {
        background: '#1c1917',
        foreground: '#fafaf9',
        card: '#292524',
        'card-foreground': '#fafaf9',
        popover: '#292524',
        'popover-foreground': '#fafaf9',
        primary: '#a8a29e',
        'primary-foreground': '#1c1917',
        secondary: '#44403c',
        'secondary-foreground': '#fafaf9',
        muted: '#292524',
        'muted-foreground': '#a8a29e',
        accent: '#78350f',
        'accent-foreground': '#fef3c7',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#44403c',
        input: '#44403c',
        ring: '#a8a29e',
        'chart-1': '#a8a29e',
        'chart-2': '#78716c',
        'chart-3': '#d6d3d1',
        'chart-4': '#e7e5e4',
        'chart-5': '#57534e',
        sidebar: '#0c0a09',
        'sidebar-foreground': '#fafaf9',
        'sidebar-primary': '#a8a29e',
        'sidebar-primary-foreground': '#1c1917',
        'sidebar-accent': '#78350f',
        'sidebar-accent-foreground': '#fef3c7',
        'sidebar-border': '#44403c',
        'sidebar-ring': '#a8a29e',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.25rem',
      },
    },
  },

  {
    label: 'Starry Night',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#fafaf9',
        foreground: '#1e293b',
        card: '#ffffff',
        'card-foreground': '#1e293b',
        popover: '#ffffff',
        'popover-foreground': '#1e293b',
        primary: '#6366f1',
        'primary-foreground': '#ffffff',
        secondary: '#f1f5f9',
        'secondary-foreground': '#334155',
        muted: '#f8fafc',
        'muted-foreground': '#64748b',
        accent: '#fef9c3',
        'accent-foreground': '#713f12',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#e2e8f0',
        input: '#f1f5f9',
        ring: '#6366f1',
        'chart-1': '#6366f1',
        'chart-2': '#8b5cf6',
        'chart-3': '#a78bfa',
        'chart-4': '#c4b5fd',
        'chart-5': '#ede9fe',
        sidebar: '#fafaf9',
        'sidebar-foreground': '#1e293b',
        'sidebar-primary': '#6366f1',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#fef9c3',
        'sidebar-accent-foreground': '#713f12',
        'sidebar-border': '#e2e8f0',
        'sidebar-ring': '#6366f1',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.625rem',
      },
      dark: {
        background: '#020617',
        foreground: '#f8fafc',
        card: '#0f172a',
        'card-foreground': '#f8fafc',
        popover: '#0f172a',
        'popover-foreground': '#f8fafc',
        primary: '#818cf8',
        'primary-foreground': '#020617',
        secondary: '#1e293b',
        'secondary-foreground': '#f8fafc',
        muted: '#0f172a',
        'muted-foreground': '#94a3b8',
        accent: '#fbbf24',
        'accent-foreground': '#0a0a0a',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#1e293b',
        input: '#1e293b',
        ring: '#818cf8',
        'chart-1': '#818cf8',
        'chart-2': '#a78bfa',
        'chart-3': '#c4b5fd',
        'chart-4': '#ddd6fe',
        'chart-5': '#6366f1',
        sidebar: '#000000',
        'sidebar-foreground': '#f8fafc',
        'sidebar-primary': '#818cf8',
        'sidebar-primary-foreground': '#020617',
        'sidebar-accent': '#fbbf24',
        'sidebar-accent-foreground': '#0a0a0a',
        'sidebar-border': '#1e293b',
        'sidebar-ring': '#818cf8',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.625rem',
      },
    },
  },

  {
    label: 'Soft Pop',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#fefce8',
        foreground: '#422006',
        card: '#ffffff',
        'card-foreground': '#422006',
        popover: '#ffffff',
        'popover-foreground': '#422006',
        primary: '#f97316',
        'primary-foreground': '#ffffff',
        secondary: '#fef3c7',
        'secondary-foreground': '#78350f',
        muted: '#fef9c3',
        'muted-foreground': '#713f12',
        accent: '#ddd6fe',
        'accent-foreground': '#5b21b6',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#fde68a',
        input: '#fef3c7',
        ring: '#f97316',
        'chart-1': '#f97316',
        'chart-2': '#fb923c',
        'chart-3': '#fdba74',
        'chart-4': '#fcd34d',
        'chart-5': '#fde047',
        sidebar: '#fefce8',
        'sidebar-foreground': '#422006',
        'sidebar-primary': '#f97316',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#ddd6fe',
        'sidebar-accent-foreground': '#5b21b6',
        'sidebar-border': '#fde68a',
        'sidebar-ring': '#f97316',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '1.25rem',
      },
      dark: {
        background: '#1c1508',
        foreground: '#fef3c7',
        card: '#2d2008',
        'card-foreground': '#fef3c7',
        popover: '#2d2008',
        'popover-foreground': '#fef3c7',
        primary: '#fb923c',
        'primary-foreground': '#1c1508',
        secondary: '#422006',
        'secondary-foreground': '#fef3c7',
        muted: '#3a1e05',
        'muted-foreground': '#fde68a',
        accent: '#7c3aed',
        'accent-foreground': '#ddd6fe',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#422006',
        input: '#422006',
        ring: '#fb923c',
        'chart-1': '#fb923c',
        'chart-2': '#f97316',
        'chart-3': '#fdba74',
        'chart-4': '#fde047',
        'chart-5': '#fcd34d',
        sidebar: '#100b03',
        'sidebar-foreground': '#fef3c7',
        'sidebar-primary': '#fb923c',
        'sidebar-primary-foreground': '#1c1508',
        'sidebar-accent': '#7c3aed',
        'sidebar-accent-foreground': '#ddd6fe',
        'sidebar-border': '#422006',
        'sidebar-ring': '#fb923c',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '1.25rem',
      },
    },
  },

  {
    label: 'Clean Slate',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#f8f9fa',
        foreground: '#212529',
        card: '#ffffff',
        'card-foreground': '#212529',
        popover: '#ffffff',
        'popover-foreground': '#212529',
        primary: '#495057',
        'primary-foreground': '#ffffff',
        secondary: '#e9ecef',
        'secondary-foreground': '#495057',
        muted: '#f8f9fa',
        'muted-foreground': '#6c757d',
        accent: '#dee2e6',
        'accent-foreground': '#212529',
        destructive: '#dc3545',
        'destructive-foreground': '#ffffff',
        border: '#dee2e6',
        input: '#e9ecef',
        ring: '#495057',
        'chart-1': '#495057',
        'chart-2': '#6c757d',
        'chart-3': '#adb5bd',
        'chart-4': '#ced4da',
        'chart-5': '#dee2e6',
        sidebar: '#f8f9fa',
        'sidebar-foreground': '#212529',
        'sidebar-primary': '#495057',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#dee2e6',
        'sidebar-accent-foreground': '#212529',
        'sidebar-border': '#dee2e6',
        'sidebar-ring': '#495057',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.25rem',
      },
      dark: {
        background: '#212529',
        foreground: '#f8f9fa',
        card: '#343a40',
        'card-foreground': '#f8f9fa',
        popover: '#343a40',
        'popover-foreground': '#f8f9fa',
        primary: '#adb5bd',
        'primary-foreground': '#212529',
        secondary: '#495057',
        'secondary-foreground': '#f8f9fa',
        muted: '#343a40',
        'muted-foreground': '#adb5bd',
        accent: '#495057',
        'accent-foreground': '#f8f9fa',
        destructive: '#e74c3c',
        'destructive-foreground': '#ffffff',
        border: '#495057',
        input: '#495057',
        ring: '#adb5bd',
        'chart-1': '#adb5bd',
        'chart-2': '#6c757d',
        'chart-3': '#ced4da',
        'chart-4': '#dee2e6',
        'chart-5': '#495057',
        sidebar: '#1a1d20',
        'sidebar-foreground': '#f8f9fa',
        'sidebar-primary': '#adb5bd',
        'sidebar-primary-foreground': '#212529',
        'sidebar-accent': '#495057',
        'sidebar-accent-foreground': '#f8f9fa',
        'sidebar-border': '#495057',
        'sidebar-ring': '#adb5bd',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.25rem',
      },
    },
  },

  {
    label: 'Quantum Rose',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#fff1f2',
        foreground: '#881337',
        card: '#ffffff',
        'card-foreground': '#881337',
        popover: '#ffffff',
        'popover-foreground': '#881337',
        primary: '#e11d48',
        'primary-foreground': '#ffffff',
        secondary: '#ffe4e6',
        'secondary-foreground': '#9f1239',
        muted: '#fecdd3',
        'muted-foreground': '#9f1239',
        accent: '#fce7f3',
        'accent-foreground': '#831843',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#fecdd3',
        input: '#ffe4e6',
        ring: '#e11d48',
        'chart-1': '#e11d48',
        'chart-2': '#f43f5e',
        'chart-3': '#fb7185',
        'chart-4': '#fda4af',
        'chart-5': '#fecdd3',
        sidebar: '#fff1f2',
        'sidebar-foreground': '#881337',
        'sidebar-primary': '#e11d48',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#fce7f3',
        'sidebar-accent-foreground': '#831843',
        'sidebar-border': '#fecdd3',
        'sidebar-ring': '#e11d48',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.875rem',
      },
      dark: {
        background: '#1a0509',
        foreground: '#ffe4e6',
        card: '#2d0a11',
        'card-foreground': '#ffe4e6',
        popover: '#2d0a11',
        'popover-foreground': '#ffe4e6',
        primary: '#fb7185',
        'primary-foreground': '#1a0509',
        secondary: '#4c0519',
        'secondary-foreground': '#ffe4e6',
        muted: '#3a0812',
        'muted-foreground': '#fda4af',
        accent: '#701a75',
        'accent-foreground': '#fce7f3',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#4c0519',
        input: '#4c0519',
        ring: '#fb7185',
        'chart-1': '#fb7185',
        'chart-2': '#f43f5e',
        'chart-3': '#fda4af',
        'chart-4': '#fecdd3',
        'chart-5': '#e11d48',
        sidebar: '#120304',
        'sidebar-foreground': '#ffe4e6',
        'sidebar-primary': '#fb7185',
        'sidebar-primary-foreground': '#1a0509',
        'sidebar-accent': '#701a75',
        'sidebar-accent-foreground': '#fce7f3',
        'sidebar-border': '#4c0519',
        'sidebar-ring': '#fb7185',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.875rem',
      },
    },
  },

  {
    label: 'Bold Tech',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#f0fdf4',
        foreground: '#14532d',
        card: '#ffffff',
        'card-foreground': '#14532d',
        popover: '#ffffff',
        'popover-foreground': '#14532d',
        primary: '#16a34a',
        'primary-foreground': '#ffffff',
        secondary: '#dcfce7',
        'secondary-foreground': '#166534',
        muted: '#f0fdf4',
        'muted-foreground': '#15803d',
        accent: '#bbf7d0',
        'accent-foreground': '#14532d',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#bbf7d0',
        input: '#dcfce7',
        ring: '#16a34a',
        'chart-1': '#16a34a',
        'chart-2': '#22c55e',
        'chart-3': '#4ade80',
        'chart-4': '#86efac',
        'chart-5': '#bbf7d0',
        sidebar: '#f0fdf4',
        'sidebar-foreground': '#14532d',
        'sidebar-primary': '#16a34a',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#bbf7d0',
        'sidebar-accent-foreground': '#14532d',
        'sidebar-border': '#bbf7d0',
        'sidebar-ring': '#16a34a',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.375rem',
      },
      dark: {
        background: '#021607',
        foreground: '#dcfce7',
        card: '#052e16',
        'card-foreground': '#dcfce7',
        popover: '#052e16',
        'popover-foreground': '#dcfce7',
        primary: '#4ade80',
        'primary-foreground': '#021607',
        secondary: '#14532d',
        'secondary-foreground': '#dcfce7',
        muted: '#052e16',
        'muted-foreground': '#86efac',
        accent: '#166534',
        'accent-foreground': '#bbf7d0',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#14532d',
        input: '#14532d',
        ring: '#4ade80',
        'chart-1': '#4ade80',
        'chart-2': '#22c55e',
        'chart-3': '#86efac',
        'chart-4': '#bbf7d0',
        'chart-5': '#16a34a',
        sidebar: '#010a03',
        'sidebar-foreground': '#dcfce7',
        'sidebar-primary': '#4ade80',
        'sidebar-primary-foreground': '#021607',
        'sidebar-accent': '#166534',
        'sidebar-accent-foreground': '#bbf7d0',
        'sidebar-border': '#14532d',
        'sidebar-ring': '#4ade80',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.375rem',
      },
    },
  },

  {
    label: 'Elegant Luxury',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#fffbeb',
        foreground: '#78350f',
        card: '#ffffff',
        'card-foreground': '#78350f',
        popover: '#ffffff',
        'popover-foreground': '#78350f',
        primary: '#d97706',
        'primary-foreground': '#ffffff',
        secondary: '#fef3c7',
        'secondary-foreground': '#92400e',
        muted: '#fefce8',
        'muted-foreground': '#a16207',
        accent: '#fef08a',
        'accent-foreground': '#713f12',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#fde68a',
        input: '#fef3c7',
        ring: '#d97706',
        'chart-1': '#d97706',
        'chart-2': '#f59e0b',
        'chart-3': '#fbbf24',
        'chart-4': '#fcd34d',
        'chart-5': '#fde047',
        sidebar: '#fffbeb',
        'sidebar-foreground': '#78350f',
        'sidebar-primary': '#d97706',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#fef08a',
        'sidebar-accent-foreground': '#713f12',
        'sidebar-border': '#fde68a',
        'sidebar-ring': '#d97706',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.5rem',
      },
      dark: {
        background: '#1c1508',
        foreground: '#fef3c7',
        card: '#2d2008',
        'card-foreground': '#fef3c7',
        popover: '#2d2008',
        'popover-foreground': '#fef3c7',
        primary: '#fbbf24',
        'primary-foreground': '#1c1508',
        secondary: '#422006',
        'secondary-foreground': '#fef3c7',
        muted: '#3a1e05',
        'muted-foreground': '#fde68a',
        accent: '#854d0e',
        'accent-foreground': '#fef08a',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#422006',
        input: '#422006',
        ring: '#fbbf24',
        'chart-1': '#fbbf24',
        'chart-2': '#f59e0b',
        'chart-3': '#fcd34d',
        'chart-4': '#fde047',
        'chart-5': '#d97706',
        sidebar: '#100b03',
        'sidebar-foreground': '#fef3c7',
        'sidebar-primary': '#fbbf24',
        'sidebar-primary-foreground': '#1c1508',
        'sidebar-accent': '#854d0e',
        'sidebar-accent-foreground': '#fef08a',
        'sidebar-border': '#422006',
        'sidebar-ring': '#fbbf24',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.5rem',
      },
    },
  },

  {
    label: 'Amber Minimal',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#fffbeb',
        foreground: '#78350f',
        card: '#fef9ec',
        'card-foreground': '#78350f',
        popover: '#ffffff',
        'popover-foreground': '#78350f',
        primary: '#d97706',
        'primary-foreground': '#ffffff',
        secondary: '#fef3c7',
        'secondary-foreground': '#92400e',
        muted: '#fefce8',
        'muted-foreground': '#a16207',
        accent: '#fde68a',
        'accent-foreground': '#78350f',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#fde68a',
        input: '#fef3c7',
        ring: '#d97706',
        'chart-1': '#d97706',
        'chart-2': '#f59e0b',
        'chart-3': '#fbbf24',
        'chart-4': '#fcd34d',
        'chart-5': '#fef08a',
        sidebar: '#fffbeb',
        'sidebar-foreground': '#78350f',
        'sidebar-primary': '#d97706',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#fde68a',
        'sidebar-accent-foreground': '#78350f',
        'sidebar-border': '#fde68a',
        'sidebar-ring': '#d97706',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.375rem',
      },
      dark: {
        background: '#1c1508',
        foreground: '#fef3c7',
        card: '#2d2008',
        'card-foreground': '#fef3c7',
        popover: '#2d2008',
        'popover-foreground': '#fef3c7',
        primary: '#fbbf24',
        'primary-foreground': '#1c1508',
        secondary: '#422006',
        'secondary-foreground': '#fef3c7',
        muted: '#3a1e05',
        'muted-foreground': '#fde68a',
        accent: '#78350f',
        'accent-foreground': '#fde68a',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#422006',
        input: '#422006',
        ring: '#fbbf24',
        'chart-1': '#fbbf24',
        'chart-2': '#f59e0b',
        'chart-3': '#fcd34d',
        'chart-4': '#fef08a',
        'chart-5': '#d97706',
        sidebar: '#100b03',
        'sidebar-foreground': '#fef3c7',
        'sidebar-primary': '#fbbf24',
        'sidebar-primary-foreground': '#1c1508',
        'sidebar-accent': '#78350f',
        'sidebar-accent-foreground': '#fde68a',
        'sidebar-border': '#422006',
        'sidebar-ring': '#fbbf24',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.375rem',
      },
    },
  },

  {
    label: 'Solar Dusk',
    source: 'BUILT_IN',
    styles: {
      light: {
        background: '#fff7ed',
        foreground: '#7c2d12',
        card: '#fffaf5',
        'card-foreground': '#7c2d12',
        popover: '#ffffff',
        'popover-foreground': '#7c2d12',
        primary: '#ea580c',
        'primary-foreground': '#ffffff',
        secondary: '#ffedd5',
        'secondary-foreground': '#9a3412',
        muted: '#fed7aa',
        'muted-foreground': '#9a3412',
        accent: '#fef3c7',
        'accent-foreground': '#78350f',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        border: '#fed7aa',
        input: '#ffedd5',
        ring: '#ea580c',
        'chart-1': '#ea580c',
        'chart-2': '#f97316',
        'chart-3': '#fb923c',
        'chart-4': '#fdba74',
        'chart-5': '#fed7aa',
        sidebar: '#fff7ed',
        'sidebar-foreground': '#7c2d12',
        'sidebar-primary': '#ea580c',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#fef3c7',
        'sidebar-accent-foreground': '#78350f',
        'sidebar-border': '#fed7aa',
        'sidebar-ring': '#ea580c',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.75rem',
      },
      dark: {
        background: '#1c0a05',
        foreground: '#ffedd5',
        card: '#2d1509',
        'card-foreground': '#ffedd5',
        popover: '#2d1509',
        'popover-foreground': '#ffedd5',
        primary: '#fb923c',
        'primary-foreground': '#1c0a05',
        secondary: '#431407',
        'secondary-foreground': '#ffedd5',
        muted: '#3a1506',
        'muted-foreground': '#fdba74',
        accent: '#78350f',
        'accent-foreground': '#fed7aa',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#431407',
        input: '#431407',
        ring: '#fb923c',
        'chart-1': '#fb923c',
        'chart-2': '#f97316',
        'chart-3': '#fdba74',
        'chart-4': '#fed7aa',
        'chart-5': '#ea580c',
        sidebar: '#150702',
        'sidebar-foreground': '#ffedd5',
        'sidebar-primary': '#fb923c',
        'sidebar-primary-foreground': '#1c0a05',
        'sidebar-accent': '#78350f',
        'sidebar-accent-foreground': '#fed7aa',
        'sidebar-border': '#431407',
        'sidebar-ring': '#fb923c',
        'font-sans': DEFAULT_FONT_SANS,
        'font-serif': DEFAULT_FONT_SERIF,
        'font-mono': DEFAULT_FONT_MONO,
        radius: '0.75rem',
      },
    },
  },
]

// Legacy presets array for backwards compatibility
export const themePresets: LegacyThemePreset[] = builtInPresets.map((preset, index) => ({
  id: preset.label?.toLowerCase().replace(/\s+/g, '-') || `preset-${index}`,
  name: preset.label || 'Untitled',
  description: `Beautiful ${preset.label} theme`,
  config: {
    name: preset.label || 'Untitled',
    light: preset.styles.light,
    dark: preset.styles.dark,
  },
}))

// Helper to get preset by label
export function getPresetByLabel(label: string): ThemePreset | undefined {
  return builtInPresets.find((preset) => preset.label === label)
}

// Helper to get preset by ID (legacy)
export function getPresetById(id: string): LegacyThemePreset | undefined {
  return themePresets.find((preset) => preset.id === id)
}
