import {
  LayoutDashboard,
  Megaphone,
  Receipt,
  GraduationCap,
  Users,
  UserCheck,
  BookOpen,
  Calendar,
  CheckCircle,
  BarChart3,
  Clock,
  Video,
  Settings,
  User,
  FileText,
  ClipboardCheck,
  Plus,
  UserPlus,
  BookPlus,
} from "lucide-react";
import type { SearchConfig, Role } from "./types";

const ALL_ROLES: Role[] = [
  "DEVELOPER",
  "ADMIN",
  "TEACHER",
  "STUDENT",
  "GUARDIAN",
  "ACCOUNTANT",
  "STAFF",
  "USER",
];

export const platformSearchConfig: SearchConfig = {
  navigation: [
    // Admin Dashboard
    {
      id: "overview",
      title: "Overview",
      type: "navigation",
      href: "/dashboard",
      icon: LayoutDashboard,
      roles: ["ADMIN"],
      keywords: ["dashboard", "home", "main"],
      breadcrumb: ["Platform", "Dashboard"],
    },
    {
      id: "admin",
      title: "Admin",
      type: "navigation",
      href: "/lab/admin",
      icon: Settings,
      roles: ["ADMIN"],
      keywords: ["administration", "management"],
      breadcrumb: ["Platform", "Dashboard"],
    },
    {
      id: "billing",
      title: "Billing",
      type: "navigation",
      href: "/admin/billing",
      icon: Receipt,
      roles: ["ADMIN", "DEVELOPER"],
      keywords: ["payments", "subscription", "plan"],
      breadcrumb: ["Platform", "Admin"],
    },
    {
      id: "charts",
      title: "Charts",
      type: "navigation",
      href: "/dashboard/charts",
      icon: BarChart3,
      roles: ["ADMIN"],
      keywords: ["analytics", "statistics", "data"],
      breadcrumb: ["Platform", "Dashboard"],
    },
    {
      id: "lab-settings",
      title: "Settings",
      type: "navigation",
      href: "/lab/settings",
      icon: Settings,
      roles: ["ADMIN", "STAFF", "TEACHER", "STUDENT", "GUARDIAN", "ACCOUNTANT", "DEVELOPER"],
      keywords: ["preferences", "configuration"],
      breadcrumb: ["Platform", "Dashboard"],
    },

    // School Platform Features
    {
      id: "announcements",
      title: "Announcements",
      type: "navigation",
      href: "/announcements",
      icon: Megaphone,
      roles: ALL_ROLES,
      keywords: ["news", "notifications", "updates"],
      breadcrumb: ["Platform"],
    },
    {
      id: "invoices",
      title: "Invoices",
      type: "navigation",
      href: "/invoice",
      icon: Receipt,
      roles: ["ADMIN", "ACCOUNTANT"],
      keywords: ["billing", "payments", "finance"],
      breadcrumb: ["Platform"],
    },
    {
      id: "grades",
      title: "Grades",
      type: "navigation",
      href: "/grades",
      icon: FileText,
      roles: ["ADMIN", "STAFF", "TEACHER", "STUDENT", "GUARDIAN"],
      keywords: ["marks", "scores", "results", "assessment"],
      breadcrumb: ["Platform"],
    },
    {
      id: "subjects",
      title: "Subjects",
      type: "navigation",
      href: "/subjects",
      icon: BookOpen,
      roles: ["ADMIN", "STAFF", "TEACHER"],
      keywords: ["courses", "curriculum", "classes"],
      breadcrumb: ["Platform"],
    },
    {
      id: "parents",
      title: "Parents",
      type: "navigation",
      href: "/parents",
      icon: Users,
      roles: ["ADMIN", "STAFF"],
      keywords: ["guardians", "families"],
      breadcrumb: ["Platform"],
    },
    {
      id: "students",
      title: "Students",
      type: "navigation",
      href: "/students",
      icon: GraduationCap,
      roles: ["ADMIN", "STAFF", "TEACHER"],
      keywords: ["pupils", "learners", "enrollment"],
      breadcrumb: ["Platform"],
    },
    {
      id: "teachers",
      title: "Teachers",
      type: "navigation",
      href: "/teachers",
      icon: UserCheck,
      roles: ["ADMIN", "STAFF"],
      keywords: ["faculty", "staff", "instructors"],
      breadcrumb: ["Platform"],
    },
    {
      id: "classes",
      title: "Classes",
      type: "navigation",
      href: "/classes",
      icon: Users,
      roles: ["ADMIN", "STAFF", "TEACHER"],
      keywords: ["groups", "sections", "divisions"],
      breadcrumb: ["Platform"],
    },
    {
      id: "lessons",
      title: "Lessons",
      type: "navigation",
      href: "/lessons",
      icon: BookOpen,
      roles: ["ADMIN", "STAFF", "TEACHER"],
      keywords: ["curriculum", "teaching", "periods"],
      breadcrumb: ["Platform"],
    },
    {
      id: "exams",
      title: "Exams",
      type: "navigation",
      href: "/exams",
      icon: ClipboardCheck,
      roles: ["ADMIN", "STAFF", "TEACHER"],
      keywords: ["tests", "assessments", "evaluations"],
      breadcrumb: ["Platform"],
    },
    {
      id: "events",
      title: "Events",
      type: "navigation",
      href: "/events",
      icon: Calendar,
      roles: ["ADMIN", "STAFF", "TEACHER"],
      keywords: ["calendar", "activities", "schedule"],
      breadcrumb: ["Platform"],
    },
    {
      id: "attendance",
      title: "Attendance",
      type: "navigation",
      href: "/attendance",
      icon: CheckCircle,
      roles: ["ADMIN", "STAFF", "TEACHER"],
      keywords: ["presence", "absence", "roll call"],
      breadcrumb: ["Platform"],
    },
    {
      id: "reports",
      title: "Reports",
      type: "navigation",
      href: "/attendance/reports",
      icon: BarChart3,
      roles: ["ADMIN", "STAFF"],
      keywords: ["analytics", "statistics", "data"],
      breadcrumb: ["Platform", "Attendance"],
    },
    {
      id: "timetable",
      title: "Timetable",
      type: "navigation",
      href: "/timetable",
      icon: Clock,
      roles: ["ADMIN", "TEACHER", "STUDENT"],
      keywords: ["schedule", "calendar", "periods"],
      breadcrumb: ["Platform"],
    },
    {
      id: "library",
      title: "Library",
      type: "navigation",
      href: "/library",
      icon: BookOpen,
      roles: ALL_ROLES,
      keywords: ["books", "reading", "resources"],
      breadcrumb: ["Platform"],
    },
    {
      id: "stream",
      title: "Stream",
      type: "navigation",
      href: "/stream",
      icon: Video,
      roles: ALL_ROLES,
      keywords: ["videos", "live", "broadcasts"],
      breadcrumb: ["Platform"],
    },
    {
      id: "settings",
      title: "Settings",
      type: "navigation",
      href: "/settings",
      icon: Settings,
      roles: ["ADMIN"],
      keywords: ["configuration", "preferences", "admin"],
      breadcrumb: ["Platform"],
    },
    {
      id: "profile",
      title: "Profile",
      type: "navigation",
      href: "/profile",
      icon: User,
      roles: ALL_ROLES,
      keywords: ["account", "user", "personal"],
      breadcrumb: ["Platform"],
    },
  ],
  actions: [
    {
      id: "new-student",
      title: "New Student",
      type: "action",
      icon: UserPlus,
      href: "/students/new",
      roles: ["ADMIN", "STAFF"],
      keywords: ["create", "add", "enroll", "register"],
      description: "Register a new student",
    },
    {
      id: "new-teacher",
      title: "New Teacher",
      type: "action",
      icon: UserPlus,
      href: "/teachers/new",
      roles: ["ADMIN", "STAFF"],
      keywords: ["create", "add", "hire"],
      description: "Add a new teacher",
    },
    {
      id: "new-class",
      title: "New Class",
      type: "action",
      icon: Plus,
      href: "/classes/new",
      roles: ["ADMIN", "STAFF"],
      keywords: ["create", "add", "group"],
      description: "Create a new class",
    },
    {
      id: "new-subject",
      title: "New Subject",
      type: "action",
      icon: BookPlus,
      href: "/subjects/new",
      roles: ["ADMIN", "STAFF"],
      keywords: ["create", "add", "course"],
      description: "Add a new subject",
    },
    {
      id: "new-announcement",
      title: "New Announcement",
      type: "action",
      icon: Plus,
      href: "/announcements/new",
      roles: ["ADMIN", "STAFF", "TEACHER"],
      keywords: ["create", "add", "post", "notify"],
      description: "Create a new announcement",
    },
    {
      id: "new-exam",
      title: "New Exam",
      type: "action",
      icon: Plus,
      href: "/exams/new",
      roles: ["ADMIN", "STAFF", "TEACHER"],
      keywords: ["create", "add", "test", "assessment"],
      description: "Schedule a new exam",
    },
  ],
  settings: [],
  showRecent: true,
  maxRecent: 5,
};
