import {
  LayoutDashboard,
  CheckSquare,
  Package,
  Globe,
  CreditCard,
  BarChart3,
  Mail,
  User,
  Plus,
} from "lucide-react";
import type { SearchConfig } from "./types";

export const saasSearchConfig: SearchConfig = {
  navigation: [
    {
      id: "dashboard",
      title: "Dashboard",
      type: "navigation",
      href: "/dashboard",
      icon: LayoutDashboard,
      keywords: ["home", "overview", "main"],
      breadcrumb: ["SaaS"],
    },
    {
      id: "kanban",
      title: "Kanban",
      type: "navigation",
      href: "/kanban",
      icon: CheckSquare,
      keywords: ["board", "tasks", "projects"],
      breadcrumb: ["SaaS"],
    },
    {
      id: "products",
      title: "Products",
      type: "navigation",
      href: "/product",
      icon: Package,
      keywords: ["items", "catalog"],
      breadcrumb: ["SaaS"],
    },
    {
      id: "domains",
      title: "Domains",
      type: "navigation",
      href: "/domains",
      icon: Globe,
      keywords: ["urls", "websites"],
      breadcrumb: ["SaaS"],
    },
    {
      id: "billing",
      title: "Billing",
      type: "navigation",
      href: "/billing",
      icon: CreditCard,
      keywords: ["payments", "invoices", "subscription"],
      breadcrumb: ["SaaS"],
    },
    {
      id: "observability",
      title: "Observability",
      type: "navigation",
      href: "/observability",
      icon: BarChart3,
      keywords: ["monitoring", "logs", "metrics"],
      breadcrumb: ["SaaS"],
    },
    {
      id: "tenants",
      title: "Tenants",
      type: "navigation",
      href: "/tenants",
      icon: Mail,
      keywords: ["schools", "organizations", "clients"],
      breadcrumb: ["SaaS"],
    },
    {
      id: "profile",
      title: "Profile",
      type: "navigation",
      href: "/profile",
      icon: User,
      keywords: ["settings", "account", "preferences"],
      breadcrumb: ["SaaS"],
    },
  ],
  actions: [
    {
      id: "new-product",
      title: "New Product",
      type: "action",
      icon: Plus,
      href: "/product/new",
      keywords: ["create", "add"],
      description: "Create a new product",
    },
    {
      id: "new-domain",
      title: "New Domain",
      type: "action",
      icon: Plus,
      href: "/domains/new",
      keywords: ["create", "add", "register"],
      description: "Register a new domain",
    },
  ],
  settings: [],
  showRecent: true,
  maxRecent: 5,
};
