/**
 * Icon Registry
 *
 * Central registry of all icons with comprehensive metadata.
 * Icons are organized by category and include search tags.
 *
 * Categories:
 * - SYSTEM: Core UI icons (buttons, navigation, interface)
 * - INTEGRATIONS: Company/technology logos
 * - CONTENT: Document and file icons
 * - APPLICATIONS: App-specific icons
 * - PRODUCTIVITY: Workflow and productivity icons
 * - DEVELOPMENT: Developer tools and code icons
 * - PROGRAMMING: Language-specific icons
 * - RATINGS: Rating/quality indicators
 * - SHAPES: Geometric shapes
 * - ILLUSTRATIONS: Anthropic design system illustrations
 * - BRANDING: Brand identity icons
 */

// Import directly from category files to avoid circular dependency with index.tsx
import { AnthropicIcons } from "./anthropic"
import * as AppIcons from "./categories/apps"
import * as ContentIcons from "./categories/content"
import * as DevelopmentIcons from "./categories/development"
import * as IntegrationIcons from "./categories/integrations"
import * as ProductivityIcons from "./categories/productivity"
import * as ProgrammingIcons from "./categories/programming"
import * as RatingIcons from "./categories/ratings"
import * as ShapeIcons from "./categories/shapes"
import * as SystemIcons from "./categories/system"
import type { IconMetadata, IconRegistry } from "./types"
import { IconCategory } from "./types"

export const iconRegistry: IconRegistry = [
  // ============================================
  // SYSTEM ICONS - Core UI elements
  // ============================================
  {
    id: "logo",
    name: "Logo",
    component: SystemIcons.LogoIcon,
    category: IconCategory.BRANDING,
    tags: ["logo", "brand", "identity", "hexagon"],
    description: "Main application logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "patreon",
    name: "Patreon",
    component: SystemIcons.PatreonIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["patreon", "sponsor", "support", "funding", "creator"],
    description: "Patreon school-dashboard logo for sponsorship links",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "coffee",
    name: "Coffee",
    component: SystemIcons.CoffeeIcon,
    category: IconCategory.SYSTEM,
    tags: ["coffee", "cup", "drink", "buy-me-a-coffee", "support"],
    description: "Coffee cup icon for donation/support links",
    viewBox: "-2 -6 24 24",
    customizable: true,
  },
  {
    id: "onboarding",
    name: "Onboarding",
    component: SystemIcons.OnboardingIcon,
    category: IconCategory.SYSTEM,
    tags: ["onboarding", "setup", "wizard", "steps", "introduction"],
    description: "Onboarding/setup wizard icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "notification",
    name: "Notification",
    component: SystemIcons.NotificationIcon,
    category: IconCategory.SYSTEM,
    tags: ["notification", "bell", "alert", "reminder", "push"],
    description: "Bell notification icon",
    viewBox: "0 0 32 32",
    customizable: true,
  },
  {
    id: "authentication",
    name: "Authentication",
    component: SystemIcons.AuthenticationIcon,
    category: IconCategory.SYSTEM,
    tags: ["auth", "authentication", "security", "shield", "protect"],
    description: "Shield icon for authentication/security",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "subscription",
    name: "Subscription",
    component: SystemIcons.SubscriptionIcon,
    category: IconCategory.FINANCE,
    tags: ["subscription", "payment", "stripe", "billing", "money"],
    description: "Stripe S logo for subscription/payment",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "dashboard",
    name: "Dashboard",
    component: SystemIcons.DashboardIcon,
    category: IconCategory.SYSTEM,
    tags: ["dashboard", "grid", "overview", "panels", "widgets"],
    description: "Dashboard grid layout icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "invoice",
    name: "Invoice",
    component: SystemIcons.InvoiceIcon,
    category: IconCategory.FINANCE,
    tags: ["invoice", "receipt", "bill", "document", "payment"],
    description: "Invoice/receipt document icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "salary",
    name: "Salary",
    component: SystemIcons.SalaryIcon,
    category: IconCategory.FINANCE,
    tags: ["salary", "payroll", "money", "bag", "payment", "wage"],
    description: "Money bag icon for salary/payroll",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "timesheet",
    name: "Timesheet",
    component: SystemIcons.TimesheetIcon,
    category: IconCategory.SYSTEM,
    tags: ["timesheet", "clock", "time", "hours", "tracking", "schedule"],
    description: "Clock icon for time tracking",
    viewBox: "0 0 20 20",
    customizable: true,
  },
  {
    id: "trash",
    name: "Trash",
    component: SystemIcons.TrashIcon,
    category: IconCategory.SYSTEM,
    tags: ["trash", "delete", "remove", "bin", "garbage"],
    description: "Trash bin for delete actions",
    viewBox: "0 0 20 20",
    customizable: true,
  },

  // ============================================
  // COMMON UI ICONS - Migrated from lucide-react
  // ============================================
  {
    id: "alert-circle",
    name: "Alert Circle",
    component: SystemIcons.AlertCircleIcon,
    category: IconCategory.SYSTEM,
    tags: ["alert", "circle", "warning", "error", "notification", "danger"],
    description: "Alert/warning indicator",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "refresh",
    name: "Refresh",
    component: SystemIcons.RefreshCwIcon,
    category: IconCategory.SYSTEM,
    tags: ["refresh", "reload", "sync", "update", "rotate", "retry"],
    description: "Refresh/reload action icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "moon",
    name: "Moon",
    component: SystemIcons.MoonIcon,
    category: IconCategory.SYSTEM,
    tags: ["moon", "dark", "night", "theme", "mode"],
    description: "Moon icon for dark mode toggle",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "sun",
    name: "Sun",
    component: SystemIcons.SunIcon,
    category: IconCategory.SYSTEM,
    tags: ["sun", "light", "day", "theme", "mode", "bright"],
    description: "Sun icon for light mode toggle",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "calendar",
    name: "Calendar",
    component: SystemIcons.CalendarIcon,
    category: IconCategory.SYSTEM,
    tags: ["calendar", "date", "schedule", "event", "time", "month"],
    description: "Calendar for date selection",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "search",
    name: "Search",
    component: SystemIcons.SearchIcon,
    category: IconCategory.SYSTEM,
    tags: ["search", "find", "magnify", "lookup", "query"],
    description: "Search/find icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "file-text",
    name: "File Text",
    component: SystemIcons.FileTextIcon,
    category: IconCategory.CONTENT,
    tags: ["file", "text", "document", "page", "paper"],
    description: "Text document icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "upload",
    name: "Upload",
    component: SystemIcons.UploadIcon,
    category: IconCategory.SYSTEM,
    tags: ["upload", "send", "export", "share", "cloud"],
    description: "Upload file action",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "download",
    name: "Download",
    component: SystemIcons.DownloadIcon,
    category: IconCategory.SYSTEM,
    tags: ["download", "save", "import", "get", "fetch"],
    description: "Download file action",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "arrow-left",
    name: "Arrow Left",
    component: SystemIcons.ArrowLeftIcon,
    category: IconCategory.SYSTEM,
    tags: ["arrow", "left", "back", "previous", "navigate"],
    description: "Left arrow for navigation",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "arrow-right",
    name: "Arrow Right",
    component: SystemIcons.ArrowRightIcon,
    category: IconCategory.SYSTEM,
    tags: ["arrow", "right", "forward", "next", "navigate"],
    description: "Right arrow for navigation",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "chevron-down",
    name: "Chevron Down",
    component: SystemIcons.ChevronDownIcon,
    category: IconCategory.SYSTEM,
    tags: ["chevron", "down", "expand", "dropdown", "more"],
    description: "Chevron down for dropdowns/expansion",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "chevron-up",
    name: "Chevron Up",
    component: SystemIcons.ChevronUpIcon,
    category: IconCategory.SYSTEM,
    tags: ["chevron", "up", "collapse", "less", "close"],
    description: "Chevron up for collapse actions",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "chevron-left",
    name: "Chevron Left",
    component: SystemIcons.ChevronLeftIcon,
    category: IconCategory.SYSTEM,
    tags: ["chevron", "left", "previous", "back", "navigate"],
    description: "Chevron left for pagination",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "chevron-right",
    name: "Chevron Right",
    component: SystemIcons.ChevronRightIcon,
    category: IconCategory.SYSTEM,
    tags: ["chevron", "right", "next", "forward", "navigate"],
    description: "Chevron right for pagination",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "check",
    name: "Check",
    component: SystemIcons.CheckIcon,
    category: IconCategory.SYSTEM,
    tags: ["check", "success", "done", "complete", "tick", "ok"],
    description: "Checkmark for success/completion",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "x",
    name: "X",
    component: SystemIcons.XIcon,
    category: IconCategory.SYSTEM,
    tags: ["x", "close", "cancel", "remove", "dismiss"],
    description: "X icon for close/cancel actions",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "plus",
    name: "Plus",
    component: SystemIcons.PlusIcon,
    category: IconCategory.SYSTEM,
    tags: ["plus", "add", "new", "create", "increase"],
    description: "Plus icon for add actions",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "minus",
    name: "Minus",
    component: SystemIcons.MinusIcon,
    category: IconCategory.SYSTEM,
    tags: ["minus", "remove", "subtract", "decrease", "reduce"],
    description: "Minus icon for remove actions",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "spinner",
    name: "Spinner",
    component: SystemIcons.Loader2Icon,
    category: IconCategory.SYSTEM,
    tags: ["spinner", "loading", "wait", "progress", "loader"],
    description: "Loading spinner animation",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "more-horizontal",
    name: "More Horizontal",
    component: SystemIcons.MoreHorizontalIcon,
    category: IconCategory.SYSTEM,
    tags: ["more", "horizontal", "dots", "menu", "options", "ellipsis"],
    description: "Horizontal dots menu icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "more-vertical",
    name: "More Vertical",
    component: SystemIcons.MoreVerticalIcon,
    category: IconCategory.SYSTEM,
    tags: ["more", "vertical", "dots", "menu", "options", "kebab"],
    description: "Vertical dots menu icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "settings",
    name: "Settings",
    component: SystemIcons.SettingsIcon,
    category: IconCategory.SYSTEM,
    tags: ["settings", "gear", "cog", "preferences", "config"],
    description: "Settings/preferences gear icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "user",
    name: "User",
    component: SystemIcons.UserIcon,
    category: IconCategory.SYSTEM,
    tags: ["user", "person", "profile", "account", "avatar"],
    description: "Single user/profile icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "users",
    name: "Users",
    component: SystemIcons.UsersIcon,
    category: IconCategory.SYSTEM,
    tags: ["users", "people", "group", "team", "members"],
    description: "Multiple users/team icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "mail",
    name: "Mail",
    component: SystemIcons.MailIcon,
    category: IconCategory.COMMUNICATION,
    tags: ["mail", "email", "envelope", "message", "inbox"],
    description: "Email/mail icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "eye",
    name: "Eye",
    component: SystemIcons.EyeIcon,
    category: IconCategory.SYSTEM,
    tags: ["eye", "view", "visible", "show", "watch", "see"],
    description: "Eye icon for visibility toggle",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "eye-off",
    name: "Eye Off",
    component: SystemIcons.EyeOffIcon,
    category: IconCategory.SYSTEM,
    tags: ["eye", "off", "hidden", "invisible", "hide", "private"],
    description: "Eye off icon for hidden state",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "lock",
    name: "Lock",
    component: SystemIcons.LockIcon,
    category: IconCategory.SYSTEM,
    tags: ["lock", "secure", "password", "protected", "private"],
    description: "Lock icon for security/password",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "edit",
    name: "Edit",
    component: SystemIcons.EditIcon,
    category: IconCategory.SYSTEM,
    tags: ["edit", "pencil", "modify", "change", "update", "write"],
    description: "Pencil icon for edit actions",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "copy",
    name: "Copy",
    component: SystemIcons.CopyIcon,
    category: IconCategory.SYSTEM,
    tags: ["copy", "duplicate", "clone", "clipboard"],
    description: "Copy to clipboard icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },

  // ============================================
  // INTEGRATION ICONS - Technology logos
  // ============================================
  {
    id: "nextjs",
    name: "Next.js",
    component: IntegrationIcons.NextjsIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["nextjs", "next", "react", "framework", "vercel"],
    description: "Next.js framework logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "react",
    name: "React",
    component: IntegrationIcons.ReactIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["react", "reactjs", "library", "frontend", "ui"],
    description: "React library logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "typescript",
    name: "TypeScript",
    component: IntegrationIcons.TypescriptIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["typescript", "ts", "javascript", "types", "microsoft"],
    description: "TypeScript language logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "tailwindcss",
    name: "Tailwind CSS",
    component: IntegrationIcons.TailwindcssIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["tailwind", "tailwindcss", "css", "styling", "utility"],
    description: "Tailwind CSS framework logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "shadcnui",
    name: "shadcn/ui",
    component: IntegrationIcons.ShadcnuiIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["shadcn", "ui", "components", "radix"],
    description: "shadcn/ui component library logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "planetscale",
    name: "PlanetScale",
    component: IntegrationIcons.PlanetscaleIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["planetscale", "database", "mysql", "serverless"],
    description: "PlanetScale database logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "prisma",
    name: "Prisma",
    component: IntegrationIcons.PrismaIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["prisma", "orm", "database", "typescript"],
    description: "Prisma ORM logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "zod",
    name: "Zod",
    component: IntegrationIcons.ZodIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["zod", "validation", "schema", "typescript"],
    description: "Zod validation library logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "react-hook-form",
    name: "React Hook Form",
    component: IntegrationIcons.ReactHookFormIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["react-hook-form", "form", "hooks", "validation"],
    description: "React Hook Form library logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "claude",
    name: "Claude",
    component: IntegrationIcons.ClaudeIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["claude", "anthropic", "ai", "assistant", "llm"],
    description: "Claude AI assistant logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "github",
    name: "GitHub",
    component: IntegrationIcons.GitHubIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["github", "git", "version-control", "code", "repository"],
    description: "GitHub school-dashboard logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "git",
    name: "Git",
    component: IntegrationIcons.GitIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["git", "version-control", "source", "branch"],
    description: "Git version control logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "figma",
    name: "Figma",
    component: IntegrationIcons.FigmaIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["figma", "design", "ui", "prototype", "graphics"],
    description: "Figma design tool logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "discord",
    name: "Discord",
    component: IntegrationIcons.DiscordIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["discord", "chat", "community", "voice", "gaming"],
    description: "Discord school-dashboard logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "framer",
    name: "Framer",
    component: IntegrationIcons.FramerIcon,
    category: IconCategory.INTEGRATIONS,
    tags: ["framer", "motion", "animation", "design", "prototype"],
    description: "Framer design/animation logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },

  // ============================================
  // CONTENT ICONS - Documents and files
  // ============================================
  {
    id: "docs",
    name: "Documentation",
    component: ContentIcons.DocsIcon,
    category: IconCategory.CONTENT,
    tags: ["docs", "documentation", "guide", "manual", "help"],
    description: "Documentation/guide icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "report",
    name: "Report",
    component: ContentIcons.ReportIcon,
    category: IconCategory.CONTENT,
    tags: ["report", "chart", "analytics", "data", "statistics"],
    description: "Report/analytics icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "pdf",
    name: "PDF",
    component: ContentIcons.PdfIcon,
    category: IconCategory.CONTENT,
    tags: ["pdf", "document", "file", "adobe", "portable"],
    description: "PDF document icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "logbook",
    name: "Logbook",
    component: ContentIcons.LogbookIcon,
    category: IconCategory.CONTENT,
    tags: ["logbook", "journal", "diary", "record", "history"],
    description: "Logbook/journal icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "proposal",
    name: "Proposal",
    component: ContentIcons.ProposalIcon,
    category: IconCategory.CONTENT,
    tags: ["proposal", "document", "plan", "submission", "draft"],
    description: "Proposal document icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },

  // ============================================
  // APPLICATION ICONS - App-specific
  // ============================================
  {
    id: "starter-kit",
    name: "Starter Kit",
    component: AppIcons.StarterKitIcon,
    category: IconCategory.APPLICATIONS,
    tags: ["starter", "kit", "template", "boilerplate", "begin"],
    description: "Starter kit/template icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "contentlayer",
    name: "Contentlayer",
    component: AppIcons.ContentlayerIcon,
    category: IconCategory.APPLICATIONS,
    tags: ["contentlayer", "content", "mdx", "markdown", "cms"],
    description: "Contentlayer CMS icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "math",
    name: "Math",
    component: AppIcons.MathIcon,
    category: IconCategory.ACADEMIC,
    tags: ["math", "mathematics", "calculate", "formula", "equation"],
    description: "Mathematics/calculation icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "flow",
    name: "Flow",
    component: AppIcons.FlowIcon,
    category: IconCategory.APPLICATIONS,
    tags: ["flow", "workflow", "process", "diagram", "automation"],
    description: "Workflow/process icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "chatbot",
    name: "Chatbot",
    component: AppIcons.ChatbotIcon,
    category: IconCategory.APPLICATIONS,
    tags: ["chatbot", "ai", "assistant", "conversation", "bot"],
    description: "AI chatbot icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "leads",
    name: "Leads",
    component: AppIcons.LeadsIcon,
    category: IconCategory.APPLICATIONS,
    tags: ["leads", "crm", "sales", "contacts", "prospects"],
    description: "Sales leads/CRM icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },

  // ============================================
  // PRODUCTIVITY ICONS
  // ============================================
  {
    id: "rules",
    name: "Rules",
    component: ProductivityIcons.RulesIcon,
    category: IconCategory.PRODUCTIVITY,
    tags: ["rules", "policies", "guidelines", "regulations"],
    description: "Rules/policies icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "prompts",
    name: "Prompts",
    component: ProductivityIcons.PromptsIcon,
    category: IconCategory.PRODUCTIVITY,
    tags: ["prompts", "ai", "templates", "instructions"],
    description: "AI prompts/templates icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "tweets",
    name: "Tweets",
    component: ProductivityIcons.TweetsIcon,
    category: IconCategory.PRODUCTIVITY,
    tags: ["tweets", "twitter", "social", "posts", "x"],
    description: "Twitter/X posts icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },

  // ============================================
  // DEVELOPMENT ICONS
  // ============================================
  {
    id: "mcp",
    name: "MCP",
    component: DevelopmentIcons.McpIcon,
    category: IconCategory.DEVELOPMENT,
    tags: ["mcp", "model-context-protocol", "ai", "tools"],
    description: "Model Context Protocol icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "cursor",
    name: "Cursor",
    component: DevelopmentIcons.CursorIcon,
    category: IconCategory.DEVELOPMENT,
    tags: ["cursor", "ide", "editor", "ai", "code"],
    description: "Cursor AI IDE icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "extensions",
    name: "Extensions",
    component: DevelopmentIcons.ExtensionsIcon,
    category: IconCategory.DEVELOPMENT,
    tags: ["extensions", "plugins", "addons", "modules"],
    description: "Extensions/plugins icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "mcp-alt",
    name: "MCP Alt",
    component: DevelopmentIcons.McpIconAlt,
    category: IconCategory.DEVELOPMENT,
    tags: ["mcp", "alternative", "tools", "protocol"],
    description: "Alternative MCP icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },

  // ============================================
  // PROGRAMMING LANGUAGE ICONS
  // ============================================
  {
    id: "python",
    name: "Python",
    component: ProgrammingIcons.PythonIcon,
    category: IconCategory.PROGRAMMING,
    tags: ["python", "language", "programming", "code", "py"],
    description: "Python programming language logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "rust",
    name: "Rust",
    component: ProgrammingIcons.RustIcon,
    category: IconCategory.PROGRAMMING,
    tags: ["rust", "language", "programming", "systems", "rs"],
    description: "Rust programming language logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "r",
    name: "R",
    component: ProgrammingIcons.RIcon,
    category: IconCategory.PROGRAMMING,
    tags: ["r", "language", "statistics", "data", "analysis"],
    description: "R programming language logo",
    viewBox: "0 0 24 24",
    customizable: true,
  },

  // ============================================
  // RATING ICONS
  // ============================================
  {
    id: "excellent",
    name: "Excellent",
    component: RatingIcons.ExcellentIcon,
    category: IconCategory.RATINGS,
    tags: ["excellent", "rating", "best", "top", "5-star"],
    description: "Excellent/top rating icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "good",
    name: "Good",
    component: RatingIcons.GoodIcon,
    category: IconCategory.RATINGS,
    tags: ["good", "rating", "positive", "thumbs-up", "4-star"],
    description: "Good rating icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "average",
    name: "Average",
    component: RatingIcons.AverageIcon,
    category: IconCategory.RATINGS,
    tags: ["average", "rating", "medium", "neutral", "3-star"],
    description: "Average rating icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "poor",
    name: "Poor",
    component: RatingIcons.PoorIcon,
    category: IconCategory.RATINGS,
    tags: ["poor", "rating", "bad", "low", "1-star"],
    description: "Poor/low rating icon",
    viewBox: "0 0 24 24",
    customizable: true,
  },

  // ============================================
  // SHAPE ICONS
  // ============================================
  {
    id: "triangle",
    name: "Triangle",
    component: ShapeIcons.TriangleIcon,
    category: IconCategory.SHAPES,
    tags: ["triangle", "shape", "geometry", "polygon", "warning"],
    description: "Triangle geometric shape",
    viewBox: "0 0 24 24",
    customizable: true,
  },

  // ============================================
  // ANTHROPIC UI ICONS
  // ============================================
  {
    id: "anthropic-a",
    name: "Anthropic A",
    component: AnthropicIcons.A,
    category: IconCategory.BRANDING,
    tags: ["anthropic", "logo", "a", "brand", "ai"],
    description: "Anthropic A logo mark",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-arrow-right",
    name: "Anthropic Arrow Right",
    component: AnthropicIcons.ArrowRight,
    category: IconCategory.SYSTEM,
    tags: ["arrow", "right", "anthropic", "navigate", "next"],
    description: "Anthropic design arrow right",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-chevron-down",
    name: "Anthropic Chevron Down",
    component: AnthropicIcons.ChevronDown,
    category: IconCategory.SYSTEM,
    tags: ["chevron", "down", "anthropic", "expand"],
    description: "Anthropic design chevron down",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-external-link",
    name: "Anthropic External Link",
    component: AnthropicIcons.ExternalLink,
    category: IconCategory.SYSTEM,
    tags: ["external", "link", "anthropic", "open", "new-tab"],
    description: "Anthropic design external link",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-linkedin",
    name: "Anthropic LinkedIn",
    component: AnthropicIcons.LinkedIn,
    category: IconCategory.INTEGRATIONS,
    tags: ["linkedin", "social", "anthropic", "professional"],
    description: "LinkedIn icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-play",
    name: "Anthropic Play",
    component: AnthropicIcons.Play,
    category: IconCategory.SYSTEM,
    tags: ["play", "video", "anthropic", "media", "start"],
    description: "Play button (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-youtube",
    name: "Anthropic YouTube",
    component: AnthropicIcons.YouTube,
    category: IconCategory.INTEGRATIONS,
    tags: ["youtube", "video", "anthropic", "google"],
    description: "YouTube icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-x-twitter",
    name: "Anthropic X/Twitter",
    component: AnthropicIcons.XTwitter,
    category: IconCategory.INTEGRATIONS,
    tags: ["x", "twitter", "social", "anthropic"],
    description: "X/Twitter icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-quote",
    name: "Anthropic Quote",
    component: AnthropicIcons.Quote,
    category: IconCategory.CONTENT,
    tags: ["quote", "testimonial", "anthropic", "citation"],
    description: "Quote/testimonial icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-announcement",
    name: "Anthropic Announcement",
    component: AnthropicIcons.Announcement,
    category: IconCategory.COMMUNICATION,
    tags: ["announcement", "news", "anthropic", "megaphone"],
    description: "Announcement icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-checklist",
    name: "Anthropic Checklist",
    component: AnthropicIcons.Checklist,
    category: IconCategory.PRODUCTIVITY,
    tags: ["checklist", "todo", "anthropic", "tasks"],
    description: "Checklist icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-book",
    name: "Anthropic Book",
    component: AnthropicIcons.Book,
    category: IconCategory.CONTENT,
    tags: ["book", "read", "anthropic", "library", "learn"],
    description: "Book icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-archive",
    name: "Anthropic Archive",
    component: AnthropicIcons.Archive,
    category: IconCategory.SYSTEM,
    tags: ["archive", "storage", "anthropic", "backup"],
    description: "Archive icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-fuel-pump",
    name: "Anthropic Fuel Pump",
    component: AnthropicIcons.FuelPump,
    category: IconCategory.SYSTEM,
    tags: ["fuel", "gas", "anthropic", "energy", "tokens"],
    description: "Fuel pump icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-devices",
    name: "Anthropic Devices",
    component: AnthropicIcons.Devices,
    category: IconCategory.SYSTEM,
    tags: ["devices", "responsive", "anthropic", "mobile", "desktop"],
    description: "Devices icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-redo",
    name: "Anthropic Redo",
    component: AnthropicIcons.Redo,
    category: IconCategory.SYSTEM,
    tags: ["redo", "repeat", "anthropic", "retry", "again"],
    description: "Redo icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-stopwatch",
    name: "Anthropic Stopwatch",
    component: AnthropicIcons.Stopwatch,
    category: IconCategory.SYSTEM,
    tags: ["stopwatch", "timer", "anthropic", "time", "speed"],
    description: "Stopwatch icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-calendar-chart",
    name: "Anthropic Calendar Chart",
    component: AnthropicIcons.CalendarChart,
    category: IconCategory.PRODUCTIVITY,
    tags: ["calendar", "chart", "anthropic", "schedule", "analytics"],
    description: "Calendar with chart (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-sparkle",
    name: "Anthropic Sparkle",
    component: AnthropicIcons.Sparkle,
    category: IconCategory.SYSTEM,
    tags: ["sparkle", "ai", "anthropic", "magic", "new"],
    description: "Sparkle icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-grant-proposal",
    name: "Anthropic Grant Proposal",
    component: AnthropicIcons.GrantProposal,
    category: IconCategory.CONTENT,
    tags: ["grant", "proposal", "anthropic", "funding", "document"],
    description: "Grant proposal icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-hands-build",
    name: "Anthropic Hands Build",
    component: AnthropicIcons.HandsBuild,
    category: IconCategory.ILLUSTRATIONS,
    tags: ["hands", "build", "anthropic", "create", "construct"],
    description: "Hands building illustration (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-code-window",
    name: "Anthropic Code Window",
    component: AnthropicIcons.CodeWindow,
    category: IconCategory.DEVELOPMENT,
    tags: ["code", "window", "anthropic", "terminal", "ide"],
    description: "Code window icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-location-pin",
    name: "Anthropic Location Pin",
    component: AnthropicIcons.LocationPin,
    category: IconCategory.SYSTEM,
    tags: ["location", "pin", "anthropic", "map", "place"],
    description: "Location pin icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-notebook",
    name: "Anthropic Notebook",
    component: AnthropicIcons.Notebook,
    category: IconCategory.CONTENT,
    tags: ["notebook", "notes", "anthropic", "journal", "write"],
    description: "Notebook icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-shield-check",
    name: "Anthropic Shield Check",
    component: AnthropicIcons.ShieldCheck,
    category: IconCategory.SYSTEM,
    tags: ["shield", "check", "anthropic", "security", "verified"],
    description: "Shield check icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-pencil",
    name: "Anthropic Pencil",
    component: AnthropicIcons.Pencil,
    category: IconCategory.SYSTEM,
    tags: ["pencil", "edit", "anthropic", "write", "draw"],
    description: "Pencil icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-briefcase",
    name: "Anthropic Briefcase",
    component: AnthropicIcons.Briefcase,
    category: IconCategory.SYSTEM,
    tags: ["briefcase", "work", "anthropic", "business", "job"],
    description: "Briefcase icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-flow",
    name: "Anthropic Flow",
    component: AnthropicIcons.Flow,
    category: IconCategory.PRODUCTIVITY,
    tags: ["flow", "workflow", "anthropic", "process", "diagram"],
    description: "Flow diagram icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-task-list",
    name: "Anthropic Task List",
    component: AnthropicIcons.TaskList,
    category: IconCategory.PRODUCTIVITY,
    tags: ["task", "list", "anthropic", "todo", "checklist"],
    description: "Task list icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-copy",
    name: "Anthropic Copy",
    component: AnthropicIcons.Copy,
    category: IconCategory.SYSTEM,
    tags: ["copy", "duplicate", "anthropic", "clipboard"],
    description: "Copy icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-globe",
    name: "Anthropic Globe",
    component: AnthropicIcons.Globe,
    category: IconCategory.SYSTEM,
    tags: ["globe", "world", "anthropic", "internet", "web"],
    description: "Globe icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-chat",
    name: "Anthropic Chat",
    component: AnthropicIcons.Chat,
    category: IconCategory.COMMUNICATION,
    tags: ["chat", "message", "anthropic", "conversation", "talk"],
    description: "Chat icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-lightning",
    name: "Anthropic Lightning",
    component: AnthropicIcons.Lightning,
    category: IconCategory.SYSTEM,
    tags: ["lightning", "fast", "anthropic", "speed", "instant"],
    description: "Lightning icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },
  {
    id: "anthropic-terminal",
    name: "Anthropic Terminal",
    component: AnthropicIcons.Terminal,
    category: IconCategory.DEVELOPMENT,
    tags: ["terminal", "cli", "anthropic", "command", "shell"],
    description: "Terminal icon (Anthropic style)",
    viewBox: "0 0 24 24",
    customizable: true,
  },

  // ============================================
  // ANTHROPIC ILLUSTRATIONS - Core Values
  // ============================================
  {
    id: "network-nodes",
    name: "Network Nodes",
    component: () => null as any,
    category: IconCategory.ILLUSTRATIONS,
    tags: [
      "anthropic",
      "network",
      "nodes",
      "connected",
      "circles",
      "courage",
      "core-values",
    ],
    description:
      "Interconnected network of nodes representing courage and connection. From Anthropic design system.",
    viewBox: "0 0 1200 1200",
    customizable: false,
    filePath: "/anthropic/claude-code-best-practices.svg",
    createdAt: new Date("2025-12-03"),
    author: "Anthropic",
  },
  {
    id: "growth-flourish",
    name: "Growth Flourish",
    component: () => null as any,
    category: IconCategory.ILLUSTRATIONS,
    tags: [
      "anthropic",
      "growth",
      "flourish",
      "person",
      "organic",
      "wisdom",
      "core-values",
    ],
    description:
      "Abstract figure with organic flourishing elements representing wisdom and growth. From Anthropic design system.",
    viewBox: "0 0 1000 1000",
    customizable: false,
    filePath: "/anthropic/category-06.svg",
    createdAt: new Date("2025-12-03"),
    author: "Anthropic",
  },
  {
    id: "frame-boundary",
    name: "Frame Boundary",
    component: () => null as any,
    category: IconCategory.ILLUSTRATIONS,
    tags: [
      "anthropic",
      "frame",
      "boundary",
      "rounded",
      "rectangle",
      "loyalty",
      "core-values",
    ],
    description:
      "Rounded rectangle frame representing loyalty and commitment boundaries. From Anthropic design system.",
    viewBox: "0 0 1200 1200",
    customizable: false,
    filePath: "/anthropic/think-tool.svg",
    createdAt: new Date("2025-12-03"),
    author: "Anthropic",
  },
  {
    id: "reaching-ascent",
    name: "Reaching Ascent",
    component: () => null as any,
    category: IconCategory.ILLUSTRATIONS,
    tags: [
      "anthropic",
      "reaching",
      "ascent",
      "climbing",
      "aspiring",
      "ambition",
      "core-values",
    ],
    description:
      "Abstract figure reaching upward with dynamic motion representing ambition. From Anthropic design system.",
    viewBox: "0 0 1000 1000",
    customizable: false,
    filePath: "/anthropic/category-03.svg",
    createdAt: new Date("2025-12-03"),
    author: "Anthropic",
  },
]

/**
 * Helper function to get icon count
 */
export function getIconCount(): number {
  return iconRegistry.length
}

/**
 * Helper function to get all icon IDs
 */
export function getAllIconIds(): string[] {
  return iconRegistry.map((icon) => icon.id)
}

/**
 * Helper function to register a new icon
 * (Used during development/migration)
 */
export function registerIcon(metadata: IconMetadata): void {
  // Check for duplicates
  const exists = iconRegistry.some((icon) => icon.id === metadata.id)
  if (exists) {
    console.warn(`Icon "${metadata.id}" already registered. Skipping.`)
    return
  }

  iconRegistry.push(metadata)
}
