// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details
//
// Transport route fees → billing. Idempotency is the core contract: re-running
// a billing month must create nothing new at any of the three layers
// (FeeStructure / FeeAssignment / UserInvoice).
import { auth } from "@/auth"
import { beforeEach, describe, expect, it, vi } from "vitest"

import { db } from "@/lib/db"
import { ensureInvoicesForAssignment } from "@/lib/fee-invoice-sync"
import { getTenantContext } from "@/lib/tenant-context"
import { provisionTransportFees } from "@/components/school-dashboard/finance/fees/transport-provisioning"

vi.mock("@/auth", () => ({ auth: vi.fn() }))
vi.mock("@/lib/tenant-context", () => ({ getTenantContext: vi.fn() }))
vi.mock("next/cache", () => ({ revalidatePath: vi.fn() }))
vi.mock("@/components/school-dashboard/finance/lib/permissions", () => ({
  checkFinancePermission: vi.fn().mockResolvedValue(true),
}))
vi.mock("@/lib/fee-invoice-sync", () => ({
  ensureInvoicesForAssignment: vi
    .fn()
    .mockResolvedValue({ invoicesCreated: 1 }),
}))
vi.mock("@/lib/db", () => {
  const dbMock: any = {
    school: { findUnique: vi.fn() },
    schoolYear: { findFirst: vi.fn() },
    routeAssignment: { findMany: vi.fn() },
    feeStructure: { findFirst: vi.fn(), create: vi.fn() },
    feeAssignment: { findMany: vi.fn(), create: vi.fn() },
  }
  dbMock.$transaction = vi.fn((cb: (tx: any) => any) => cb(dbMock))
  return { db: dbMock }
})

const SCHOOL_ID = "school-1"

beforeEach(() => {
  vi.clearAllMocks()
  vi.mocked(db.$transaction).mockImplementation((cb: any) => cb(db))
  vi.mocked(auth).mockResolvedValue({
    user: { id: "admin-1", role: "ADMIN", schoolId: SCHOOL_ID },
  } as never)
  vi.mocked(getTenantContext).mockResolvedValue({
    schoolId: SCHOOL_ID,
    subdomain: "demo",
  } as never)
  vi.mocked(db.school.findUnique).mockResolvedValue({
    currency: "SDG",
    preferredLanguage: "en",
  } as never)
  vi.mocked(db.schoolYear.findFirst).mockResolvedValue({
    yearName: "2026-2027",
  } as never)
  vi.mocked(db.routeAssignment.findMany).mockResolvedValue([
    {
      studentId: "st-1",
      route: { id: "route-1", name: "North Route", monthlyFee: 200 },
    },
    {
      studentId: "st-2",
      route: { id: "route-1", name: "North Route", monthlyFee: 200 },
    },
    // Route with no fee — must bill nothing.
    {
      studentId: "st-3",
      route: { id: "route-free", name: "Walkers", monthlyFee: null },
    },
  ] as never)
})

describe("provisionTransportFees", () => {
  it("creates a per-route structure, per-student assignments, and invoices", async () => {
    vi.mocked(db.feeStructure.findFirst).mockResolvedValue(null)
    vi.mocked(db.feeStructure.create).mockResolvedValue({ id: "fs-1" } as never)
    vi.mocked(db.feeAssignment.findMany).mockResolvedValue([] as never)
    vi.mocked(db.feeAssignment.create)
      .mockResolvedValueOnce({ id: "fa-1" } as never)
      .mockResolvedValueOnce({ id: "fa-2" } as never)

    const result = await provisionTransportFees({ billingMonth: "2026-07" })

    expect(result.success).toBe(true)
    if (result.success && result.data) {
      expect(result.data.routesProcessed).toBe(1)
      expect(result.data.studentsProvisioned).toBe(2)
      expect(result.data.invoicesCreated).toBe(2)
    }
    expect(db.feeStructure.create).toHaveBeenCalledTimes(1)
    expect(db.feeStructure.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          transportFee: 200,
          totalAmount: 200,
          installments: 1,
          isAutoGenerated: true,
          sourceSignals: expect.objectContaining({
            transportRouteId: "route-1",
            billingMonth: "2026-07",
          }),
        }),
      })
    )
    expect(ensureInvoicesForAssignment).toHaveBeenCalledTimes(2)
  })

  it("is idempotent: a re-run finds the structure and skips assigned students", async () => {
    vi.mocked(db.feeStructure.findFirst).mockResolvedValue({
      id: "fs-1",
    } as never)
    vi.mocked(db.feeAssignment.findMany).mockResolvedValue([
      { studentId: "st-1" },
      { studentId: "st-2" },
    ] as never)

    const result = await provisionTransportFees({ billingMonth: "2026-07" })

    expect(result.success).toBe(true)
    if (result.success && result.data) {
      expect(result.data.studentsProvisioned).toBe(0)
      expect(result.data.skippedExisting).toBe(2)
      expect(result.data.invoicesCreated).toBe(0)
    }
    expect(db.feeStructure.create).not.toHaveBeenCalled()
    expect(db.feeAssignment.create).not.toHaveBeenCalled()
    expect(ensureInvoicesForAssignment).not.toHaveBeenCalled()
  })

  it("rejects a malformed billing month", async () => {
    const result = await provisionTransportFees({ billingMonth: "07-2026" })
    expect(result.success).toBe(false)
    expect(db.routeAssignment.findMany).not.toHaveBeenCalled()
  })

  it("denies without fees.create permission", async () => {
    const { checkFinancePermission } =
      await import("@/components/school-dashboard/finance/lib/permissions")
    vi.mocked(checkFinancePermission).mockResolvedValueOnce(false)

    const result = await provisionTransportFees({ billingMonth: "2026-07" })
    expect(result.success).toBe(false)
  })
})
