// Copyright (c) 2025-present databayt
// Licensed under SSPL-1.0 -- see LICENSE for details

/**
 * Which fee structures an OFFER quotes — the same set `ensureStudentFeeAssignments`
 * (src/lib/fee-auto-assign.ts) will assign at enrollment, resolved before a
 * Student exists.
 *
 * Three sources match an applicant's grade, mirroring the enrollment side:
 *   1. admin-created school-wide structures (classId null, not auto-generated)
 *   2. class-linked structures whose class belongs to the grade
 *   3. auto-generated per-grade structures (sourceSignals.gradeId) — a
 *      MUTUALLY-EXCLUSIVE variant group (base + per-stream / per-type prices
 *      of the same grade fee), of which enrollment assigns exactly ONE.
 *
 * The offer used to sum every matching row, and its school-wide arm carried no
 * `isAutoGenerated: false` filter. A school whose grades had several pricing
 * variants — or whose auto-generated rows had no Class to link to and so sat
 * at classId null — was quoted every variant's registration fee added
 * together: one number on the offer page, another on the invoices raised at
 * enrollment. This module is the single place the quote's set is decided.
 */

export interface OfferFeeStructureCandidate {
  id: string
  isAutoGenerated: boolean
  sourceSignals: unknown
}

interface VariantSignals {
  gradeId?: string | null
  streamId?: string | null
  studentType?: string | null
}

function signalsOf(row: OfferFeeStructureCandidate): VariantSignals | null {
  return (row.sourceSignals as VariantSignals | null) ?? null
}

/**
 * Reduce the matched candidates to the set enrollment will assign: every
 * additive row plus ONE variant per auto-generated grade group.
 *
 * Without a student there is no stream / student-type to resolve against, so
 * the BASE variant (no pinned dimension) is preferred — it is the price a
 * family with no special pricing pays. Failing that, the cheapest pinned
 * variant; never a sum of several. Pure and synchronous so it is unit-tested
 * without a database.
 */
export function selectOfferFeeStructures<T extends OfferFeeStructureCandidate>(
  candidates: T[],
  gradeId: string | null,
  amountOf: (row: T) => number
): T[] {
  const additive: T[] = []
  const variants: T[] = []
  for (const row of candidates) {
    if (row.isAutoGenerated && gradeId && signalsOf(row)?.gradeId === gradeId) {
      variants.push(row)
    } else {
      additive.push(row)
    }
  }

  if (variants.length <= 1) return [...additive, ...variants]

  const pinnedDimensions = (row: T): number => {
    const sig = signalsOf(row)
    return (sig?.streamId ? 1 : 0) + (sig?.studentType ? 1 : 0)
  }

  let chosen = variants[0]
  for (const row of variants.slice(1)) {
    const rowPinned = pinnedDimensions(row)
    const chosenPinned = pinnedDimensions(chosen)
    if (
      rowPinned < chosenPinned ||
      (rowPinned === chosenPinned && amountOf(row) < amountOf(chosen))
    ) {
      chosen = row
    }
  }

  return [...additive, chosen]
}

/**
 * The amount the family pays at the offer stage: the registration component
 * (plus any one-time admission component) of every structure that will be
 * assigned, with the campaign's legacy `applicationFee` as the fallback when
 * no structure defines one. Both components are part of the structure's
 * annual total, so the payment is later allocated against the invoices that
 * total raises — it is a deposit on the year, never an extra charge.
 */
export function sumRegistrationFee(
  structures: Array<{
    registrationFee: number | null
    admissionFee: number | null
  }>,
  campaignApplicationFee: number | null
): number {
  let total = 0
  for (const fs of structures) {
    if (fs.registrationFee) total += fs.registrationFee
    if (fs.admissionFee) total += fs.admissionFee
  }
  if (total <= 0 && campaignApplicationFee) {
    return Number(campaignApplicationFee)
  }
  return total
}
